### ISSUE TITLE
"npm run electron-rebuild" has errors.

### ISSUE THREAD

**Issue by Vigor111** [justadudewhohacks/opencv4nodejs#1]
I already installed opencv3.3.0_3

> npm install --save electron-rebuild

this command has no errors.

but when I run the

> npm run electron-rebuild

I got this error.

npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "electron-rebuild"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0

npm ERR! missing script: electron-rebuild
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/.npm/_logs/2017-09-08T19_20_49_789Z-debug.log
users-iMac-5:opencv4nodejs user$ npm run electron-rebuild
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "electron-rebuild"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0

npm ERR! missing script: electron-rebuild
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/.npm/_logs/2017-09-08T19_21_16_440Z-debug.log

**Comment by justadudewhohacks** [comment]
Hey, did you do the following:
> 
> Add the following script to your package.json:
> 
> "electron-rebuild": "electron-rebuild -w opencv4nodejs"

**Comment by Vigor111** [comment]
Yes I already put it in my opencv4nodejs/package.json
it looks like this.

{
  "name": "opencv4nodejs",
  "version": "1.3.2",
  "description": "Transparent OpenCV API for nodejs.",
  "keywords": [
    "opencv",
    "cv",
    "computer vision",
    "image",
    "processing",
    "detection",
    "recognition",
    "tracking",
    "matching",
    "face",
    "hand",
    "gesture"
  ],
  "main": "./lib/opencv4nodejs.js",
  "scripts": {
    "install": "node-gyp rebuild",
    "configure": "node-gyp configure",
    "build": "node-gyp configure build",
    "rebuild": "node-gyp rebuild"
  },
  "author": "justadudewhohacks",
  "license": "ISC",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/justadudewhohacks/opencv4nodejs"
  },
  "gypfile": true,
  "dependencies": {
    "electron-rebuild": "^1.6.0",
    "nan": "^2.6.2"
  },
  "electron-rebuild": "electron-rebuild -w opencv4nodejs"
}

**Comment by justadudewhohacks** [comment]
Did you clone my repository or did you `npm install --save opencv4nodejs`?
This is how one adds scripts to the package.json:
```
"scripts": {
  "electron-rebuild": "electron-rebuild -w opencv4nodejs"
}
```
This should be added to your package.json of your project and not in the opencv4nodejs directory, which should be in /node_modules/opencv4nodejs if you install it locally.

**Comment by justadudewhohacks** [comment]
Closing this issue. An electron example is now available here: https://github.com/justadudewhohacks/opencv-electron
