### ISSUE TITLE
A issue about resize method

### ISSUE THREAD

**Issue by Lanfei** [justadudewhohacks/opencv4nodejs#103]
I resized a image with code:

```js
image = image.resize(92, 122);
console.log(image.rows, image.cols);
```

But what I got is:

```js
92 92
```

**Comment by justadudewhohacks** [comment]
In opencv4nodejs a method call almost always returns the result. Try the following:
```
const resizedImage = image.resize(92, 122);
console.log(resizedImage.rows, resizedImage.cols);
```

**Comment by justadudewhohacks** [comment]
Just figured out, that there's a bug in resize, will fix it asap.

**Comment by justadudewhohacks** [comment]
Should be fixed.

**Comment by Lanfei** [comment]
Thanks very much for your quick response, I have checked the latest version, the bug is fixed. 👍
