### ISSUE TITLE
Not running from different path

### ISSUE THREAD

**Issue by gideono** [justadudewhohacks/opencv4nodejs#108]
After cloning this  repository and playing around with examples. I found an irritating issue, when running the example with i search path e.i
`node examples/asyncFaceDetection.js` this results in a error `empty Mat`
not sure if this is bug or if im using the resource incorrectly.
OS: macOS 10.13.1
Opencv version: 3.3.1_1

**Comment by justadudewhohacks** [comment]
Oh, you are right! This is because I use relative paths in some examples to read the images via cv.imread. I should probably use path.resolve here, to get the absolute path.
