### ISSUE TITLE
npm fails to install

### ISSUE THREAD

**Issue by psylock** [justadudewhohacks/opencv4nodejs#112]
`npm install opencv4nodejs --save

> opencv4nodejs@2.26.1 install /Mobile/node_modules/opencv4nodejs
> node-gyp rebuild

/Mobile/node_modules/opencv4nodejs/lib/utils.js:88
      throw new Error(`no valid .so, .lib or .dylib files found in in OPENCV_LIB_DIR ('${libDir}')`);
      ^

Error: no valid .so, .lib or .dylib files found in in OPENCV_LIB_DIR ('/usr/local/lib')
    at fs.readdir (Mobile/node_modules/opencv4nodejs/lib/utils.js:88:13)
    at FSReqWrap.oncomplete (fs.js:123:15)
gyp: Call to 'node ./lib/libs.js' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
`
I'm on ubuntu 16.04, node v6.12.2, npm  v3.10.10

Thanks,

**Comment by justadudewhohacks** [comment]
Do you have opencv installed?

**Comment by psylock** [comment]
hum... nope. Sorry.
