### ISSUE TITLE
Trying to configure OpenCV to work with matchFeatures.js

### ISSUE THREAD

**Issue by Gektor40k** [justadudewhohacks/opencv4nodejs#115]
justadudewhohacks hello again!) I'm interested in the possibility of match features. but I just cant get the correct work. I checked by example (in matchFeatures.js). During the condition "if (cv.xmodules.xfeatures2d)" I get "skipping SIFT matches", but I compiled opencv with opencv_contrib modules. I also read this forum and came across a similar problem, also build the "install" solution. What I have:
- Builded OpenCV with contrib modules
- Builded Install solution, that provided me folders with include and bin and lib files .
- Environment Variables:
OPENCV_BIN_DIR -> C:\CurrentOpenCV\opencv-master\build\install\x64\vc12\bin
OPENCV_DIR -> C:\CurrentOpenCV\opencv-master\build
OPENCV_INCLUDE_DIR -> C:\CurrentOpenCV\opencv-master\build\install\include
OPENCV_LIB_DIR -> C:\CurrentOpenCV\opencv-master\build\install\x64\vc12\lib
And still does not pass "check if opencv compiled with extra modules and nonfree"
In OpenCV directory a lot of folders with names 'lib', 'dir' etc., I tried a lot of combinations, but I did not get any better. 
Can you tell me what I'm doing wrong?
Thank you for attention :)

**Comment by justadudewhohacks** [comment]
Hi,

can you confirm, that in your 'OPENCV_LIB_DIR' folder there is a .lib file called 'opencv_xfeatures2d3xx'? Which opencv version are you using? 

Also it seems that with opencv 3.2 for example I had to set the OPENCV_ENABLE_NONFREE flag in the cmake configuration. Maybe this does the trick for you.

**Comment by Gektor40k** [comment]
Yes, in OPENCV_LIB_DIR i found file "opencv_xfeatures2d340.lib" (by "340" postfix i think my OpenCV version is 3.4) 
And I set  OPENCV_ENABLE_NONFREE flag in cmake configuration

**Comment by justadudewhohacks** [comment]
Hm, strange. I just checked with opencv3.4 and contrib3.3.1, so it should work. Did you also rebuild the module e.g. npm install each time you did changes to your environment variables?

**Comment by Gektor40k** [comment]
Yes! it worked! I'm perfectly happy!
What I did (you can throw this tutorial on the future to any slow guys like me):
- I did everything from the beginning. Download opencv (source, 3.2) and opencv_contrib_modules (archive, also version 3.2)
- Configuration in CMake (as in the other OpebCv install tutorials). Set the OPENCV_ENABLE_NONFREE flag, EXTRA_MODULES_PATH goes to opencv_contrib_modules/modules. Configuration and generation (under VS2013) in the build folder (created the folder opencv/build)
- A solution appears in the build folder. First I built "ALL_BUILD" (Debug and Release versions) Then "Install" (also 2 versions)
- The install folder appears in the build directory. Than set environment variables:
OPENCV_BIN_DIR: => %your_opencv_dir% \  build \ install \ x64 \ vc12 \ bin
OPENCV_DIR: => %your_opencv_dir% \ build \ install \ x64 \ vc12
OPENCV_INCLUDE_DIR: => %your_opencv_dir% \ build \ install \ include
OPENCV_LIB_DIR: => %your_opencv_dir% \ build \ install \ x64 \ vc12 \ lib
Also, let's try the OPENCV_BIN_DIR variable in the PATH.
Restart the console and reinstall module (npm install opencv4nodejs)
and...
Everything works great!
Thanks for the advice and sorry for my bad english :) You can close it. Merry Christmas and Happy New Year!

**Comment by justadudewhohacks** [comment]
Awesome! Thanks for the explaining the solution to your problem.

Happy holidays!
