### ISSUE TITLE
Add support for matchTemplate

### ISSUE THREAD

**Issue by Bfindlay** [justadudewhohacks/opencv4nodejs#12]
I am wondering if there will be any support for the matchTemplate function anytime soon?
Thanks

**Comment by justadudewhohacks** [comment]
Hey,

I can add it. Are you missing any further functions? You can list them here and I will add them with this PR.

**Comment by Bfindlay** [comment]
As of now matchTemplate is the only one i am missing.
Thanks for the fast reply.

**Comment by justadudewhohacks** [comment]
Merged and published. Let me know if something is not wokring as intended.
