### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by sbilbault** [justadudewhohacks/opencv4nodejs#125]
When trying to install opencv4nodejs on windows with OpenCV3.4 installed, and the 2 variables correctly set,, I get the following error when compiling with node_gyp: 

C:\........\node_modules\opencv4nodejs\cc\macros.h(1): fatal error C1083: Cannot open include file: 'macro-inferno.h': No such file or directory (compiling source file ..\cc\cvTypes\imgprocConstants.cc) C:\...\node_modules\opencv4nodejs\build\opencv4nodejs.vcxproj]

I correctly installed macro-inferno via npm, and the macro-inferno.h file is present in the node_modules folder. 

I don't understand the issue. Would you have any clue of the cause ?

Thanks,
Sébastien

**Comment by justadudewhohacks** [comment]
Hmm,

when you npm install opencv4nodejs it should also install macro-inferno, such that you should end up with a folder in node_modules/macro-inferno/src where all the header files are located. Can you verify that this folder is present with the header files + an index.js in the macro-inferno root folder?

Maybe there is an issue with the path. In the index.js mentioned you will simply find the script `console.log(require('path').join(__dirname, 'src'));`. For debugging you could change this `throw new Error(require('path').join(__dirname, 'src'));`, which will throw an error with the absoulte path name, just to see whether the path is correct.

**Comment by sbilbault** [comment]
Thanks for your help, an accent in the name of the folder was blocking the installation. Now, the package is installed successfully !

However, when trying to use it, I get the following error when executing a js file containing only 
const cv = require('opencv4nodejs');

Would you have any idea where it comes from ? 

Thanks,
Sébastien

**Comment by justadudewhohacks** [comment]
Which error is it? Probably same as #106 ?

**Comment by sbilbault** [comment]
When I try to run the following line  `const cv = require('opencv4nodejs');` , i get the following error message : 
```
module.js:664
  return process.dlopen(module, path._makeLong(filename));
                 ^
Error: Le module spécifié est introuvable.
\\?\C:\Users\snbt\Documents\Prive\OuiSol\2 Dev\Roof\JS\node_modules\opencv4nodejs\build\Release\opencv4nodejs.node
    at Object.Module._extensions..node (module.js:664:18)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\snbt\Documents\Prive\OuiSol\2 Dev\Roof\JS\node_modules\opencv4nodejs\lib\opencv4nodejs.js:7:8)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)

```
I looked at #109, #50 and other messages, but the path of the OPENCV_... looks ok. When I do ```
console.log(process.env.OPENCV_DIR);
console.log(process.env.OPENCV_INCLUDE_DIR);
console.log(process.env.OPENCV_LIB_DIR);
console.log(process.env.OPENCV_BIN_DIR);
```
I get the following which looks ok according to the other posts
C:\Users\snbt\opencv
C:\Users\snbt\opencv\build\include
C:\Users\snbt\opencv\build\x64\vc15\lib
C:\Users\snbt\opencv\build\x64\vc15\bin

Would you have any idea to solve this ?

**Comment by justadudewhohacks** [comment]
Did you also add OPENCV_BIN_DIR to your system path?

**Comment by sbilbault** [comment]
Yes, all 4 variables are set !
OPENCV_BIN_DIR is set to C:\....\opencv\build\x64\vc15\bin

**Comment by justadudewhohacks** [comment]
The path to binaries has to be in your system path. If you `echo path` from a terminal or `console.log(process.env.path);` then you should find 'C:....\opencv\build\x64\vc15\bin' in there. If not go to system setting, find variable path and append `;%OPENCV_BIN_DIR%;` to it, save, reopen your console and try to run it again.

**Comment by sbilbault** [comment]
When I `echo %OPENCV_BIN_DIR%`, I get `C:\...\opencv\build\x64\vc15\bin` 

The issue seems different from other ones where the path to .dlls was not set, and I cannot figure out the issue

**Comment by justadudewhohacks** [comment]
Can you `echo %path%` please and make sure "C:\...\opencv\build\x64\vc15\bin" is in there.

**Comment by sbilbault** [comment]
You're fully right, I didn't understood I needed to also add C:\...\opencv\build\x64\vc14\bin to the path ! I added it, and now it works.

Thank you so much !

**Comment by justadudewhohacks** [comment]
Great! I think I have to be more clear about that in the windows install sections, since this gets asked alot.
