### ISSUE TITLE
Canny detector

### ISSUE THREAD

**Issue by sbilbault** [justadudewhohacks/opencv4nodejs#128]
I'm unable to have the canny detector working with my image, I suspect to have a Mat type issue, but cannot figure out why this example ends with a black picture ....

```
    var MatInput = cv.imread(ImagePath);

    var MatGray = MatInput.bgrToGray();
    var MatGray_16SC1 = MatGray.convertTo(cv.CV_16SC1);

    cv.canny(MatGray_16SC1, MatGray_16SC1, 0, 1, false);
    console.log('TEST CANNY DETECTOR', MatGray_16SC1);
    var MatOutput = MatGray_16SC1.convertTo(cv.CV_16UC1);
    cv.imshow('Test window', MatOutput);
```
Would you have any idea how to solve this issue ?

**Comment by justadudewhohacks** [comment]
Hey there are two types of Canny:

1. takes the gradient mats dx and dy and is called from the cv object
signature: `Mat : cv.canny ( Mat dx , Mat dy , number threshold1 , number threshold2 , boolean L2gradient = false )`

2. takes a gray image as input and is directly called on the gray mat
signature: `Mat : mat.canny ( number threshold1 , number threshold2 , int apertureSize = 3 , boolean L2gradient = false )`

So in your case it would probably be:
```
MatGray_16SC1 = MatGray_16SC1.canny(0, 1, false);
```

**Comment by sbilbault** [comment]
Thanks, I missed the two types of Canny ! It works perfectly !
