### ISSUE TITLE
Add new modules : watershed and morphologyEx

### ISSUE THREAD

**Issue by sbilbault** [justadudewhohacks/opencv4nodejs#129]
Could you please add the **watershed** module and the **morphologyEx()** module to the opencv4nodejs package ? I would need it, and have been unable to find it in the currrent package;

Thanks in advance !

**Comment by justadudewhohacks** [comment]
Hey,

morphologyEx is available in the Mat object, 
see: https://opencv4nodejs.herokuapp.com/docs/core#Mat-morphologyEx

watershed will be added asap.

**Comment by sbilbault** [comment]
Hey !
Thanks for your prompt answer, the package is really awesome !
Could you please also add cornerHarris and cornerSubPix to the next release ?
Thank you so much

**Comment by justadudewhohacks** [comment]
Sure, I will make a new release tomorrow. Just let me know if you are missing some other bindings until then.

**Comment by sbilbault** [comment]
Hey,
If it's not too late, I would also need the resize module ;-)
resize(InputArray src, OutputArray dst, Size dsize, double fx=0, double fy=0, int interpolation=INTER_LINEAR )
Thanks !

**Comment by justadudewhohacks** [comment]
Your requested functions are now available in the newest release.

**Comment by sbilbault** [comment]
Thanks @justadudewhohacks  !
