### ISSUE TITLE
Unknown layer type DecodeJpeg

### ISSUE THREAD

**Issue by mappum** [justadudewhohacks/opencv4nodejs#130]
Hey @justadudewhohacks, this project is awesome!

Right now I'm trying to read in a Tensorflow network, which is a retrained inception-v3. When I call `readNetFromTensorflow` I get this error:

```
DecodeJpeg:DecodeJpeg(DecodeJpeg/contents)
try_recover_truncated:[ ]
fancy_upscaling:[ ]
acceptable_fraction:[ ]
ratio:[ ]
channels:[ ]
dct_method:[ ]
OpenCV Error: Unspecified error (Unknown layer type DecodeJpeg in op DecodeJpeg) in populateNet, file /tmp/opencv-20171226-25540-qyr0tr/opencv-3.4.0/modules/dnn/src/tensorflow/tf_importer.cpp, line 1487
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /tmp/opencv-20171226-25540-qyr0tr/opencv-3.4.0/modules/dnn/src/tensorflow/tf_importer.cpp:1487: error: (-2) Unknown layer type DecodeJpeg in op DecodeJpeg in function populateNet
```

I'm on macOS, with OpenCV 3.4 installed via `brew`.

**Comment by justadudewhohacks** [comment]
Hey,

unfortunately I also faced trouble importing some tensorflow models. Apparently not all layer types in tensorflow are compatible with OpenCV, thus one has to remove those. Seems that there is a script for doing so, but I have never done it.

Maybe this helps you: https://github.com/opencv/opencv_contrib/issues/1029

**Comment by justadudewhohacks** [comment]
Closing this issue, as it is an OpenCV issue.
