### ISSUE TITLE
require shoots an error

### ISSUE THREAD

**Issue by trix0** [justadudewhohacks/opencv4nodejs#132]
const cv = require('opencv4nodejs');

node comp.js
module.js:664
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\xampp\htdocs\Web_Dev\pv\Pl\node_modules\opencv4nodejs\build\Release\opencv4nodejs.node
    at Object.Module._extensions..node (module.js:664:18)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\xampp\htdocs\Web_Dev\pv\Pl\node_modules\opencv4nodejs\lib\opencv4nodejs.js:7:8)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)

Could you please give me any advice ? :)

and yeah I would like to use your library to find if singin button exists on image with a help of another image  which function should i use for that ?

**Comment by justadudewhohacks** [comment]
You are missing the opencv binaries in your system path, see #125 

You mean you have an image of the signin button and want to figure out whether it exists in a given webpage? Sound like template matching to me, e.g. matchTemplates function in opencv.

**Comment by trix0** [comment]
Thx :) for fast answer gonna try to fix it

**Comment by justadudewhohacks** [comment]
Yeah, template matching means you have an image patch (template), which you are sliding over an input image, to locate the template or a similar image in that input image.

**Comment by trix0** [comment]
Okey ,I am not sure whats wrong. I have those variables 
https://ctrlv.cz/tO20

M i missing any of them ? I am already confused in it :D

**Comment by justadudewhohacks** [comment]
Looks good, OPENCV_BIN_DIR is the one where all the .dlls are located. Did you close and reopen your terminal from which you executed your nodejs script? Everytime you make changes to your envs, you should restart the console.

**Comment by trix0** [comment]
Okey I found it. 
https://ctrlv.cz/shots/2018/01/04/WINi.png
I had to put all of those in there on left env variables on right path variables. now It works :)
Could you please edit little bit this env variables explanation. I got kinda lost in it :) and Yeah good job and thx for responses.

**Comment by justadudewhohacks** [comment]
Well actually only the OPENCV_BIN_DIR should be in your path, the other envs do not matter at runtime, they are read when the package is compiled.

**Comment by trix0** [comment]
haha :D I added everything to make it work I had no idea Ill give you a star :)
