### ISSUE TITLE
cv.matchTemplate is not a function

### ISSUE THREAD

**Issue by trix0** [justadudewhohacks/opencv4nodejs#134]
// I had to access it through the image 

Hey, dude

I have a problem access one of functions.

cv.matchTemplate();

shoots TypeError: cv.matchTemplate is not a function
I am not sure if I am doing something wrong again :D , but when i try for example

.drawMatches(); it complains about parameters so that function is recognized. Any idea guys how to make this matchTemplate works ? :D

**Comment by yummyLcj** [comment]
Hi,have you solved this problem?

**Comment by yummyLcj** [comment]
Oh!I know. I should call Mat. matchTemplate!!

**Comment by ossuskeeper25** [comment]
Hey dude , l could not flnd lt, example ?
