### ISSUE TITLE
Issue with inRange when used with single channel gray image

### ISSUE THREAD

**Issue by sbilbault** [justadudewhohacks/opencv4nodejs#136]
Hey,

I'm trying to use inRange with a single channel gray image, which seems to be fine according to OpenCV documentation https://docs.opencv.org/2.4/modules/core/doc/operations_on_arrays.html?highlight=inrange

However, when I look in the opencv4nodejs documentation (_inRange ( Vec3 lower , Vec3 upper )_), the inRange module require Vec3, which prevent from using it with single channel image. When I set a scalar as argument of the inRange, an errror pops up, requiring Vec3 arguments.

Could you please adjust the opencv4nodejs in order to allow scalar to be passed as argument of the inRange module ? Or do you see any other way to apply a filter to a gray image, in order to extract pixels between lower and upper values ?

Thanks !

**Comment by justadudewhohacks** [comment]
Ah yeah you are right, inRange currently is only accepting Vec3. I will add support for Scalars.

But for now you should be able to simply do this with thresholding, somehow like this:
`gray.threshold(upper, 255, cv.THRESH_BINARY).bitwiseNot(gray.threshold(lower, 255, cv.THRESH_BINARY))`

**Comment by sbilbault** [comment]
Ok, thanks !

Unfortunately, I'm using a 32F mat for this application, so I believe this method cannot works, isn't ?

**Comment by justadudewhohacks** [comment]
threshold should work on CV_8U and CV_32F

**Comment by justadudewhohacks** [comment]
inrange should also accept scalars now.

**Comment by sbilbault** [comment]
Thanks ;-)
