### ISSUE TITLE
Node can't find module

### ISSUE THREAD

**Issue by brianscroggins24** [justadudewhohacks/opencv4nodejs#137]
I've globally installed the package but node still can't seem to find it. Every other globally installed package works. Not sure how to solve this issue.

**Comment by justadudewhohacks** [comment]
What do you mean by cannot find the package? Can you post an error log please.

**Comment by yangxiaolin** [comment]
same error
<pre>
/Users/*****/node_modules/_opencv4nodejs@2.32.0@opencv4nodejs/lib/utils.js:105
        throw new Error(`lib for module '${m}' not found in OPENCV_LIB_DIR ('${libDir}')`);
        ^

Error: lib for module 'core' not found in OPENCV_LIB_DIR ('/usr/local/lib')
    at modules.forEach.m (/Users/*****/node_modules/node_modules/_opencv4nodejs@2.32.0@opencv4nodejs/lib/utils.js:105:15)
    at Array.forEach (<anonymous>)
    at fs.readdir (/Users/*****/node_modules/node_modules/_opencv4nodejs@2.32.0@opencv4nodejs/lib/utils.js:101:13)
    at FSReqWrap.oncomplete (fs.js:135:15)
gyp: Call to 'node ./lib/libs.js' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/cnpm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/cnpm/node_modules/npminstall/node-gyp-bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/*****/node_modules/node_modules/_opencv4nodejs@2.32.0@opencv4nodejs
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
✖ Install fail! Error: post install error, please remove node_modules before retry!
Run "sh -c node-gyp rebuild" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "sh -c node-gyp rebuild" error, exit code 1
    at ChildProcess.proc.on.code (/usr/local/lib/node_modules/cnpm/node_modules/runscript/index.js:74:21)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
</pre>

**Comment by justadudewhohacks** [comment]
Closing this issue. If you guys made sure any OpenCV 3 version is set up on your system and the error still remains feel free to reopen this.
