### ISSUE TITLE
Support for Scharr / Sobel  

### ISSUE THREAD

**Issue by smoscar** [justadudewhohacks/opencv4nodejs#14]
Wondering if there are plans to support the Scharr / Sobel operators?
Thanks!

**Comment by justadudewhohacks** [comment]
Definitely! :)

**Comment by justadudewhohacks** [comment]
Merged and published. Let me know if something is not working as intended.

**Comment by smoscar** [comment]
Awesome! 
It's working great, thanks for the quick response!

**Comment by justadudewhohacks** [comment]
Great! You're welcome. Supporting this project, by leaving a star for the repo would of course be highly appreciated. :)

**Comment by smoscar** [comment]
Sure thing
