### ISSUE TITLE
LBPHFaceRecognizer,EigenFaceRecognizer,FisherFaceRecognizer is not a constructor

### ISSUE THREAD

**Issue by egcaragay** [justadudewhohacks/opencv4nodejs#141]
Cannot instantiate LBPHFaceRecognizer,EigenFaceRecognizer,FisherFaceRecognizer.

**Comment by justadudewhohacks** [comment]
You probably have compiled the package without the opencv face module. Try `console.log(cv.xmodules.face)` if it's undefined it is not compiled or try to run the face recognition examples.

Have you set up opencv with contrib modules?

**Comment by egcaragay** [comment]
Hi @justadudewhohacks 
You're right it's undefined.
Anyway
I'm using windows 7, I downloaded the opencv 3.4 executable file.
Extracted it and set the environment variables.

**Comment by egcaragay** [comment]
Do i need extra step on this? Thanks

**Comment by justadudewhohacks** [comment]
Yeah contrib is an extra module collection for opencv. See how to set it up here: https://github.com/opencv/opencv_contrib#how-to-build-opencv-with-extra-modules

**Comment by egcaragay** [comment]
@justadudewhohacks  Thanks

**Comment by amyDoxy** [comment]
Amazing package. 
I am getting the same error except that I am building  from justadudewhohacks/opencv-nodejs:node9-opencv3.4.1-contrib image. This image doesn't have  opencv-contrib?

**Comment by justadudewhohacks** [comment]
The image should have the contrib packages, but you are right. I didn't know face and tracking have a dependency on the opencv_plot module, which I disabled in the build script of the docker image.

I am currently rebuilding the image and will push the updated one.

**Comment by justadudewhohacks** [comment]
Pushed the updated image. You should now be able to use the face module after pulling the updated image.

**Comment by debz05** [comment]
Error: exiting: opencv4nodejs compiled without face module
    at Object.<anonymous> (C:\opencv4nodejs-master\examples\faceRecognition1.js:6:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

I am getting this error even after building the opencv-contrib module. Kindly help me to fix this issue.

**Comment by MuriloRS** [comment]
> Yeah contrib is an extra module collection for opencv. See how to set it up here: https://github.com/opencv/opencv_contrib#how-to-build-opencv-with-extra-modules

I ran the commands to add the extra opencv modules, however when it finishes executing it shows that the module Eigen = false. When giving console.log (cv.xmodules); show me undefined and cv.EigenFaceRecognizer that EigenFaceRecognizer is not a builder. 

There's somenthing wrong that I did?
