### ISSUE TITLE
imread question 

### ISSUE THREAD

**Issue by trix0** [justadudewhohacks/opencv4nodejs#142]
Its not an issue its a question 
Hey dude :) I just have a question I am getting images in form of a base 64 encoded string how can i convert this string into Mat ? I would like to skip using fs.writefile and then reading it with imread.

**Comment by justadudewhohacks** [comment]
Hey,

getting the image from a base64 encoded string is as simple as:
```
const buf = Buffer.from(base64Data, 'base64') 
const img = cv.imdecode(buffer)
```

I have also done this in the express example: https://github.com/justadudewhohacks/opencv-express/blob/master/src/services/imgcodecs.js

**Comment by gjovanov** [comment]
Check #70

**Comment by trix0** [comment]
Oh i see :) thx guys I ve been using iamread instead of iamdecode ... you are such a good guys :)
