### ISSUE TITLE
Setting drawContours parameter contourIdx =-1 (Draw all contours)

### ISSUE THREAD

**Issue by Leon-Sam** [justadudewhohacks/opencv4nodejs#147]
Hello,

I stumbled upon this package a few days ago. It's great, and thank you for taking the time for developing this. 

When trying to use the drawContours function, I try to set  the contourldx parameter to a negative value to make OpenCV draw all the contours within passed in contour object. 

However when set to a negative value as indicated by the [OpenCV docs](https://docs.opencv.org/3.4.0/d6/d6e/group__imgproc__draw.html#ga746c0625f1781f1ffc9056259103edbc), in order to draw all contours. An error is thrown. 

"Error: Mat::DrawContours - expected arg 2 to be of type: UINT"

Which makes sense, since in the [opencv4nodejs docs](https://opencv4nodejs.herokuapp.com/docs/core#Mat-drawContours). It says that the contourldx is a type of uint (unsigned integer). So I can only pass in a positive value. 

When I pass in a positive value, the contourIdx works as intended, highlighting the specified contour. 

**Here is my question, am I overlooking simple way to draw all contours (other than doing something silly and looping over the contours object?**  

Or does the wrapper accidentally "wipe out" the ability draw all contours. If this is the case, is the "fix" as simple as changing the parameter input from a type of "uint" to a type of "int" in the opencv4nodejs bindings?

If anything I said is unclear, feel free to ask. I have no issue on expanding. 

Other info: 
Docker environment with node-carbon base image, Built opencv3.4.0 from source
opencv4nodejs npm package

**Comment by justadudewhohacks** [comment]
Hi,

You are right, it's because the binding expects a uint instead of an int. I will change it and supply a fix, just wanted to add something to the package anyways.

Thanks for reporting.

**Comment by justadudewhohacks** [comment]
Ok should work now as expected.

**Comment by Leon-Sam** [comment]
Thank you for getting back so quickly. If you want me to take some load off your chest, I can try to send in a PR by the end of the day tomorrow. 

Disclaimer: This would be my first PR in an open source project. So I may make some errors. 

Let me know how you want me to proceed.

**Comment by justadudewhohacks** [comment]
Maybe you find some more things to fix :D. PRs are always highly appreciated and don't worry about making mistakes, you can not really make any.

**Comment by Leon-Sam** [comment]
That sounds good.  If their is anything I can fix, I'll send a PR your way. I tend to value good docs a lot, if you see things from me, it will most likely be of that flavor.  I close this now, to clean up the issues section.
