### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by sbilbault** [justadudewhohacks/opencv4nodejs#149]
Hey justadududewhohacks !

Still need features to be added please : polylines, fillPoly, and fillConvexPoly

Thanks for this awesome package !

**Comment by justadudewhohacks** [comment]
Your requested drawing methods are now avaiable:
https://opencv4nodejs.herokuapp.com/docs/core#Mat-drawPolylines
https://opencv4nodejs.herokuapp.com/docs/core#Mat-drawFillPoly
https://opencv4nodejs.herokuapp.com/docs/core#Mat-drawFillConvexPoly

**Comment by sbilbault** [comment]
Thanks a lot !

**Comment by sbilbault** [comment]
Hey,

Have you modified any test on modules when adding the modules ? DrawLine was previously working for instance with the following argment, and is not working anymore !

`Mat.drawLine(new cv.Point(10,10),new cv.Point(32,34),new cv.Vec(255,255,255),{thickness: 1})`

Thanks

**Comment by justadudewhohacks** [comment]
Damn you are right, I added a default value for the color, which had none before.

If you want to use named optional args it would now be:
`Mat.drawLine(new cv.Point(10,10),new cv.Point(32,34),{thickness: 1, color: new cv.Vec(255,255,255)})`

Or simply:
`Mat.drawLine(new cv.Point(10,10),new cv.Point(32,34),new cv.Vec(255,255,255))`
as thickness 1 is the default value anyways.

This probably broke all drawing stuff in the examples too. I might have to check that later.

**Comment by sbilbault** [comment]
OK, it solves the issue, thanks !

**Comment by Shanmax1996** [comment]
Not working

mat.drawFillPoly function

**Comment by Shanmax1996** [comment]
I want to draw fillpoly and i try with syntax and get same issue..
Please help me

I want to get point 1 = 200,500
point 2 = 1100,500
point 3 = 550,250
fillpoly like that..

my syntax
Mat.drawFillPoly(new cv.Point2([200,500],[1100,500],[550, 250]), new cv.Vec(255,255,255));

I got err

mask.drawFillPoly(new cv.Point2([200,500],[1100,500],[550, 250]), new cv.Vec(255,255,255));
^
Mat::DrawFillPoly - Error: expected argument 0 to be of type array of arrays of Point2
(Use node --trace-uncaught ... to show where the exception was thrown
