### ISSUE TITLE
Result from library not consistent

### ISSUE THREAD

**Issue by hbinduni** [justadudewhohacks/opencv4nodejs#158]
Hi, i try with this code:

[test-img.png](https://imgur.com/k1wzsYW)

```
const cv = require('opencv4nodejs');

const file = './test-img.png';

const test = async () => {
  try {
    const img = await cv.imreadAsync(file);
    const grayImg = await img.bgrToGrayAsync();
    const mat = await grayImg.thresholdAsync(254, 255, cv.THRESH_BINARY_INV);

    const pt2 = new cv.Point(2, 2);
    const kernel = new cv.Mat(5, 5, cv.CV_8U);
    const open = await mat.morphologyExAsync(kernel, cv.MORPH_OPEN, pt2);

    cv.imshowWait('a window name', open);
    cv.destroyAllWindows();
  } catch (err) {
    console.error(err);
  }
}

test();

```

but the result seems not consistent. can you tell me what's wrong?
sometimes it give me result like below:

[Result 1](https://imgur.com/mhJABBS)

sometimes like this:

[Result 2](https://imgur.com/5NuZ3q1)

below my os system:

ProductName:	Mac OS X
ProductVersion:	10.13.2
BuildVersion:	17C205

node v9.4.0
opencv 3.4.0_1

**Comment by justadudewhohacks** [comment]
Strange, I will check that.

Did you run this code with python before and it did not produce inconsistent results? Just trying to figure out whether it's related to OpenCV or opencv4nodejs.

**Comment by hbinduni** [comment]
I run this code in python, and their result consistent when i run multiple times:

```
import cv2
import numpy as np

file = './images/test-img.png'

img = cv2.imread(file, cv2.IMREAD_GRAYSCALE)

(ret, th1) = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY_INV)

k1 = np.ones((1, 1), np.uint8)
k2 = np.ones((5, 5), np.uint8)

opening = cv2.morphologyEx(th1, cv2.MORPH_OPEN, k2)

dilate = cv2.morphologyEx(opening, cv2.MORPH_DILATE, k1)

cv2.imshow('dilate image', dilate)
cv2.waitKey(0)

```

**Comment by justadudewhohacks** [comment]
Ok then it's an issue with the bindings.

By the way just noticed: `const kernel = new cv.Mat(5, 5, cv.CV_8U);` This will initialize a Mat with more or less random data, more precisely, whatever data is held by the memory location atm, as you just allocate it but do not fill it with any data.

Do you want it to be a Mat of ones? Then try: `const kernel = new cv.Mat(5, 5, cv.CV_8U, 1);`.

**Comment by hbinduni** [comment]
Hi, after change the kernel with your suggestion, i got the constant result. Thank you for your help.

Regards
