### ISSUE TITLE
cv.matchKnnFlannBased is not a constructor error

### ISSUE THREAD

**Issue by flefloch** [justadudewhohacks/opencv4nodejs#160]
Hello,

first thank you for porting openCV to Node :)

I'm trying to do this tuto : https://docs.opencv.org/trunk/dc/dc3/tutorial_py_matcher.html
When trying to "translate" the original code
```
flann = cv.FlannBasedMatcher(index_params,search_params)
matches = flann.knnMatch(des1,des2,k=2)
```
I guessed that I had to use cv.matchKnnFlannBased but I receive a not constructor error.
`var matches = new cv.matchKnnFlannBased(image1Computed, image2Computed, 2);`
Did I understood something wrong?

Thank you.

**Comment by justadudewhohacks** [comment]
cv.matchKnnFlannBased is not a class, its a plain function. Call it without the new keyword.

**Comment by flefloch** [comment]
Hello,

thanks for answering so quickly!
But I'm still a bit confused, since I was able to call
`var matches = new cv.matchBruteForce(image1Computed, image2Computed);`
which should be a function too and not a class, that's why I thought there was possibly an issue in the documentation.

Anyway, I'm still stuck with this methode since I'm not able to call it as a static method 
`var matches = cv.matchKnnFlannBased(image1Computed, image2Computed, 2);`
nor by creating an instance of SimpleBlobDetector and collaing the method on it 
```
  var matcher = new cv.SimpleBlobDetector(matcherParams);
  var matches = matcher.matchKnnFlannBased(image1Computed, image2Computed, 2);
```
I'm probably understanding something wrong but I can't figure out what.
May you help?

Thank you.

**Comment by justadudewhohacks** [comment]
Okay that's strange. knn matching has recently been added in #154 . I will try it out later, maybe there is some issue.

What happens when you call it like this:
`var matches = cv.matchKnnFlannBased(image1Computed, image2Computed, 2);`

This should be the correct way to call it.

**Comment by flefloch** [comment]
Same error : 
`TypeError : cv.matchKnnFlannBased is not a function`

**Comment by justadudewhohacks** [comment]
Are you using opencv4nodejs v 2.37.0+ ?

**Comment by flefloch** [comment]
Yep I'm using version 2.37.1
Actually I'm just using the full docker package you provided in your example.

**Comment by justadudewhohacks** [comment]
Ohh ok, the problem is the express-example uses a docker image with opencv4nodejs v2.1.0.

I will have to update the image.

**Comment by flefloch** [comment]
Really?
But when I'm doing npm view opencv4nodejs version it returns 2.37.1

**Comment by flefloch** [comment]
I confirmed I updated to 2.37.1 and I still have the same error.
If you have any idea I'll be happy to hear.
Thank you for your help.

**Comment by justadudewhohacks** [comment]
You mean the opencv4nodejs version, which is set up in your docker container or on your local machine? Note, that the docker image provided in the express example comes with v2.1.0 globally installed, so unless you added the instructions to update opencv4nodejs in your dockerfile, the reason why it doesnt find cv.matchKnnFlannBased resides in the version.

I will update the docker image in a second.

**Comment by justadudewhohacks** [comment]
Facing issues with docker, so currently not able to update the image. In the meantime you can use this to build the docker image:

```
FROM justadudewhohacks/opencv3.3-contrib

RUN apt-get update \
&&apt-get install -y build-essential curl \
&&curl -sL https://deb.nodesource.com/setup_6.x | bash \
&&apt-get install -y nodejs python \
&&npm install -g nodemon opencv4nodejs \
&&rm -rf /var/lib/apt/lists/* \
&&apt-get purge -y build-essential \
&&apt-get purge -y curl \
&&apt-get autoremove -y --purge
```

**Comment by flefloch** [comment]
Hello, 

oh you're right, stupid answer from my side.
I updated the Dockerfile but when trying to run npm install on version 2.37.1  I receive an error with node-gyp rebuild.

I remember facing the same issue when trying to install opencv4node on my computer, that's why I ended by using the docker image.

**Comment by justadudewhohacks** [comment]
Could you post the error log for both docker and your local machine.

**Comment by flefloch** [comment]
Here is the error returned : 
`Alexandre:opencv4node fabricelefloch$ docker build -f Dockerfile .
Sending build context to Docker daemon  5.325MB
Step 1/7 : FROM justadudewhohacks/opencv3.3-contrib
 ---> b7ba8a0a0e83
Step 2/7 : RUN apt-get update &&apt-get install -y build-essential curl &&curl -sL https://deb.nodesource.com/setup_6.x | bash &&apt-get install -y nodejs python &&npm install -g nodemon opencv4nodejs &&rm -rf /var/lib/apt/lists/* &&apt-get purge -y build-essential &&apt-get purge -y curl &&apt-get autoremove -y --purge
 ---> Using cache
 ---> 6138cb4b675a
Step 3/7 : WORKDIR /app
 ---> Using cache
 ---> 5c04a01f7a40
Step 4/7 : COPY package.json /app/package.json
 ---> Using cache
 ---> 444a3142e52f
Step 5/7 : RUN npm install
 ---> Running in 87624c35eafe

> opencv4nodejs@2.37.1 install /app/node_modules/opencv4nodejs
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:14:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:69:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:81:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Linux 4.9.60-linuxkit-aufs
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/opencv4nodejs
gyp ERR! node -v v6.12.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
opencv-express@0.0.4 /app
+-- body-parser@1.18.2 
| +-- bytes@3.0.0 
| +-- content-type@1.0.4 
| +-- debug@2.6.9 
| | `-- ms@2.0.0 
| +-- depd@1.1.2 
| +-- http-errors@1.6.2 
| | +-- depd@1.1.1 
| | +-- inherits@2.0.3 
| | +-- setprototypeof@1.0.3 
| | `-- statuses@1.4.0 
| +-- iconv-lite@0.4.19 
| +-- on-finished@2.3.0 
| | `-- ee-first@1.1.1 
| +-- qs@6.5.1 
| +-- raw-body@2.3.2 
| | `-- unpipe@1.0.0 
| `-- type-is@1.6.15 
|   +-- media-typer@0.3.0 
|   `-- mime-types@2.1.17 
|     `-- mime-db@1.30.0 
`-- express@4.16.2 
  +-- accepts@1.3.4 
  | `-- negotiator@0.6.1 
  +-- array-flatten@1.1.1 
  +-- content-disposition@0.5.2 
  +-- cookie@0.3.1 
  +-- cookie-signature@1.0.6 
  +-- encodeurl@1.0.2 
  +-- escape-html@1.0.3 
  +-- etag@1.8.1 
  +-- finalhandler@1.1.0 
  | `-- statuses@1.3.1 
  +-- fresh@0.5.2 
  +-- merge-descriptors@1.0.1 
  +-- methods@1.1.2 
  +-- parseurl@1.3.2 
  +-- path-to-regexp@0.1.7 
  +-- proxy-addr@2.0.2 
  | +-- forwarded@0.1.2 
  | `-- ipaddr.js@1.5.2 
  +-- range-parser@1.2.0 
  +-- safe-buffer@5.1.1 
  +-- send@0.16.1 
  | +-- destroy@1.0.4 
  | +-- mime@1.4.1 
  | `-- statuses@1.3.1 
  +-- serve-static@1.13.1 
  +-- setprototypeof@1.1.0 
  +-- statuses@1.3.1 
  +-- utils-merge@1.0.1 
  `-- vary@1.1.2 

npm ERR! Linux 4.9.60-linuxkit-aufs
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.12.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! opencv4nodejs@2.37.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv4nodejs@2.37.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the opencv4nodejs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs opencv4nodejs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls opencv4nodejs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log
The command '/bin/sh -c npm install' returned a non-zero code: 1`

It first seems that the build-essential lib isn't found to run MAKE, but apt-get install -y build-essential is at the beginning of the script.

**Comment by justadudewhohacks** [comment]
Oh yeah the thing is that I remove all build tools at the end to keep the image as lean as possible. 

So in case you need build tools for any other npm package in your package.json you should keep it. Note, that you shouldn't have to add opencv4nodejs in your package.json as it is installed globally here. Having it in your package.json without having the required build tools set up will cause this error.

Alternatively you can just remove these instructions from your docker image, to keep the build tools:
```
&&rm -rf /var/lib/apt/lists/* \
&&apt-get purge -y build-essential \
&&apt-get purge -y curl \
&&apt-get autoremove -y --purge
```

**Comment by flefloch** [comment]
Hello,

OK it makes sense.
I just removed the opencv4nodejs from the package.json file and rebuild the container.
It seems now that I have the correct version installed 
 `root@89cc79da4147:/app# npm view opencv4nodejs version
2.37.1`
But unfortunately I'm still stuck with the same TypeError: cv.matchKnnFlannBased is not a function error.

**Comment by justadudewhohacks** [comment]
Okay that's indeed strange.

I updated the docker image now and tested it, cv.matchKnnFlannBased should exist. Maybe your docker app is using a cached build, have you tried to do a docker-compose build?

**Comment by flefloch** [comment]
Yes I think there is something messy in my computer...
If you updated your docker image I think I'll try to grab it again and restart from there.
i'll teel you what happens.

Thank you so much for your help.

**Comment by flefloch** [comment]
I confirm that rebuilding from you last image works just fine.
Thank you so much for your help!
