### ISSUE TITLE
Creating type file for DefinitelyTyped

### ISSUE THREAD

**Issue by Tzelon** [justadudewhohacks/opencv4nodejs#163]
Hey,
Thank you for your excellent work.
Did you think about creating this kind of file? It is very helpful.

**Comment by justadudewhohacks** [comment]
Hi,

I am not familar with TypeScript, so I do not have any plans to add it.

**Comment by justadudewhohacks** [comment]
Sorry closed by mistake. If anyone is familar with TypeScript and has knowledge about creating such an DefinitelyTyped file, feel free to submit a PR :)

**Comment by Tzelon** [comment]
I will try to start something in the near future

**Comment by justadudewhohacks** [comment]
Just added TypeScript definitions and TypeScript examples for the package, so closing here :)
