### ISSUE TITLE
Support basic Sign Language :)

### ISSUE THREAD

**Issue by binarykitchen** [justadudewhohacks/opencv4nodejs#165]
That's an awesome library with huge potential! 

And since I am a Deaf programmer here, I would love to see it support some basic signs. Like the finger alphabet. The one which is internationally recognised: http://fingerspell.net/#/how

Imagine capturing a sequence of letters, forming a command ... possibilities are unlimited :)

**Comment by justadudewhohacks** [comment]
Hi,

While this is a nice idea, it's probably not going to fit in this package, as your idea is more of an application, which has to be built on top of OpenCV. The task of this package is to simply provide a Nodejs API to OpenCV, such that it allows to build such computer vision applications such as the one suggested by you. Furthermore, to build such an application one would probably have to come up with a complex solution.

**Comment by binarykitchen** [comment]
@justadudewhohacks yeah, you are right - will consider another package on top of this one.

but can you tell me first if your package is suitable for this use case? to recognise over 30 different handshapes and map these to letters?

or would you recommend another library to do this? could be that OpenCV is overkill.

**Comment by justadudewhohacks** [comment]
Hmm good question, first of all I would research whether someone implemented something similar in OpenCV. I would think that it's possible to implement with OpenCV, although it would be hard to distinguish between some gestures that look quite similar.

Maybe  also someone came up with a fancy deep learning library that does gesture recognition. I would also do some research in this area first.

**Comment by binarykitchen** [comment]
Yeah, something like that. Although this will be quite lots of work and is new land to me.

Would be nice to have a new npm package that takes in images with signed letters as an input pipe and outputs whole sentence on end event. Simple as that. All the complexity in the black box. And I bet many will use that, I see a huge potential ...
