### ISSUE TITLE
Draw function arguments order

### ISSUE THREAD

**Issue by quentin-coursodon** [justadudewhohacks/opencv4nodejs#167]
Hi,
It looks like there is a mix up between doc and implementation for draw functions.

In the [doc](https://opencv4nodejs.herokuapp.com/docs/core#Mat-drawArrowedLine) LineType comes first and [here](https://github.com/justadudewhohacks/opencv4nodejs/blob/master/cc/core/MatImgproc.cc#L1275) thickness comes first.

**Comment by justadudewhohacks** [comment]
You are right, thanks for reporting. I adjusted the docs.
