### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by crashspringfield** [justadudewhohacks/opencv4nodejs#169]
I got the following error trying 

    In file included from ../cc/opencv4nodejs.cc:14:0:
    ../cc/modules/tracking/tracking.h:2:32: fatal error: opencv2/tracking.hpp: No such file or directory
     #include <opencv2/tracking.hpp>
                                ^
    compilation terminated.

    make: *** [Release/obj.target/opencv4nodejs/cc/opencv4nodejs.o] Error 1
    make: Leaving directory `/home/user/js/node/tutorials/opencv4nodejs/build'`

I'm running Linux Mint 17. I've installed OpenCv following [these directions](https://docs.opencv.org/2.4/doc/tutorials/introduction/linux_install/linux_install.html) and set an environment variable to `OPENCV4NODEJS_DISABLE_AUTOBUILD=1`. I've also tried the same steps without setting the environment variable.

**Comment by justadudewhohacks** [comment]
Which version are you trying to install? This was a bug I fixed in opencv-build v0.0.2, so it shouldn't occur with opencv4nodejs v.3.0.2.

**Comment by crashspringfield** [comment]
I'm using v.3.0.2. I started a new project and tried again, but got a different error this time. Here's the stack trace:

    131 silly install opencv-build@0.0.2
    132 info lifecycle opencv-build@0.0.2~install: opencv-build@0.0.2
    133 verbose lifecycle opencv-build@0.0.2~install: unsafe-perm in lifecycle true
    134 verbose lifecycle opencv-build@0.0.2~install: PATH: /home/user/.nvm/versions/node/v8.0.0/lib/node_modules/npm/bin/node-gyp-bin:/home/user/js/node/tutorials/opencv/node_modules/opencv-build/node_modules/.bin:/home/user/js/node/tutorials/opencv/node_modules/.bin:/home/user/.nvm/versions/node/v8.0.0/bin:/home/user/npm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/user/.node/bin:/opt/lampp/bin
    135 verbose lifecycle opencv-build@0.0.2~install: CWD: /home/user/js/node/tutorials/opencv/node_modules/opencv-build
    136 silly lifecycle opencv-build@0.0.2~install: Args: [ '-c', 'node ./install.js' ]
    137 silly lifecycle opencv-build@0.0.2~install: Returned: code: 1  signal: null
    138 info lifecycle opencv-build@0.0.2~install: Failed to exec install script
    139 verbose unlock done using /home/user/.npm/_locks/staging-90c3cd53b94d4daa.lock for /home/user/js/node/tutorials/opencv/node_modules/.staging
    140 warn opencv@1.0.0 No description
    141 warn opencv@1.0.0 No repository field.
    142 verbose stack Error: opencv-build@0.0.2 install: `node ./install.js`
    142 verbose stack Exit status 1

**Comment by justadudewhohacks** [comment]
Hmm not sure what that is. Did you try clearing node_modules / deleting package.lock.json and run a fresh install?

**Comment by crashspringfield** [comment]
Yup. Still the same issue.

**Comment by crashspringfield** [comment]
Here's what logs to the counsel. I included a few lines before it throws the error:

    -- Installing: /home/crash/js/node/tutorials/opencv/node_modules/opencv-build/opencv/build/share/OpenCV/lbpcascades/lbpcascade_frontalcatface.xml
    -- Installing: /home/crash/js/node/tutorials/opencv/node_modules/opencv-build/opencv/build/share/OpenCV/lbpcascades/lbpcascade_frontalface.xml
    -- Installing: /home/crash/js/node/tutorials/opencv/node_modules/opencv-build/opencv/build/share/OpenCV/lbpcascades/lbpcascade_silverware.xml
    -- Installing: /home/crash/js/node/tutorials/opencv/node_modules/opencv-build/opencv/build/share/OpenCV/lbpcascades/lbpcascade_profileface.xml

error here:

    CMake Error at apps/annotation/cmake_install.cmake:42 (FILE):
      file INSTALL cannot find
      "/home/crash/js/node/tutorials/opencv/node_modules/opencv-build/opencv/build/bin/opencv_annotation".
    Call Stack (most recent call first):
      apps/cmake_install.cmake:39 (INCLUDE)
      cmake_install.cmake:90 (INCLUDE)

**Comment by justadudewhohacks** [comment]
Not sure why it fails building the apps, but just noticed I should disable opencv to build the example apps, which are useless for opencv4nodejs anyways.

**Comment by justadudewhohacks** [comment]
Published a new version, maybe you can try to build v3.0.3.

**Comment by crashspringfield** [comment]
Download and install worked. Ran through [your sweet tutorial on medium](https://medium.com/@muehler.v/node-js-opencv-for-face-recognition-37fa7cb860e8) and it worked. Thanks!

**Comment by justadudewhohacks** [comment]
Nice!
