### ISSUE TITLE
`Key pressed, exiting.` without pressing a key, when running some examples on macOS

### ISSUE THREAD

**Issue by vjpr** [justadudewhohacks/opencv4nodejs#17]
Easy fix: On Mac it seems key is -1 when no key is pressed instead of 255.

**Comment by justadudewhohacks** [comment]
Hey,

Yes there seem to be differences across OpenCV versions and OS, which I didn't figure out yet. Thank's for reminding me to take a look at this.

**Comment by carlosen14** [comment]
Thanks, i was going to take a new issue. 👍🏻

**Comment by carlosen14** [comment]
this should work
```
const os = require('os');
...
console.log("os : " , os.platform())
if (os.platform == "darwin"){
    done = key !== -1  ;
}else{
    done = key !== 255  ;
}
```

**Comment by justadudewhohacks** [comment]
Alternatively, as a simple fix I think the following should make it : 
` done = key !== -1 && key !== 255`
Will update the example asap.
