### ISSUE TITLE
How to set environment variable in Mac

### ISSUE THREAD

**Issue by neciszhang** [justadudewhohacks/opencv4nodejs#171]
Hello,i want to set environment variable :OPENCV4NODEJS_DISABLE_AUTOBUILD=1 in Mac. How can i do it?

**Comment by justadudewhohacks** [comment]
I am not a mac user, but I would say it's the same as under linux: `export OPENCV4NODEJS_DISABLE_AUTOBUILD=1`

**Comment by neciszhang** [comment]
Thanks a lot
