### ISSUE TITLE
Issue with Dilate

### ISSUE THREAD

**Issue by codyseibert** [justadudewhohacks/opencv4nodejs#172]
Hey again,

I'm finding that I'm needing to call dilate twice to achieve what I'm trying to do instead of just setting the iteration argument to 2:

expected solution:
```
const dilatedImage = image.dilate(
      new cv.Mat([[1, 1],[1, 1]], cv.CV_8U), 
      new cv.Vec(-1, -1), 
      2
    )
```

what I actually have to do:
```
const dilatedImage = image.dilate(
      new cv.Mat([[1, 1],[1, 1]], cv.CV_8U), 
      new cv.Vec(-1, -1), 
      1
    )
    .dilate(
      new cv.Mat([[1, 1],[1, 1]], cv.CV_8U), 
      new cv.Vec(-1, -1), 
      1
    );
```

Is there something I'm fundamentally missing about how to use dilate, or is this function just broken?

**Comment by justadudewhohacks** [comment]
Does it make a difference if you set the iterations to a much higher value instead of 1? Could be a bug in the bindings. What's also strange is, that you don't get any error passing a cv.Vec, since actually it requires a cv.Point.

**Comment by codyseibert** [comment]
awesome, that works.  Thanks!
