### ISSUE TITLE
How can i use it by webcam?

### ISSUE THREAD

**Issue by neciszhang** [justadudewhohacks/opencv4nodejs#173]
Hello, i want use the example "Hand Gesture Recognition ", how can i use the webcam  instead of the ''/data/hand-gesture.mp4'' in the example? Thanks a lot!

**Comment by neciszhang** [comment]
I know, i read the documents ,and read the VideoCapture API,it's provided devicePort.I change the option use '0',it works, why the devicePot is number zero?

**Comment by neciszhang** [comment]
@justadudewhohacks Thanks a lot!

**Comment by Simon1059770342** [comment]
> @justadudewhohacks Thanks a lot!

Hi there! Have U done what U want to realize the example "Hand Gesture Recognition " in Web?
