### ISSUE TITLE
webcam detection using opencv4nodejs

### ISSUE THREAD

**Issue by vijaysagi** [justadudewhohacks/opencv4nodejs#174]
Hi,

we are new to this framework, gone thru the documentation could u pls suggest how to enable the webcam and detect the face from it.

Thanks

**Comment by justadudewhohacks** [comment]
Example for face detection from webcam:
https://github.com/justadudewhohacks/opencv4nodejs/blob/master/examples/faceDetect/webcamFaceDetectionCpu.js

**Comment by vijaysagi** [comment]
Thats awesome got it....

Currently am using tracking.js for face detection in the client side, could u pls suggest the best possible way to use opencv4nodejs in the client side only for face detection.

**Comment by justadudewhohacks** [comment]
opencv4nodejs is a native package. You cant run native packages in the browser. If you want to do face detection in the browser you can try streaming with websockets, but if trackingjs is good enough for your task I would stick with it.

**Comment by vijaysagi** [comment]
actually the problem with tracking.js is have following problems
1. multiple objects r detected as faces
2. we r not able to detect faces from long distance (ex 15 feet)

using opencv4nodejs we r able to resolve above two issues but we do not know how to invoke from client side

**Comment by justadudewhohacks** [comment]
Yeah when tracking directly in the browser via javascript one has to make tradeoffs between accuracy and performance.

As I said opencv4nodejs does not run on the client only on a webserver. So you would invoke it via a webapi or I would personally recommend websockets(socket.io) for streaming images.

**Comment by komalpharate** [comment]
you can use Opencv.js
https://docs.opencv.org/3.3.1/d5/d10/tutorial_js_root.html
may be

**Comment by jvizarretasilvaUNI** [comment]
Now, the solution like be face-api.js https://itnext.io/face-api-js-javascript-api-for-face-recognition-in-the-browser-with-tensorflow-js-bcc2a6c4cf07 Thanks @justadudewhohacks
