### ISSUE TITLE
How  can i use the tranning cascade.xml ?

### ISSUE THREAD

**Issue by neciszhang** [justadudewhohacks/opencv4nodejs#175]
I use opencv to tranning the cascade.xml,how can i use the cascade.xml in this project?

**Comment by justadudewhohacks** [comment]
The first parameter of cv.CascadeClassifier is the path to your .xml file. The constants like `cv.HAAR_FRONTALFACE_ALT2` are just holding the relative path to the predefined cascade files.

For example:
``` javascript
const path = require('path')
const xmlFilePath = path.resolve('./myFile.xml')
const classifier = new cv.CascadeClassifier(xmlFilePath)
```

**Comment by neciszhang** [comment]
@justadudewhohacks yes, but i have other question.

`grabFrames(0, delay, (frame) => {
	const matBGR = new cv.Mat(frame, cv.CV_8UC3);
	const gray_img= matBGR.cvtColor(cv.COLOR_BGR2HSV);
	const mouse=mouse_haar.detectMultiScale(gray_img,1.2,5);
	cv.imshow('img', frame)
});`

i run the node, it's hinted error
`OpenCV Error: Assertion failed ((scn == 3 || scn == 4) && (depth == 0 || depth == 5)) in cvtColor, file /tmp/opencv-20180113-47978-vhoedt/opencv-3.4.0/modules/imgproc/src/color.cpp, line 11178
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /tmp/opencv-20180113-47978-vhoedt/opencv-3.4.0/modules/imgproc/src/color.cpp:11178: error: (-215) (scn == 3 || scn == 4) && (depth == 0 || depth == 5) in function cvtColor`

**Comment by neciszhang** [comment]
@justadudewhohacks yes!But i have other question!

`grabFrames(0, delay, (frame) => {`
        
    const matBGR = new cv.Mat(frame, cv.CV_8UC3);

	const gray_img= matBGR.cvtColor(cv.COLOR_BGR2HSV);

	const mouse=mouse_haar.detectMultiScale(gray_img,1.2,5);});`


However,i run the node, it's hinted error:
`OpenCV Error: Assertion failed ((scn == 3 || scn == 4) && (depth == 0 || depth == 5)) in cvtColor, file /tmp/opencv-20180113-47978-vhoedt/opencv-3.4.0/modules/imgproc/src/color.cpp, line 11178 libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /tmp/opencv-20180113-47978-vhoedt/opencv-3.4.0/modules/imgproc/src/color.cpp:11178: error: (-215) (scn == 3 || scn == 4) && (depth == 0 || depth == 5) in function cvtColor`

**Comment by justadudewhohacks** [comment]
```
const matBGR = new cv.Mat(frame, cv.CV_8UC3
```
This is not a valid call to the conarructor. What are you trying to achieve here. frame should already be a bgr Mat.

**Comment by justadudewhohacks** [comment]
Closing, if this is still an issue feel free to reopen.
