### ISSUE TITLE
Video Streaming example

### ISSUE THREAD

**Issue by MattCollins84** [justadudewhohacks/opencv4nodejs#178]
Hey, I'm just getting started with OpenCV and I'm loving the module!

I'm looking for a bit of OpenCV advice, plus hopefully an example...

I can access a RTSP stream using `new cv.VideoCapture` no problem, and then output it to a window using `cv.imshow`, however I am finding it tricky to make this output play at a decent speed. It feels clunky/laggy and often ends up behind the stream by a considerable distance.

I am looking for some "best practice" examples on things such as:

- capture a stream and output to window
- Pause/resume
- move to most recent frame of stream

I can do all of the above, but I'm struggling to find good examples that make sense to me. Any help anyone can offer would be great!

Thanks for all your effort on this module!

**Comment by justadudewhohacks** [comment]
Unfortunately I don't have experience with handling RTSP streams in OpenCV, maybe someone else does. Probably better to also ask the OpenCV experts on stackoverflow and/ or OpenCV forums.

**Comment by komalpharate** [comment]
I think you should look for waiKey() function of OpenCV.
Also, you can take a look at ::
https://stackoverflow.com/questions/38064777/use-waitkey-in-order-pause-and-play-video

**Comment by MattCollins84** [comment]
Thank you guys, I will take a look at this!

**Comment by komalpharate** [comment]
Hey
you can also have counting mechanism..
Like, count the number of frame and display nth frame..by just dividing the count by desired 'n'

Also to set fps there are some Properties you can set in Video capture class

https://docs.opencv.org/3.1.0/d8/dfe/classcv_1_1VideoCapture.html#a8c6d8c2d37505b5ca61ffd4bb54e9a7c

Let us know how you implement the mentioned scenario..will help a lot..

**Comment by bruno767** [comment]
Hello @MattCollins84 , 
I am also trying to stream rtsp but is not working for me, could you please share your code?

thanks (Y)
