### ISSUE TITLE
Add more bindings for GUI - e.g. `im.moveWindow`

### ISSUE THREAD

**Issue by vjpr** [justadudewhohacks/opencv4nodejs#18]
https://docs.opencv.org/3.3.0/d7/dfc/group__highgui.html#ga453d42fe4cb60e5723281a89973ee563

**Comment by justadudewhohacks** [comment]
Alright. Only moveWindow?

**Comment by vjpr** [comment]
For now that was just one function I wanted to use that wasn't available.

I'm wondering if there is not a more automated way to easily implement all the methods?

**Comment by justadudewhohacks** [comment]
Nothing that I am aware of, not for nodejs bindings. There is an approach, which compiles some OpenCV modules to pure javascript via LLVM using emscripten, but the future goal of opencv4nodejs is to provide native performance, easy multithreading, async methods and an comfortable to use API.

**Comment by vjpr** [comment]
What if you parse the OpenCV API Docs and generate the entire api?

A quick search found some other people looking for the same thing over in `node-opencv` https://github.com/peterbraden/node-opencv/issues/290.

Also, this project looks interesting: https://github.com/charto/nbind. But I have never tried it out.

**Comment by justadudewhohacks** [comment]
I think that's what I was talking about by compiling it to asm.js using emscripten. Haven't tried any of them yet, but as far as I know asm.js has still considerably less performance than native, maybe that might change with webassembly in future. 

However I am also not sure, if it is possible to achieve async methods and multiple workers that way and how one would generate these, but I don't know asm.js well enough. I'm gonna have a look at your links, thanks for sharing.

**Comment by vjpr** [comment]
I don't think using emscripten/asm is a good idea. Rather, its about generating the bindings from the c code.

The opencv python bindings are generated by parsing the c/cpp headers, and then using some string templates as explained in the answers.opencv.org link.

In the opencv codebase there is some interesting stuff in `opencv/modules/{js,python,ts}`.
