### ISSUE TITLE
Get frames per second of any video stream using opencv4nodejs

### ISSUE THREAD

**Issue by komalpharate** [justadudewhohacks/opencv4nodejs#180]
Hi,
I want to get frames per second of any video file using opencv4nodejs.
I did it in Python and CPP following way:
https://www.learnopencv.com/how-to-find-frame-rate-or-frames-per-second-fps-in-opencv-python-cpp/
Can I get litle help to do that?
I tried following code::
```
const cv = require('opencv4nodejs');
const vCap = new cv.VideoCapture("url");
//const frame = vCap.read();

var i = 0;
while (i != 120) {
    console.log(i);
    if (i == 0)
        var start = new Date().getTime();
    let frame = vCap.read();
    console.log(frame);
    i += 1;
    if (i == 120) {
        var end = new Date().getTime();

        console.log("Time required ::", end - start);
        console.log("FPS ::", (end - start) / 120);
    }
}

```

**Comment by justadudewhohacks** [comment]
Uhm, you should be able to get the fps with: `const fps = vCap.get(cv.CAP_PROP_FPS)`.

**Comment by komalpharate** [comment]
Actually I'm getting 0.0 output for that. As openCV `vCap.get(cv.CAP_PROP_FPS)` doesn't work for all type of streams

**Comment by justadudewhohacks** [comment]
Ah I see. Looking at your code the last line should be `console.log("FPS ::", 120/((end - start) / 1000));` (frames/seconds and not the other way around and timestamps are in milliseconds, thus / 1000). Other then that it should work.

**Comment by komalpharate** [comment]
OOps..it's right..
Thank you very much..
