### ISSUE TITLE
[Feature request] Add enums

### ISSUE THREAD

**Issue by cotejp** [justadudewhohacks/opencv4nodejs#184]
There are quite a few [enums](https://docs.opencv.org/3.1.0/df/d4e/group__imgproc__c.html) that are defined by OpenCV. Some of them are available in opencv4nodejs while others are not. 

Are you planning on eventually adding them all ? If so, would it be possible to add the ones expected by `findContours()` ? Those are: 

```
CV_RETR_EXTERNAL =0, 
CV_RETR_LIST =1, 
CV_RETR_CCOMP =2, 
CV_RETR_TREE =3, 
CV_RETR_FLOODFILL =4 

CV_CHAIN_CODE =0, 
CV_CHAIN_APPROX_NONE =1, 
CV_CHAIN_APPROX_SIMPLE =2, 
CV_CHAIN_APPROX_TC89_L1 =3, 
CV_CHAIN_APPROX_TC89_KCOS =4, 
CV_LINK_RUNS =5 
```
Thanks.

**Comment by justadudewhohacks** [comment]
Hi,

These enums are from the old C API and they have equivalents in the CPP API, which are exported by opencv4nodejs. These do not have the **CV_** prefix, for example `RETR_EXTERNAL `.

I exported most of the constants and enums here:
[cvTypes.cc](https://github.com/justadudewhohacks/opencv4nodejs/blob/10e11778b4e930ec5b8f0e0a0d34e5789811786c/cc/cvTypes/cvTypes.cc)
[imgprocConstants.cc](https://github.com/justadudewhohacks/opencv4nodejs/blob/10e11778b4e930ec5b8f0e0a0d34e5789811786c/cc/cvTypes/imgprocConstants.cc)
[videoCaptureProps.cc](https://github.com/justadudewhohacks/opencv4nodejs/blob/10e11778b4e930ec5b8f0e0a0d34e5789811786c/cc/cvTypes/videoCaptureProps.cc)

In case something is missing (which might be), let me know and I will be happy to add them.

I actually use some of the enums related to `findContours()` in the fingertip detection example:
[handGestureRecognition0.js](https://github.com/justadudewhohacks/opencv4nodejs/blob/10e11778b4e930ec5b8f0e0a0d34e5789811786c/examples/handGestureRecognition0.js)

**Comment by cotejp** [comment]
My bad. I first tried using `CV_RETR_TREE` then `cv.CV_RETR_TREE` and then I figured they weren't available. Thanks.
