### ISSUE TITLE
compareHist example

### ISSUE THREAD

**Issue by peterforgacs** [justadudewhohacks/opencv4nodejs#185]
Hi!

First of all thanks for the great work!
I'm trying to compare the histograms of two images with compareHist method.
I've tried to figure it out from the histogram example but i got stuck on the error:

`
terminate called after throwing an instance of 'cv::Exception'
  what():  /opencv/opencv-3.1.0/modules/imgproc/src/histogram.cpp:2344: error: (-215) H1.type() == H2.type() && H1.depth() == CV_32F in function compareHist`

I guess it has something to width the depth not matching but i'm not sure how i can manipulate that.
This is what i've tried:

```js
'use strict';
const cv = require('opencv4nodejs');

const getHistAxis = channel => ([
    {
      channel,
      bins: 256,
      ranges: [0, 256]
    }
]);

const getHistChange = ({ targetFile, templateFile }) => {
    if (!targetFile || !templateFile){
        return console.error('Missing arguments.');
    }

    const image = cv.imread(targetFile);
    const imageHist = cv.calcHist(image, getHistAxis(0))

    const template = cv.imread(templateFile);
    const templateHist = cv.calcHist(template, getHistAxis(0))

    return imageHist.compareHist(templateHist, 0);
}

getHistChange({
    targetFile: './target.jpg',
    templateFile: './template.jpg'
});
```

Could you give me an example of using this function correctly?
Thanks in advance

**Comment by justadudewhohacks** [comment]
The error message says that compareHist expects both histograms to be of type CV_32F, but cv.calcHist returns them as CV_64F, which I should probably fix, sorry for the inconvenience.

You can simply convert the type of matrices. Also look at #159, I think this is exactly the code that you want.

**Comment by peterforgacs** [comment]
Thanks a lot, it works.

```js
const H1 = cv.calcHist(image, [{
    channel: 0,
    bins: 256,
    ranges: [0, 256]}
]).convertTo(cv.CV_32F);
```
