### ISSUE TITLE
Can not load open_nsfw caffe model

### ISSUE THREAD

**Issue by digitaledge** [justadudewhohacks/opencv4nodejs#186]
Hi,

first of all thank you for this great work!

I am actually trying to load the open_nsfw model by [yahoo](https://github.com/yahoo/open_nsfw).
Problem is that openCV does return an error similar to the one explained in this [issue](https://github.com/opencv/opencv/issues/10530). That issue was fixed with this [PR](https://github.com/opencv/opencv/pull/10550). 

Im wondering how i could upgrade openCV to the lastest version including the fix, when using this module for the bindings.

Cheers
Stefan

**Comment by nskondratev** [comment]
@digitaledge Hi,
I faced the same issue, because I had installed opencv4nodejs with auto build OpenCV.
To solve this I installed OpenCV v3.4.1 with [this instruction](http://www.samontab.com/web/2017/06/installing-opencv-3-2-0-with-contrib-modules-in-ubuntu-16-04-lts/), but replacing versions from **v3.2.0** to **v3.4.1**.
After that I removed **node_modules** directory and install packages with disabled OpenCV auto build:

```bash
OPENCV4NODEJS_DISABLE_AUTOBUILD=1 npm i
```

Now model is loading without errors.

**Comment by digitaledge** [comment]
Thanks @nskondratev 

Well, i wanted to have openCV still installed by NPM.
Actually i solved it by changing the version tag in the opencv-build dependency to 3.4.1.

**Comment by justadudewhohacks** [comment]
Nice, feel free to submit a PR to opencv-build. I didnt notice 3.4.1 to be released yet.

**Comment by digitaledge** [comment]
@justadudewhohacks

I just submitted a PR.

**Comment by nskondratev** [comment]
@digitaledge 

I get the right value from Yahoo model by executing the following code:

```js
cv
  .readNetFromCaffeAsync(prototxt, modelFile)
  .then(net => {
    // Net is loaded
    return cv
      .imreadAsync('bad_img.jpg')
      .then(img => cv.blobFromImageAsync(img, 1.0, new cv.Size(224, 224), new cv.Vec3(104, 117, 123)))
      .then(inputBlob => net.setInputAsync(inputBlob))
      .then(() => net.forwardAsync())
      .then(outputBlob => outputBlob.at(0, 1))
      .then(score => console.log(`NSFW Score for image: ${score}`))
  })
```

But the probability on the same images is not as high as if I pass them to the [original code](https://github.com/yahoo/open_nsfw).

I think, that lack of pre-processing is the reason for getting worse results. Pre-processing in the [classify_nsfw.py](https://github.com/yahoo/open_nsfw/blob/79f77bcd45076b000df71742a59d726aa4a36ad1/classify_nsfw.py#L110):

```python
# Load transformer
# Note that the parameters are hard-coded for best results
caffe_transformer = caffe.io.Transformer({'data': nsfw_net.blobs['data'].data.shape})
caffe_transformer.set_transpose('data', (2, 0, 1))  # move image channels to outermost
caffe_transformer.set_mean('data', np.array([104, 117, 123]))  # subtract the dataset-mean value in each channel
caffe_transformer.set_raw_scale('data', 255)  # rescale from [0, 1] to [0, 255]
caffe_transformer.set_channel_swap('data', (2, 1, 0))  # swap channels from RGB to BGR
```

**Comment by digitaledge** [comment]
Thanks @nskondratev!
The issue was caused by creating the inputBlob with wrong params.
Finally i got it to work now using your example! 

This is how it looks here using async/await:
`const classify = async (imagePath) => {

    const imgPath = __dirname + imagePath; // todo: add upload root here
    const img = await cv.imreadAsync(imgPath);
    const inputBlob = await cv.blobFromImageAsync(img, 1.0, new cv.Size(224, 224), new cv.Vec3(104, 117, 123));

    await net.setInputAsync(inputBlob);

    const outputBlob = await net.forwardAsync();
    const score = outputBlob.at(0, 1);

    return { score }
};`

Actually the scores are looking quite good, but i noted the same differences like you.
Im wondering if the pre-processing could be somehow done by openCV.

**Comment by matt212** [comment]
hi @digitaledge  , 

what does finalcode base look like .

how to integrate below  (a) and (b) codeblocks 

_(a)_
```
const cv = require('opencv4nodejs');
const fs = require('fs');
const path = require('path');
const prototxt = 'nsfw_model/deploy.prototxt'
const modelFile = 'nsfw_model/resnet_50_1by2_nsfw.caffemodel'
cv
    .readNetFromCaffeAsync(prototxt, modelFile)
    .then(net => {
        // Net is loaded
        return cv
            .imreadAsync('./data/e.jpg')
            .then(img => cv.blobFromImageAsync(img, 1.0, new cv.Size(224, 224), new cv.Vec3(104, 117, 123)))
            .then(inputBlob => net.setInputAsync(inputBlob))
            .then(() => net.forwardAsync())
            .then(outputBlob => outputBlob.at(0, 1))
            .then(score => console.log(`NSFW Score for image: ${score}`))
    })

```
_(b)_

```
 const classify = async(imagePath) => {

    const imgPath = imagePath; // todo: add upload root here
    console.log(imgPath);
    const img = await cv.imreadAsync(imgPath);
    const inputBlob = await cv.blobFromImageAsync(img, 1.0, new cv.Size(224, 224), new cv.Vec3(104, 117, 123));

    await net.setInputAsync(inputBlob);

    const outputBlob = await net.forwardAsync();
    const score = outputBlob.at(0, 1);
    console.log(`NSFW Score for image: ${score}`)
    return { score }
}; 
```

any pointers !
