### ISSUE TITLE
How to detect if image is cup?

### ISSUE THREAD

**Issue by emretekince** [justadudewhohacks/opencv4nodejs#187]
Hello,
I just want to detect if image is a coffee cup or not.
Can you show me a sample code? I dont have experience about OpenCV

**Comment by justadudewhohacks** [comment]
Hi,

You probably want to take a look at the object recognition examples with Tensorflow inception or the SSD example:
[dnnTensorflowInception.js](https://github.com/justadudewhohacks/opencv4nodejs/blob/master/examples/dnnTensorflowInception.js)
[dnnSSDCoco.js](https://github.com/justadudewhohacks/opencv4nodejs/blob/master/examples/dnnSSDCoco.js)

Also the [object recognition article](https://medium.com/@muehler.v/node-js-meets-opencvs-deep-neural-networks-fun-with-tensorflow-and-caffe-ff8d52a0f072) might be useful for you.

**Comment by emretekince** [comment]
Thank you
