### ISSUE TITLE
face recognition using python

### ISSUE THREAD

**Issue by vijaysagi1** [justadudewhohacks/opencv4nodejs#189]
My requirement is  using opencv4nodejs i need to read the detected webcam face from python application where i need  to extract 128 face embeddings and undergo face recognition(using our custom logic in python).

Pls suggest how can i read the streamed face from python application.

**Comment by justadudewhohacks** [comment]
Could you tell me what exactly you need to read from your python application and how opencv4nodejs fits into this, if you perform face detection and face recognition in your python application?

**Comment by vijaysagi1** [comment]
Face detection was the major challenge with python:
   **webcam detection from multiple clients is a challenge. While accessing the application from different browsers always server side streaming was enabled instead of client stream**
 
for Face recognition the following is the challenge
 **once the face is detected on client side(using tracking.js), it is saved as a image in a tmp folder then  facial coordinates are extracted. The above approach is a challenge when multiple clients r involved** 

using opencv4nodejs i want to detect multiple faces from multiple clients and undergo face recognition
in real time while streaming the detected face.

**Comment by justadudewhohacks** [comment]
Didn't you ask a similar question in #174 yet? As I said, the approach would be to stream the webcam images from your clients (via websockets, with socket.io for example) to a nodejs server with opencv4nodejs installed, which does face detection/ face recognition and streams the results back.

**Comment by justadudewhohacks** [comment]
Closing.
