### ISSUE TITLE
Support Tracking api

### ISSUE THREAD

**Issue by vjpr** [justadudewhohacks/opencv4nodejs#19]
https://docs.opencv.org/3.3.0/d9/df8/group__tracking.html

**Comment by justadudewhohacks** [comment]
Hey,

For now, I added the following bindings to v2.8:
- Trackers (Boosting, GOTURN, MIL, KCF, MedianFlow, TLD)
- MultiTracker

Please let me know, if you urgently need something else from this module soon, or if something is not working as supposed to.
