### ISSUE TITLE
Train the data model with new Fonts

### ISSUE THREAD

**Issue by RoncoCo** [justadudewhohacks/opencv4nodejs#194]
Hi,

I have recently started using the library and it is working amazing and the software is able to recognize and detect English almost perfectly.

Recently I have encountered _Italic_ text fonts and to my surprise, it is completely different and the software struggles and detecting almost everything wrong.

How can I train my software to detect _Italic_ fonts?

Thanks

**Comment by justadudewhohacks** [comment]
Hi,

Are you talking about the OCR example with HOG + SVM? I just used some handwritten letters to train the SVM, so it should mainly only be able to recognize my handwriting.

If you want to recognize Italic fonts, you would have to train from your own dataset.

**Comment by RoncoCo** [comment]
Yes, I am trying to train the system with Italic fonts,
Can you refer me to where should I look for an example of how to train the system with new fonts?

**Comment by RoncoCo** [comment]
Got it,
https://medium.com/@muehler.v/machine-learning-with-opencv-and-javascript-part-1-recognizing-handwritten-letters-using-hog-and-88719b70efaa

Thanks,
