### ISSUE TITLE
npm install error on win 8.1

### ISSUE THREAD

**Issue by matt212** [justadudewhohacks/opencv4nodejs#196]
Hi, 

I am getting below error while executing below codebase 

`npm install --save opencv4nodejs`

error message 

![4](https://user-images.githubusercontent.com/1698139/37351205-8f54eb2e-2700-11e8-81ec-6ec0c0237e33.png)

what are depedencies required to prior to running 

`npm install --save opencv4nodejs`

any pointers on how to resolve this issues !

**Comment by justadudewhohacks** [comment]
Well, does the directory printed exist? Also, did the output complete without errors?

**Comment by justadudewhohacks** [comment]
Ah okay. Once you install opencv4nodejs, it first install opencv-build, which clones OpenCV and builds it from scratch. Did that one complete successfully? If so the path that is printed in the error message should exist and contain .lib files.

**Comment by matt212** [comment]
nope . no building is complete
The whole folder is empty not even node_modules folder exists !
Since i ran on empty folder 
Please find attached screenshot for
![6](https://user-images.githubusercontent.com/1698139/37355373-a94f2a0e-2709-11e8-960a-3363606a72e7.png)

**Comment by justadudewhohacks** [comment]
Odd, it looks like it directly executes the install script of opencv4nodejs without even installing it's dependencies. Which npm version are you using (`npm -v`) ?

You could try to install opencv-build first `npm install --save opencv-build`. Also I would first of all initialize a package.json in your working directory (`npm init -y`).

**Comment by matt212** [comment]
sure will try and provide with an update accordingly 

my current npm and node version  details are

npm 5.2.0
node v8.5.0

**Comment by matt212** [comment]
Thanks provided suggestion helped !

![9](https://user-images.githubusercontent.com/1698139/37387290-d88e0e2a-2781-11e8-9d73-07980da3d6b5.png)

also i want to moderation nsfw images is , could you please provide with some pointers.
Since i am quite nascent in opencv , tensorflow universe

**Comment by justadudewhohacks** [comment]
Great. I haven't tried it yet but have a look at #186. Apparently there is a caffe model provided by yahoo which is able to detect nsfw content.
