### ISSUE TITLE
Publish Dockerfile used for base image

### ISSUE THREAD

**Issue by stefancrain** [justadudewhohacks/opencv4nodejs#198]
These docker base images are great, please include the Dockerfile that created them 👍 

https://hub.docker.com/r/justadudewhohacks/opencv-nodejs/

**Comment by justadudewhohacks** [comment]
Sure, was just working on updating all the docker images. I still need to adjust this one for the current opencv4nodejs version, but will include it. Basically it's just something like this [Dockerfile](https://github.com/justadudewhohacks/opencv4nodejs-docker-images/blob/master/opencv/Dockerfile), with a global installation of the package.

**Comment by justadudewhohacks** [comment]
Dockerfiles can be found at [opencv4nodejs-docker-images](https://github.com/justadudewhohacks/opencv4nodejs-docker-images).
