### ISSUE TITLE
remote image path in imreadAsync module

### ISSUE THREAD

**Issue by matt212** [justadudewhohacks/opencv4nodejs#200]
Hi, 
It would be really great if we load image from url rather than file system.
Is there any way except downloading image and giving path to module pertaining to image processing 
imreadAsync('./data/c.jpg') 

any pointers on same !

**Comment by matt212** [comment]
hi, 
since rather than issue of this module closing this issue !

**Comment by ManuelZ** [comment]
Hey @matt212 did you discover how to load an image from an url?
