### ISSUE TITLE
Library not loaded: @rpath/libopencv_core.3.4.dylib

### ISSUE THREAD

**Issue by fakob** [justadudewhohacks/opencv4nodejs#204]
Hi, 

I was wondering if anyone else is packaging the opencv4nodejs library with electron-builder into a desktop app. For [my project](https://github.com/fakob/MoviePrint_v004), which uses the [electron-react-boilerplate ](https://github.com/chentsulin/electron-react-boilerplate) I am trying to do just that. Running it in dev mode works like a charm, but as soon as I build it and try it on a different machine, I get the following error.
```dlopen(/var/folders/b_/j_t1rf8d08bbfkm7rv9l06940000gn/T/.org.develar.ElectronReact.modQGT, 1): Library not loaded: @rpath/libopencv_core.3.4.dylib```

When searching the web I came across [similar issue](https://github.com/electron-userland/electron-builder/issues/2434) where the solution mentioned was
>This was not an issue with electron-builder. The problem was that the library was installed using a particular version of python (python2 in this case), while I built the package using a different python (python3). Using the same python to install the modules and to package the app solved the problem.

Now, to try this solution, I was wondering how I can actually control with which python version to install or build opencv4nodejs?

Here the full error:
```Uncaught Exception: Error: dlopen(/var/folders/b_/j_t1rf8d08bbfkm7rv9l06940000gn/T/.org.develar.ElectronReact.modQGT, 1): Library not loaded: @rpath/libopencv_core.3.4.dylib
Referenced from: /var/folders/b_/j_t1rf8d08bbfkm7rv9l06940000gn/T/.org.develar.ElectronReact.modQGT
Reason: image not found
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jakob/Desktop/ElectronReact.app/Contents/Resources/app.asar/node_modules/opencv4nodejs/lib/opencv4nodejs.js:13:8)
    at Object.<anonymous> (/Users/jakob/Desktop/ElectronReact.app/Contents/Resources/app.asar/node_modules/opencv4nodejs/lib/opencv4nodejs.js:31:3)```

**Comment by justadudewhohacks** [comment]
I think your problem is not python but the fact, that you have to bundle your app with the shared object libraries of opencv. The opencv4nodejs.node file built with nodegyp contains external references to the .so / .dylib files of your opencv installation. If you are to ship an executable you would also have to ship the shared object libraries and link the package against these. But as I said in your other issue, I dont have Experience with electron-bundler, but maybe the above said helps you.

**Comment by fakob** [comment]
Thanks for the tip, I will look into it and also do some more research on how electron-builder links the packages.

**Comment by fakob** [comment]
An update to my issue. First off, I have not solved it yet and still get a similar error. 
Nevertheless you had pointed out something important which I had tried to solve.

electron-builder packages all necessary folders in node_modules (opencv-build and opencv4nodejs) into an electron archive format called asar. Changing the setting to not wrap the 2 modules into the asar file, changes the error message to
`
dlopen(/Applications/MoviePrint_v004.app/Contents/Resources/app.asar.unpacked/node_modules/opencv4nodejs/build/Release/opencv4nodejs.node, 1): Library not loaded: @rpath/libopencv_core.3.4.dylib
Referenced from: /Applications/MoviePrint_v004.app/Contents/Resources/app.asar.unpacked/node_modules/opencv4nodejs/build/Release/opencv4nodejs.node
Reason: image not found
`
Running `otool -l opencv4nodejs.node` shows all opencv dylib files and their paths. E.g. 
```
Load command 8
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libopencv_core.3.4.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 3.4.0
compatibility version 3.4.0
```
Originally, as you pointed out, the only path listed is an absolute one. 
```
Load command 28
          cmd LC_RPATH
      cmdsize 120
         path /Users/jakob/Documents/Electron/MoviePrint_v004/app/node_modules/opencv-build/opencv/build/lib (offset 12)
```
As I am not fully sure how exactly the linking works I added multiple rpath options to the binding.gyp file for testing. This:
```
    "link_settings": {
        "libraries": [
          "-Wl,-rpath,$$ORIGIN/MoviePrint_v004.app/Contents/Resources/app.asar.unpacked/node_modules/opencv-build/opencv/build/lib",
          "-Wl,-rpath,$$ORIGIN/../Resources/app.asar/node_modules/opencv-build/opencv/build/lib",
          "-Wl,-rpath,$$ORIGIN/../../../opencv-build/opencv/build/lib"
        ],
      },
```
added more paths to opencv4nodejs.node
```
Load command 29
          cmd LC_RPATH
      cmdsize 120
         path /MoviePrint_v004.app/Contents/Resources/app.asar.unpacked/node_modules/opencv-build/opencv/build/lib (offset 12)
Load command 30
          cmd LC_RPATH
      cmdsize 88
         path /../Resources/app.asar.unpacked/node_modules/opencv-build/opencv/build/lib (offset 12)
Load command 31
          cmd LC_RPATH
      cmdsize 56
         path /../../../opencv-build/opencv/build/lib (offset 12)
```
but it seems that the path to `libopencv_core.3.4.dylib` still does not get resolved properly. Maybe my tests for referencing are still wrong, but I tried relative paths from the executable as well as from opencv4nodejs.node. 
I will have to investigate further.

**Comment by fakob** [comment]
And again an update to my issue. 
Regarding the proper link settings in the binding.gyp file I have found that 
```
		"link_settings": {
			"libraries": [
				"-Wl,-rpath,@loader_path/../../../opencv-build/opencv/build/lib"
			],
		},
```
seems to be the correct path to use. 
However, it still does not work. `electron-builder` which I use for packaging wraps everything in an [asar file](https://github.com/electron/asar) which is a tar like archive (mentioned it earlier). For native stuff I am using the option to leave the `opencv4nodejs` and the `opencv-build` modules unpacked. However it appears that only the actual dylib files are unpacked and not the symlinks. 
The file `libopencv_core.3.4.dylib` for example, referenced from `opencv4nodejs.node`, can be found in the app.asar file, but not in the app.asar.unpacked folder. 
```
Resources
--app.asar
    |--node_modules
        |--opencv-build
            |--opencv
                |--build
                    |--lib
                        |--libopencv_core.3.4.0.dylib
                        |--libopencv_core.3.4.dylib
                        |--libopencv_core.dylib
--app.asar.unpacked
    |--node_modules
        |--opencv-build
            |--opencv
                |--build
                    |--lib
                        |--libopencv_core.3.4.0.dylib
```
So I will continue to investigate :-)

**Comment by fakob** [comment]
Finally I made it work. 
What I had overlooked was the possibility in `electron-builder` to prevent packing the app folder into an asar file completely. I only had used the `asarUnpack` feature. Now I have added this to the electron-builder setup
```
"asar": false
```
which keeps everything in a folder. 
This combined with adding a relative path in `binding.gyp` for `opencv4nodejs.node` did the trick. 
```
"link_settings": {
	"libraries": [
		"-Wl,-rpath,@loader_path/../../../opencv-build/opencv/build/lib"
	],
},
```

**Comment by fakob** [comment]
@justadudewhohacks I think it could be valuable to include the following relative link in your `binding.gyp`. It would not replace the absolute one which is added automatically, but just be an addition. What do you think?
```
"link_settings": {
	"libraries": [
		"-Wl,-rpath,@loader_path/../../../opencv-build/opencv/build/lib"
	],
},
```

**Comment by justadudewhohacks** [comment]
Nice! Agreed, adding a flag to the linker settings shouldn't hurt anybody:
```
...
"ldflags" : [
  "-Wl,-rpath,'$$ORIGIN'",
  "-Wl,-rpath,@loader_path/../../../opencv-build/opencv/build/lib"
],
...
```

**Comment by fakob** [comment]
Ah, ok it should go into `ldflags`. Do you know what the difference is? 

The `link settings` had worked for me as I could edit the `binding.gyp` file and running `yarn` again afterwards, did not overwrite it with the original. Using `ldflags` that "trick" did not work.

Shall I make a PR?

**Comment by fakob** [comment]
I have now run another test and not sure why, but when using `ldflags` instead of `link_settings -> libraries` the `@loader_path` path does not get added. Did it work for you?

**Comment by justadudewhohacks** [comment]
Hmm, actually I didn't try it out, but I think your solution is also ok, as long as these flags are applied in a condition section in the .gyp file, as this apparently may fail on windows, or atleast generate warnings.

**Comment by MDOBreno** [comment]
If you are having this Problem:

> dyld: Library not loaded: *.dylib ... Reason: no suitable image found.

Means your *.dylib files are not signed with your Apple iD develop account, and
There is two ways to solve that:

1) The right way:  Code sign all your files with errors with this command:

    codesign -f -s "Mac Developer: YOURDEVELOPEREMAIL" /usr/local/opt/*/lib/*.dylib

2) The temporary way(until you don't deploy to App Store): Inside Xcode, go to:

`[YourProjectFile]` --> `[YourTargetFile]` --> `"Signing & Capabilities"` --> and Enable `"Disable Library Validation"`

Done :D

**Comment by zcmgyu** [comment]
@MDOBreno I have the same issues as yours, but it did not help me at all.

This is my attempt:

I enabled **com.apple.security.cs.disable-library-validation** key in **entitlements.mac.plist** before make a build. Afterward, _no suitable image found_ error message has gone.

**entitlements.mac.plist**

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>
  </dict>
</plist>
```
