### ISSUE TITLE
MSER detectRegions

### ISSUE THREAD

**Issue by btsimonh** [justadudewhohacks/opencv4nodejs#205]
Hi, is there any way to call the MSER detectRegions function (from features2d)?
I can create an MSER detector, and run detect, but this generates a set of points.  MSER adds a detectRegions function which returns both (points in each region) and (regions).

I'm guessing this would need to be added as a function of the detector, rather than as a generic function on features2d?  I could have a crack at it, but advice probably required :)

**Comment by justadudewhohacks** [comment]
Hi,

The detectors in this package currently only implement detect and compute. From a quick look at the docs it seems as only MSER implements detectRegions, right? So it could be added as a function directly in the [MSERDetector.cc](https://github.com/justadudewhohacks/opencv4nodejs/blob/master/cc/modules/features2d/detectors/MSERDetector.cc) I guess.

If you want to attempt it, having quick look at the adding-function-bindings section in the [contribution guide](https://github.com/justadudewhohacks/opencv4nodejs/blob/master/CONTRIBUTING.md#adding-function-bindings) might help. For new function bindings I try to stick with the Worker struct pattern as you only have to write a struct once for the function binding and can convienently create a sync and async binding from it. Probably also helps to have a look at how other bindings are implemented, the pattern is usually the same.

PS: You can use converters for all kinds of stuff, like an ArrayOfArray of `cv::Point2d`, which you might need for stuff like `std::vector<std::vector<Point>>`.

**Comment by btsimonh** [comment]
ok, PR in place for base code.  Tested Async.
didn't quite understand the unwrap stuff in terms of the async; please check it's ok as is.
