### ISSUE TITLE
How to Use the Android 'IP Webcam' App with opencv4nodejs ?

### ISSUE THREAD

**Issue by komalpharate** [justadudewhohacks/opencv4nodejs#209]
Hi
I got this : 
How to Use the Android 'IP Webcam' App with Python / OpenCV  : 

https://www.hackster.io/peter-lunk/how-to-use-the-android-ip-webcam-app-with-python-opencv-45f28f

Can I do this with opencv4nodejs?

**Comment by komalpharate** [comment]
I did it by reopening url for each frame.
but the issue is Videocapture takes time to open the url.
so Im not able to stream mobile phone camera faster.
So can I solve it or thats the way it works?

**Comment by justadudewhohacks** [comment]
Why did you reopen the VideoCapture each time? You should open it once and then read frames using cap.read() or am I misunderstanding something here? Could you share the code you are using?

**Comment by komalpharate** [comment]
Hi,
The URL I want to open is 
http://ip-address/shot.jpg
It's progressive image url..that is why..
As mentioned in my first comment, IP webcam application gives the URL in this format

**Comment by justadudewhohacks** [comment]
Well according to OpenCV forum posts it should work the same as with a video file. Open the url once in the VideoCapture, then read the frames: http://answers.opencv.org/question/133/how-do-i-access-an-ip-camera

**Comment by wbern** [comment]
Closing. Feel free to re-open if you keep having issues.

**Comment by nlaboren** [comment]
Does anyone here have the IP webcam APK?
