### ISSUE TITLE
Install fails without autobuild

### ISSUE THREAD

**Issue by MattCollins84** [justadudewhohacks/opencv4nodejs#213]
Hey,

I am trying to build the module whilst using my pre-installed version of OpenCV. While it's building I get this error:

`opencv4nodejs.target.mk:208: recipe for target 'Release/obj.target/opencv4nodejs/cc/modules/machinelearning/SVM.o' failed`

Does anyone have an idea what this might be?

````
opencv_version = 3.1.0-dev
which opencv_version = /usr/local/bin/opencv_version
````

**Comment by MattCollins84** [comment]
To add a bit of extra context...

If I run with autobuild and do `cv.version` I get `{ major: 3, minor: 4 }`... does this mean that I need to update my locally installed OpenCV to `3.4?`

**Comment by justadudewhohacks** [comment]
The auto build script builds opencv 3.4.1. You can use any opencv 3 minor version if you want.

I need the full error log to figure out why the build is failing for you.

**Comment by MattCollins84** [comment]
[debug.log](https://github.com/justadudewhohacks/opencv4nodejs/files/1836958/debug.log)

This is the log file that NPM gives me after the install, is this what you are looking for?

Thanks

**Comment by justadudewhohacks** [comment]
I was talking about the logging output on your terminal when you type npm install. Sorry for confusion.

**Comment by MattCollins84** [comment]
[output.log](https://github.com/justadudewhohacks/opencv4nodejs/files/1837377/output.log)

No worries! Thanks for your time

This is on an Ubuntu desktop

**Comment by justadudewhohacks** [comment]
Odd, the error message says:
```
../cc/modules/machinelearning/SVM.cc:145:66: error: expected primary-expression before ‘>’ token
  FF_UNWRAP(info.This(), SVM)->svm = cv::ml::SVM::load<cv::ml::SVM>(path);
                                                                  ^
```

What's your gcc version? But since you can build via auto build I don't think gcc is the issue here. My guess is, that there is something messed up with the header files.

Is your opencv 3.1 compiled from the release source code or from cloning the repo some point in time? Did you change some cmake settings, e.g. disable the ML module or something?

**Comment by MattCollins84** [comment]
I don't know this information. I'm tempted to re-install again with the latest version to match your autobuild version, but I can't do that at the moment. 

Maybe you can answer my main query tho.. The reason I want to do this, is that I am sure that my local installation is built with GPU support. I am unsure that the autobuild version is built in this way - can you help me with this?

The reason I ask is that when I do anything to do with tracking on my MacBook the performance is not great... I was expecting it to be better on the Ubuntu box that has a nice Nvidia GPU in it, but performance was the same. This is when I started to look into the autobuild.

**Comment by justadudewhohacks** [comment]
Ah okay, that explains it. I think some stuff in the machine learning module e.g. SVM has different signatures when building with CUDA support. Atleast I think I faced that problem once.

The thing is opencv4nodejs does not really support a CUDA build, as there are no bindings for the CUDA module implemented. Would be a nice to have (also OCL bindings), however I don't have a NVIDIA GPU, thus am not able to test and implement these.

I think I mentioned in another issue that if someone wants to implement CUDA bindings, I am happy to take PRs.

**Comment by MattCollins84** [comment]
Ah ok, that makes sense!

Thank you for your help and I love the module

**Comment by justadudewhohacks** [comment]
I think the actual issue with cuda builds is, that opencv4nodejs might link the cuda libraries instead of the cpu ones as pointed out in #162.

**Comment by MattCollins84** [comment]
Ok, I have read that issue and only somewhat follow it - is this something that is fixable?

**Comment by justadudewhohacks** [comment]
Currently working on it.

**Comment by MattCollins84** [comment]
thank! You are awesome

**Comment by MattCollins84** [comment]
Just re-opening this issue so I see any progress :)

**Comment by justadudewhohacks** [comment]
Oh, it should have been fixed already a while ago, forgot to notify you.

**Comment by MattCollins84** [comment]
Hey, I just tried again with version `4.2.0` and I got the same error.. :(

**Comment by justadudewhohacks** [comment]
Hm, then your issue might not have been related to the problem of linking wrong libraries as pointed out by @cjntaylor in #162, as this issue should be resolved by now (if not then it's my fault, please let me know).

I am not sure in which opencv CUDA module the SVM code resides, but you could try to temporarily rename that library and see if this resolves your issue. If it does then the issue mentioned above apparently is not fixed properly yet.
