### ISSUE TITLE
Running on react native app

### ISSUE THREAD

**Issue by RyszardRzepa** [justadudewhohacks/opencv4nodejs#214]
Hey,

I was trying to run ur package 'opencv4nodejs'  in react native app where I run node js on a separate thread.
I manage to run IOS app with node 'express' package. I succesfull installed  opencv4nodejs, but when I import `var cv = require('opencv4nodejs')`, I am getting an error: 

```
Error: dlopen(/Users/ryrz01/Library/Developer/CoreSimulator/Devices/55B8702F-DC21-4EC4-8440-3A420CA895E8/data/Containers/Bundle/Application/018299DA-823D-4B36-A001-B48193BD0235/nodeJs_demo.app/nodejs-project/node_modules/opencv4nodejs/build/Release/opencv4nodejs.node, 1): no suitable image found.  Did find:
	/Users/ryrz01/Library/Developer/CoreSimulator/Devices/55B8702F-DC21-4EC4-8440-3A420CA895E8/data/Containers/Bundle/Application/018299DA-823D-4B36-A001-B48193BD0235/nodeJs_demo.app/nodejs-project/node_modules/opencv4nodejs/build/Release/opencv4nodejs.node: mach-o, but not built for iOS simulator
   at Module._extensions[.node] (module.js:653:3)
   at Module.prototype.load (module.js:545:3)
   at tryModuleLoad (module.js:508:5)
   at Module._load (module.js:500:3)
   at Module.prototype.require (module.js:568:3)
   at require (internal/module.js:11:7)
   at Anonymous function (/Users/ryrz01/Library/Developer/CoreSimulator/Devices/55B8702F-DC21-4EC4-8440-3A420CA895E8/data/Containers/Bundle/Application/018299DA-823D-4B36-A001-B48193BD0235/nodeJs_demo.app/nodejs-project/node_modules/opencv4nodejs/lib/opencv4nodejs.js:16:3)
   at Module.prototype._compile (module.js:624:5)
   at Module._extensions[.js] (module.js:635:3)
   at Module.prototype.load (module.js:545:3)
```

I am wondering why other node.js package works but not opencv4nodejs?

I used this library for node-react-native: https://github.com/janeasystems/nodejs-mobile-react-native

**Comment by justadudewhohacks** [comment]
I am sorry but installing this package wont work on a mobile device.

You can only use node modules with react native, which are not or do not use native node modules. Opencv4nodejs is a native nodejs module, which has to be compiled for a specific OS, architecture, node ABI etc.

Furthermore it requires an OpenCV setup, which has to be also compiled for a specific platform. You can build OpenCV for android or IOS if desired, but you would have to consume it in the native language (java / objective C).

**Comment by RyszardRzepa** [comment]
Thanks a lot for a quick replay. 

If I want to use Opencv4nodejs as an API and push for example to the google cloud servers, is it the same process as regular node.js app ?

**Comment by justadudewhohacks** [comment]
I would say it depends. The machine you are pushing to has to have opencv set up or has to be able to build opencv via the auto build script.

I would recommend you to dockerize your app and use the opencv-nodejs base image (see express example). Using docker you have to deal with none of that and you can use opencv4nodejs right out of the box.

**Comment by RyszardRzepa** [comment]
Great! I will try to set it up with docker.

Are u using ur library in any production project? 
Do you know any examples on which I could take a look?

**Comment by justadudewhohacks** [comment]
I don't have any app running in a production environment, I am just a student :D 

I know of some people, that have reported me they are using opencv4nodejs and/ or face-recognition.js in production, but I don't know if anybody open sourced some of their code.

**Comment by RyszardRzepa** [comment]
Thanks! 

And great work with the library!
