### ISSUE TITLE
findHomography mask

### ISSUE THREAD

**Issue by pchmelar** [justadudewhohacks/opencv4nodejs#238]
Hi,
I'm trying to retrieve an output mask from findHomography(), but it is always empty. What is the correct way? Is it possible or do we have to modify calib3d module?
```
let mask = new cv.Mat();   
cv.findHomography(matched1, matched2, { method: cv.RANSAC, ransacReprojThreshold: 5, mask: mask });
```

**Comment by justadudewhohacks** [comment]
Are you using atleast 4 matches? I think findHomography needs atleast 4 srcPoints and 4 dstPoints, otherwise return an empty result.

**Comment by pchmelar** [comment]
Yes, I have way over 4 matches. 
The method correctly returns a homography matrix, but the optional output mask is empty (parameter "mask") in my nodejs implementation.  
The output mask is there (in calib3d.cc). But it is not set to a matrix passed into the method as "mask" parameter. Or am I doing something wrong?

```
FF_OBJ jsMat = FF_NEW_INSTANCE(Mat::constructor);
FF_UNWRAP_MAT_AND_GET(jsMat) = cv::findHomography(srcPoints, dstPoints, method, ransacReprojThreshold, mask, maxIters, confidence);
// mask non empty here
FF_RETURN(jsMat);
```

**Comment by justadudewhohacks** [comment]
Ahh, sorry didn't get that you are talking about the mask here. Actually, I am not sure, why it is not setting the mask correctly.

Looking at the implementation of the binding I think it would be better to not accept the mask as an argument to the function call, but rather returning it, as it is an OutputArray, looking at the opencv docs. But that shouldn't be the source of the issue.
