### ISSUE TITLE
integral support

### ISSUE THREAD

**Issue by asilvas** [justadudewhohacks/opencv4nodejs#240]
https://docs.opencv.org/master/d7/d1b/group__imgproc__misc.html#ga97b87bec26908237e8ba0f6e96d23e28

`const sum = mat.integral([sqsum][,tilted])` would help a ton!

**Comment by justadudewhohacks** [comment]
`mat.integral` is available in version 4.1.0 now.

**Comment by asilvas** [comment]
Sweet thanks, almost identical to the code I had running locally.
