### ISSUE TITLE
`nan` should be in `dependencies`

### ISSUE THREAD

**Issue by vjpr** [justadudewhohacks/opencv4nodejs#25]
As it is used in `binding.gyp`.

This breaks when using [pnpm](https://github.com/pnpm/pnpm) package manager.

**Comment by justadudewhohacks** [comment]
Ohh that's not good. Does this package manager not install peer dependencies? Nan is a dependency of macro-inferno. However, I will include it, since I am planning to replace the macro lib anyways.
