### ISSUE TITLE
How do i combine multiple images into one wider image?

### ISSUE THREAD

**Issue by abkava** [justadudewhohacks/opencv4nodejs#253]
as setRoi() not supported yet, i have used copyTo method but actually not found any reference how can i copy image from source to target by defining x and y

**Comment by abkava** [comment]
i want to combine images of 150 X 150 into one wider image, below is my code but at the end of loop all i got is a wide black empty image. here "similarFaces" is my array of matrix.
```javascript
  let sideBySide = new cv.Mat(150, 150 * (similarFaces.length), cv.CV_8UC3); // created wider image row
    similarFaces.forEach((image, i) => {
      let mat = image.matrix;
      const y = 0;

      const x = i * 150; 
      mat.copyTo(sideBySide.getRegion(new cv.Rect(x, y, 150, 150)));
    })
    const name = frame;
    const targetPath = `${dirTraining }/${name}.jpg`;
    cv.imwrite(targetPath, sideBySide);
```

**Comment by justadudewhohacks** [comment]
Hmm works fine for me. Are you sure all face images are 150x150 and of type cv.CV_8UC3? Maybe they are grey images (cv.CV_8U).

**Comment by abkava** [comment]
issue was as you have described i was combining gray images which type was different from cv.CV_8U, thank u
