### ISSUE TITLE
Installation issues on Win10 with npm Auto Install

### ISSUE THREAD

**Issue by DennisSSDev** [justadudewhohacks/opencv4nodejs#254]
[The auto install section](https://github.com/justadudewhohacks/opencv4nodejs#auto-build) does not mention that in order for opencv4nodejs to work you have to include opencv .dll files into the release folder yourself (...\node_modules\opencv4nodejs\build\Release). 

`$ npm install --save opencv4nodejs` did not auto install the necessary opencv files and the docs do not mention the required install. 

Note: certain machines were able to install the opencv4nodejs without issues (cmake is present regardless). But it's unclear why others had trouble linking the opencv modules. Tested running in admin/none-admin modes, but can't replicate the issue. My closest lead is it has something to do with the directory where the node_modules have been attempted to be installed.

![issue](https://user-images.githubusercontent.com/26827854/38755399-91c6be5a-3f33-11e8-9077-b29cc779d941.JPG)

**Comment by justadudewhohacks** [comment]
Hey,

That actually shouldn't be required. I guess on the machines where it didn't work you got an dlopen Error requiring the module, right? Once you require the package and have set `OPENCV4NODEJS_DISABLE_AUTOBUILD` it will add the binary path to the environment path of the node process. My guess why it might have failed on some systems is, that the env is not set or you have other OpenCV binaries in your system path.
