### ISSUE TITLE
Classifier doesn't return the correct output in webcamFaceDetectionGpu.js

### ISSUE THREAD

**Issue by DennisSSDev** [justadudewhohacks/opencv4nodejs#255]
Issues found in: [webcamFaceDetectionGpu.js](https://github.com/justadudewhohacks/opencv4nodejs/blob/master/examples/faceDetect/webcamFaceDetectionGpu.js) and [videoFaceDetectionGpu.js](https://github.com/justadudewhohacks/opencv4nodejs/blob/master/examples/faceDetect/webcamFaceDetectionGpu.js)

Currently on line **21**: `return classifier.detectMultiScaleGpu(img.bgrToGray(), options);` the output will return **null**. It should instead return the `.objects` property. Thus, the face detection doesn't work properly.

By adding: `return classifier.detectMultiScaleGpu(img.bgrToGray(), options).objects;` it will give the correct face recognition.

This issue is also present in: `videoFaceDetectionGpu.js` on line **20**.

**Comment by justadudewhohacks** [comment]
Right, thanks for the fix!
