### ISSUE TITLE
LNK1181 Error on AutoBuild

### ISSUE THREAD

**Issue by DanielLeeJM** [justadudewhohacks/opencv4nodejs#257]
Hey, I've been using this module as part of a larger project, but it seems like there's an error when doing the autobuild.

This is the error.
------------------
Done Building Project "C:\Users\Daniel\data_integ\app\node_modules\opencv-build\opencv\build\modules\ximgproc\opencv_xi
mgproc.vcxproj.metaproj" (default targets).

Done Building Project "C:\Users\Daniel\data_integ\app\node_modules\opencv-build\opencv\build\ALL_BUILD.vcxproj.metaproj
" (default targets) -- FAILED.

Done Building Project "C:\Users\Daniel\data_integ\app\node_modules\opencv-build\opencv\build\OpenCV.sln" (default targe
ts) -- FAILED.

Build FAILED.

"C:\Users\Daniel\data_integ\app\node_modules\opencv-build\opencv\build\OpenCV.sln" (default target) (1) ->
"C:\Users\Daniel\data_integ\app\node_modules\opencv-build\opencv\build\ALL_BUILD.vcxproj.metaproj" (default target) (2)
 ->
"C:\Users\Daniel\data_integ\app\node_modules\opencv-build\opencv\build\modules\hdf\opencv_hdf.vcxproj.metaproj" (defaul
t target) (78) ->
"C:\Users\Daniel\data_integ\app\node_modules\opencv-build\opencv\build\modules\hdf\opencv_hdf.vcxproj" (default target)
 (79) ->
(ClCompile target) ->
  c:\program files (x86)\microsoft visual studio\2017\buildtools\vc\tools\msvc\14.13.26128\include\xmemory0(919): warni
ng C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [C:\Users\Daniel\data_integ\app\node
_modules\opencv-build\opencv\build\modules\hdf\opencv_hdf.vcxproj]

"C:\Users\Daniel\data_integ\app\node_modules\opencv-build\opencv\build\OpenCV.sln" (default target) (1) ->
"C:\Users\Daniel\data_integ\app\node_modules\opencv-build\opencv\build\ALL_BUILD.vcxproj.metaproj" (default target) (2)
 ->
"C:\Users\Daniel\data_integ\app\node_modules\opencv-build\opencv\build\modules\viz\opencv_viz.vcxproj.metaproj" (defaul
t target) (86) ->
"C:\Users\Daniel\data_integ\app\node_modules\opencv-build\opencv\build\modules\viz\opencv_viz.vcxproj" (default target)
 (87) ->
(Link target) ->
  LINK : fatal error LNK1181: cannot open input file 'C:\Program Files\Microsoft SDKs\Windows\v6.0A\Lib\x64\d3d9.lib' [
C:\Users\Daniel\data_integ\app\node_modules\opencv-build\opencv\build\modules\viz\opencv_viz.vcxproj]

    1 Warning(s)
    1 Error(s)

Time Elapsed 00:05:41.05
ERR! child process exited with code 1
npm WARN kyc@1.0.0 No description
npm WARN kyc@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv-build@0.0.11 install: `node ./install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv-build@0.0.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Daniel\AppData\Roaming\npm-cache\_logs\2018-04-15T08_08_59_126Z-debug.log

----------------------------

Any Suggestions? I did the windows-build-tools --vs2017

**Comment by justadudewhohacks** [comment]
Hmm looks like OpenCV wants to build the viz module probably because cmake detected a VTK installation on your system, but there seems to be some dependency missing.

Viz is not supported by opencv4nodejs anyways so we might want to also explicitly disable it via cmake flag WITH_VTK=OFF.

**Comment by justadudewhohacks** [comment]
By the way, I disabled vtk in opencv-build@0.0.12, in case you want to try it again.
