### ISSUE TITLE
calcHistory 3D

### ISSUE THREAD

**Issue by asilvas** [justadudewhohacks/opencv4nodejs#259]
The following example is not working. Am I missing something?

The source image is confirmed to have 3 channels. The min/max data is also verified valid.

```
const channels = image.split();
const { minVal: minL, maxVal: maxL } = channels[0].minMaxLoc();
const { minVal: minA, maxVal: maxA } = channels[1].minMaxLoc();
const { minVal: minB, maxVal: maxB } = channels[2].minMaxLoc();
const hist = cv.calcHist(image, [
      { channel: 0, bins: 8, ranges: [minL, maxL] },
      { channel: 1, bins: 8, ranges: [minA, maxA] },
      { channel: 2, bins: 8, ranges: [minB, maxB] }
    ]);
```

It isn't blowing up, but the `hist` Mat returned is of size `-1, -1`. If I remove the 3rd dimension, it will return a valid 2d matrix.

**Comment by justadudewhohacks** [comment]
Hi, 

In OpenCV every Mat that has more then 2 dimensions, it doesn't work with rows and cols. The dimensions should be available in `mat.sizes` or does that one also return -1?

**Comment by asilvas** [comment]
Ah, yes, `sizes` is `[8, 8, 8]`. But how do I access the histo data? All the get functions, ala `getDataAsArray`, return nothing.

**Comment by justadudewhohacks** [comment]
That's a good question. I think right now it's not possible to access data from a Mat with more then 2 dimensions from this package. In C++ one would probably do this as pointed out in this [stackoverflow post](https://stackoverflow.com/questions/8809517/multi-dimensional-data-in-a-matrix-in-opencv-with-c)

**Comment by asilvas** [comment]
I've been pulling the histogram data via the new `at(y, x, z)` Vec3 function, assuming the data was correct, but now I'm finding it differs vastly from the python comparison using exact same inputs. At first I thought it was just some slight calc rounding errors, but it's very dramatic, with the node version returning mostly 0's. I've been spending some time on the C code trying to debug what's going on, but it's been over 10 years since I actively wrote C so it's pretty slow going. Anything obvious you can think of?

```
// 1D works great, identical to python code
cv.calcHist(image, [{ channel: 0, bins: 8, ranges: [minL, maxL] }]);
// 1D works great, identical to python code
cv.calcHist(image, [{ channel: 1, bins: 8, ranges: [minA, maxA] }]);
// 1D works great, identical to python code
cv.calcHist(image, [{ channel: 2, bins: 8, ranges: [minB, maxB] }]);
// 2D works great, identical to python code
cv.calcHist(image, [
  { channel: 0, bins: 8, ranges: [minL, maxL] },
  { channel: 1, bins: 8, ranges: [minA, maxA] }
]);

// !!! 3D produces vastly different results (though size & shape are identical -- `8x8x8`)
cv.calcHist(image, [
  { channel: 0, bins: 8, ranges: [minL, maxL] },
  { channel: 1, bins: 8, ranges: [minA, maxA] },
  { channel: 2, bins: 8, ranges: [minB, maxB] }
]);
```

It's not clear if fixing `getDataAsArray` to support 3D matrices would alleviate the issue.

**Comment by asilvas** [comment]
I've identified the culprits, and will create a PR soon to permit 3D mat's.

**Comment by asilvas** [comment]
will close once published.

**Comment by justadudewhohacks** [comment]
Will publish later today, just want to adjust some links in the readme after setting up github pages to get this into the next npm release.

**Comment by rainabba** [comment]
Is this effectively doing a CLACHE equalization ( https://docs.opencv.org/3.2.0/d5/daf/tutorial_py_histogram_equalization.html ) ?

I've been struggling with the following, and I wonder if this isn't what I need to effectively do the same. If anyone has a moment and a thought on this, I'd gladly hear it.

https://github.com/justadudewhohacks/opencv4nodejs/issues/411
