### ISSUE TITLE
Fastest Way to Modify an Mat?

### ISSUE THREAD

**Issue by codyseibert** [justadudewhohacks/opencv4nodejs#260]
So, in my code I need to loop over each pixel and apply a function to the pixel if it is over a certain threshold.  I have tried a couple of things:

- The first thing I tried was image.getDataAsArray(), then I'd modify the 2d array, and return a new cv.Mat(arr).  This was pretty slow. 

- The second things I tried instead using image.at(i, j) and image.set(i, j, value) inside of a double for loop which was a bit faster, but since I doing a function call thousands of times in the loops, it is still not that great.

- I have tried doing image.getData and modifying the buffer, but it seems like that might return a copy of the buffer and not the one created in the c++ code...  I guess I could always just return a new cv.Mat(buffer, rows, col) if there isn't a way to actually modify the underlying buffer / arrays.

I was wondering what the fastest way for modifying and applying a function to a Mat might be?

**Comment by rainabba** [comment]
@codyseibert  I'm going through the same process now. Did you find another approach?  [Here's](https://github.com/justadudewhohacks/opencv4nodejs/issues/329#issuecomment-418434602) where I am now and it's faster, but I'm stuck getting back to a Mat so I'd appreciate any tips you have.
