### ISSUE TITLE
how to save images?

### ISSUE THREAD

**Issue by woojoo666** [justadudewhohacks/opencv4nodejs#263]
I am trying to save the image generated by `matchFeatures.js`. In python there is the `imshow` function but I noticed that wasn't included here. In addition, it seems like the image is in matrix form not binary so fs.writeFile` gives me a black image. How do I save the resulting image?

**Comment by woojoo666** [comment]
do you by any chance know how to turn binary image data into a matrix (aka the opposite of what I was trying to do before)

**Comment by justadudewhohacks** [comment]
How does your binary data look like? If it's a node buffer, there is a constructor: `new cv.Mat(rows, cols, type, buffer)`.

**Comment by woojoo666** [comment]
what type does Mat usually use when reading jpg files?

**Comment by justadudewhohacks** [comment]
Hold on. If you simply want to read images from common codecs like jpg, png etc. you would simply use `const mat = cv.imread(filepath)`.

**Comment by woojoo666** [comment]
I'm getting jpg data from a server so I'd ideally like to convert it directly into a Mat if possible. I'm just not sure if there are any ways if going directly from jpg data to Mat

**Comment by justadudewhohacks** [comment]
Yes it is possible. You can use `cv.imdecode` for that, which accepts a node buffer. You just have to be careful with encoding, in case you retreive the jpg data as a string. For example in case you get base64 strings from the server, you can retrieve a Mat like this: `const mat = cv.imdecode(Buffer.from(data, 'base64))`

**Comment by woojoo666** [comment]
that worked for me. Thanks for all your help!
