### ISSUE TITLE
npm test

### ISSUE THREAD

**Issue by asilvas** [justadudewhohacks/opencv4nodejs#265]
Would be helpful to have the `test` script for those submitting PR's to prevent the need for manual testing and/or travis ci.

**Comment by justadudewhohacks** [comment]
The test scripts are located under /tests or what do you mean?

**Comment by asilvas** [comment]
Being able to run `npm test` is standard nodejs convention for testing a package. If there is reason for this not working, it'd be helpful to include the special instructions in the readme (or somewhere).

**Comment by asilvas** [comment]
Oh my bad, I see what you mean, you included `test` folder as it's own installed thing. Cool, that works!
