### ISSUE TITLE
npm readme

### ISSUE THREAD

**Issue by asilvas** [justadudewhohacks/opencv4nodejs#266]
Readme not showing up on npm.org -- nothing obviously wrong from your package.json, but perhaps this line `git+` might be confusing it: https://github.com/justadudewhohacks/opencv4nodejs/blob/master/package.json#L23

**Comment by justadudewhohacks** [comment]
Hmm strange, this morning the readme was still visible on npm, not sure what's going on.

**Comment by asilvas** [comment]
ok will close if it's just an npm fluke.
