### ISSUE TITLE
Mat.mean() returning empty Mat

### ISSUE THREAD

**Issue by fakob** [justadudewhohacks/opencv4nodejs#267]
Hi

When running `console.log(mat.mean());` it returns an empty Mat
```
Mat {
  step: 0,
  elemSize: 0,
  sizes: [],
  empty: true,
  depth: 0,
  dims: 0,
  channels: 1,
  type: 0,
  cols: 0,
  rows: 0 }
```
I was expecting a scalar value. Am I doing anything wrong here? How else would I get the mean value?

**Comment by justadudewhohacks** [comment]
True, right now it returns an empty Mat, it should return a scalar or vector instead. Will fix this with next release.

**Comment by fakob** [comment]
Cool, thanks. Sorry that I cannot help out there, as I had no clue when I was looking at the code trying to understand whats going on :-)

**Comment by justadudewhohacks** [comment]
Fixed mat.mean() with version 4.4.0.

**Comment by fakob** [comment]
That is fantastic. Thanks @justadudewhohacks!
