### ISSUE TITLE
Relocating error at runtime after successful build

### ISSUE THREAD

**Issue by RobinBressan** [justadudewhohacks/opencv4nodejs#268]
Hi,

I'm trying to use the lib inside a docker but it fails each time by throwing an error which looks like this:
```
error: uncaughtException: Error relocating /xxxx/opencv4nodejs/build/Release/opencv4nodejs.node: _ZTIN2cv12MatAllocatorE: symbol not found
```

I can't have a regular setup through a package.json, because I want the build to be inside a Docker container.
Therefore I've tried many strategies like installing it globally into the container, building it from the git and then linking it and so on. But each time it fails with the previous error.

At the runtime, my code runs into the same docker.

Do you have any clues on this? My first idea would be that the node-gyp doesn't like to not be called from an other folder than my node_modules.

Best regards

**Comment by RobinBressan** [comment]
Hi,

I'm using node:9.5.0-alpine. But I've tried with yours too, it ends up the same way.

**Comment by SkeLLLa** [comment]
Yeah, I'm currently working on fixing it in alpine. For now, you can try stretch or ubuntu builds.

**Comment by SkeLLLa** [comment]
@RobinBressan It seems that docker manages to break ld linking when an image is built from different images. I've managed to build alpine docker image that works, but it's too big for now. I'll try to find out the cause in a few days.

**Comment by RobinBressan** [comment]
Great! Thanks for your work. Looking forward to getting the links.

**Comment by SkeLLLa** [comment]
@RobinBressan 
Try these:
https://hub.docker.com/r/m03geek/ffmpeg-opencv-node/
https://hub.docker.com/r/m03geek/opencv-node/

I haven't checked it in depth, but seems they're working with my example.
Later I'll push other images with dlib.

**Comment by SkeLLLa** [comment]
@RobinBressan 
UPD: All docker images were rebuilt. So you can try any of images that you can find in readme under "Other images" section. Images like ffmpeg-* I've tested on my own example, so they should definitely work.
