### ISSUE TITLE
question: is there a way for extract a unique id from face?

### ISSUE THREAD

**Issue by publicocean0** [justadudewhohacks/opencv4nodejs#283]
Suppossing i have 100.000 faces. It is a problem to load a array with all faces for executing the neural training. I there a way for extract a model (a set of parameter) describing a face in unique way?
If i have a model ... i could reduce it to a hash. When i have a new face ... the process generate a model ... , so a hash, and then i can load just faces with same hash.

**Comment by publicocean0** [comment]
Uhmm there is another problem ... the faces can be added incrementelly in the database. Maybe it is difficult to load every time all faces.

**Comment by justadudewhohacks** [comment]
So basically you want to improve the model every time you get new data? In case you want to use a neural net, you could simply load your old model and train it with the new data.

**Comment by justadudewhohacks** [comment]
Just for clarification, are you talking about the face recognizers provided by OpenCV or are you using opencv4nodejs with the FaceRecognizer from face-recognition.js? I assumed the latter one.

Anyways if you were talking about the FaceRecognizer from OpenCV then I can't tell you how these will perform with 100.000 faces :D

**Comment by publicocean0** [comment]
... provided by OpenCV ... but i think is complex to handle it in scalable way with NN. 
I found another library using euclidean distance... maybe it is the right way
