### ISSUE TITLE
Its irrelevant question but need help

### ISSUE THREAD

**Issue by komalpharate** [justadudewhohacks/opencv4nodejs#284]
Im using node-opencv
https://github.com/peterbraden/node-opencv
Because it works with JetsonTX2.
And I have the issue 
https://github.com/justadudewhohacks/opencv4nodejs/issues/162
to use opencv4nodejs.
So,
Can I know if in node-opencv package, the function cap.reset() is implemented or not ?
I need to restart the video once EOF is reached.
Thank you

**Comment by justadudewhohacks** [comment]
This is not node-opencv. opencv4nodejs implements cap.reset(, I don't know if node-opencv if that answers your question.
