### ISSUE TITLE
Installed just fine, but how do I run examples

### ISSUE THREAD

**Issue by heaversm** [justadudewhohacks/opencv4nodejs#285]
Sorry - very new to this all - I believe I have everything installed properly, but how do I run one of the examples? The tutorials online provide all the code, but I'm not sure what terminal commands to run to see any output. For example, the tensorflow/caffe examples just says things like:

`If we run the prediction for each image` and `Let’s feed an image with cars into the network and filter the result for detections with the className ‘car’:` but does not provide the code to do so.

Thanks for clarifying.

**Comment by justadudewhohacks** [comment]
All the examples are in the examples folder. `cd` into that directory and run any example `node example.js`. You are familar with nodejs right?
