### ISSUE TITLE
Export the hand gesture detection as a module to be used as a backend for a webapp

### ISSUE THREAD

**Issue by sridharangopal** [justadudewhohacks/opencv4nodejs#287]
Very new to OpenCV and the APIs defined by this project. I have been trying to export the hand gesture detection module (https://medium.com/@muehler.v/simple-hand-gesture-recognition-using-opencv-and-javascript-eb3d6ced28a0) and use it in an app. The idea is to capture picture of the hand gesture through a webcam every 2 sec or so and send it to the backend server that can detect the number of fingers and send it back in the response. For that I am trying to work with your docker image. Trying to mimic what was done for the face detection module. Any ideas or an explanation on how to export the hand gesture example is much appreciated.

**Comment by justadudewhohacks** [comment]
Which face detection module are you referring to, the face detection example with opencv4nodejs and express.js?

What you would have to do is to use the browser API to read webcam images and stream these images via websockets to your nodejs server (I would recommend socket.io here). On the nodejs server you can process the frames, draw the results and send them back to the client via websockets again.

**Comment by sridharangopal** [comment]
Hi, thank you for the reply. I was referring to the hand gesture module in the examples in this project. https://github.com/justadudewhohacks/opencv4nodejs/blob/master/examples/handGestureRecognition0.js
I have been able to grab the pictures I want from the browser using WebRTC. But have not been able to feed it to the above example as it is reading a local MP4 file. The problem looks like the statement "const cap = new cv.VideoCapture(videoFile);" in the utils.js file which exports grabframes is not able to take in a file send from the browser directly. It seems to be looking for a file on the filesystem only. I looked at the documentation and it only has 2 options - one from the filesystem and the other from a device directly. So I am not sure how to feed a camera stream or pictures from WebRTC directly to this backend.
I am looking at your examples for socket.io use as well right now. Maybe there is a way I can implement from those examples.
Thanks again.

**Comment by justadudewhohacks** [comment]
Open is basically done in the constructor here, so I don't think exposing a binding to open is necessary.

As mentioned above, using VideoCapture is not the right approach here. Read the frames in the browser, stream them to a nodejs server and create a Mat from the buffer received (probably using imdecode, if he is using the `getUserMedia` API to read webcam images in the browser, as they are encoded I think).

**Comment by Rutulpatel7077** [comment]
@justadudewhohacks  I love your work man! 
DO you have any example of this issue?
