### ISSUE TITLE
TemplateMatching.ts - FindWaldo

### ISSUE THREAD

**Issue by RenanChagas** [justadudewhohacks/opencv4nodejs#288]
Hello @justadudewhohacks ,

Thank you very much for the tools on your repository is really helping me.

Im trying your TemplateMatching and I know it can draw a rectangle if it finds waldo...but is there anyway of knowing that it couldn't find him ?

Like create an response saying he could not be found 

Thank you very much in advance

**Comment by RenanChagas** [comment]
Actually if I take a picture of something else on the waldo image and compare it cant find.....
It can only find if I compare the findwaldo.jpg with the waldo.jpg

**Comment by justadudewhohacks** [comment]
Hi,

I think you can use the value of the Mat at position x, y returned from minMaxLoc to figure out, whether the object was found. Depending on the matching method you use, a high (or low) value might indicate the probability of the template being matched correctly.

I am not sure, but I think you could also try to scale your template to different sizes, as I think cv.matchTemplates assumes the template and the object in the image to be roughly the same size.

**Comment by RenanChagas** [comment]
Hi @justadudewhohacks , thank you for the reply.

I cropped another part of the findwaldo picture and tried to look for it and draw a rectangle like you did with the waldo but it could never find it right.

No matter the match method (1-5) and using High or low value, it keeps drawing in places different than the cropped image it should be.

Its only worked with the waldo face.

Do you know what could be wrong ?

<img width="215" alt="screen shot 2018-05-10 at 8 53 26 am" src="https://user-images.githubusercontent.com/13058807/39856312-a390c78c-542f-11e8-8847-2c7b23a30211.png">
<img width="377" alt="screen shot 2018-05-10 at 8 53 08 am" src="https://user-images.githubusercontent.com/13058807/39856314-a3b03e00-542f-11e8-863d-39050e5833b6.png">

**Comment by justadudewhohacks** [comment]
Do the image dimensions of the image you cropped out and the size of the template in the original image match? Looks like the rectangle drawn in the image is much bigger then it should be and your template image looks very blurry.

**Comment by RenanChagas** [comment]
I open the image (findwaldo) on their actual size (default mac image preview program) and cropped the image using the mac default commands (cmd + shift+4). Should I cropped using a different method ?

Yeah, the image is appearing much bigger everytime, even though was not supposed to.

**Comment by justadudewhohacks** [comment]
Well, you should make sure that cropping doesn't scale the dimensions of your template up (I am not familar with mac), because your template will get blurry and noisy.

You can also get a region of an image directly from opencv4nodejs:
`
const region = img.getRegion(new cv.Rect(x, y, width, height))
`

**Comment by RenanChagas** [comment]
Thanks for the hint !!
What did you use for cropping the waldo picture for your template? maybe I can do the same to try if i can make it work

**Comment by RenanChagas** [comment]
Can I use any command of the opencv library to make sure it doesnt scale when I use the command: imreadAsync ?

**Comment by justadudewhohacks** [comment]
I didn't implement the example, so I don't really know :D

imread does not do any scaling, it reads the image as is. I think upscaling your template was due to the image cropping process.

**Comment by wbern** [comment]
@RenanChagas Do you intend to find waldo in multiple images? If so I'd highly recommend re-training a classifier via TensorFlow as the fastest alternative to template matching, which really only does a good job of matching identical images that may or may not be skewed/transformed/modified.

If you want a really fast approach without retraining a classifier (important: retraining is different than making a new one altogether!), I would give histograms a try instead, trying to capture waldos distinct and tightly nit red and white colors.

**Comment by RenanChagas** [comment]
Hi @wbern do you have any tutorials about doing this on TensorFlow ?

Thank you in advance

**Comment by wbern** [comment]
Sure thing.

https://medium.com/@linjunghsuan/create-a-simple-image-classifier-using-tensorflow-a7061635984a
https://github.com/VikramTiwari/tensorflow-retrain-samplev
https://becominghuman.ai/transfer-learning-retraining-inception-v3-for-custom-image-classification-2820f653c557v
https://www.tensorflow.org/tutorials/image_retraining
