### ISSUE TITLE
[request] Add opencv kmeans

### ISSUE THREAD

**Issue by SkeLLLa** [justadudewhohacks/opencv4nodejs#289]
Hi. Consider adding kmeans opencv binding.
https://docs.opencv.org/3.1.0/d5/d38/group__core__cluster.html

**Comment by justadudewhohacks** [comment]
Hi.

kmeans is implemented: https://justadudewhohacks.github.io/opencv4nodejs/docs/cv#kmeans

Should work for all different Point, Vec classes and cv.Mat

**Comment by SkeLLLa** [comment]
Oh, thanks. Thought that was something cv.Mat special.
