### ISSUE TITLE
JS build for browser

### ISSUE THREAD

**Issue by rishantagarwal** [justadudewhohacks/opencv4nodejs#292]
Hi, i am trying to build a version of JS for browser using the steps given on openCV site , using opencv_contrib modules, but everytime i do that, lots of modules like fist and orb detetctors do not get exposed, though they are accessible here in your module. Can you help me with how i can do that ?

**Comment by rishantagarwal** [comment]
Any pointers in this direction will be really helpful to me

**Comment by justadudewhohacks** [comment]
Hi,

I think you are confusing something here. This npm package is opencv4nodejs, which has nodejs bindings for OpenCV. What you are referring to is opencv.js, which is a completely different project.

**Comment by rishantagarwal** [comment]
I understand that this lib is for Node version, and i am looking for some pointers for Browser versions. I am trying to export ORB module in browser version, i was able to export the ORB in JS, but since it's an   abstract class, it can't be instantiated and is giving  `unbound` error. 

I see you have implemented the ORB here and so, can you point me how i can do it ?

**Comment by slushnys** [comment]
@rishantagarwal have you figured out how to port this library to the browser? I'm trying to port your library @justadudewhohacks to the browser as well as you implemented the memory management option so that garbage collection would collect it. Any thoughts on how I could do this?

**Comment by rishantagarwal** [comment]
@slushnys I think the recent version of Open CV has support for lot of functions to be turned into Webassembly modules and then to be usable in browsers. Maybe you should look into it. 

https://docs.opencv.org/master/d4/da1/tutorial_js_setup.html
