### ISSUE TITLE
electron-opencv4nodejs cv.HAAR_FRONTALFACE_ALT2 is undefined

### ISSUE THREAD

**Issue by maxucheng0** [justadudewhohacks/opencv4nodejs#294]
`<script>
    const { cv, drawBlueRect } = require('../utils');
    const path = require('path');

    let img = cv.imread(path.resolve('assets', 'test.jpg')).resizeToMax(800);
    //测试
    /*let imgBase64 = cv.imencode('.jpg', img).toString('base64');
    console.log(imgBase64);*/
    renderImage(img, document.getElementById('image'));
    const classifier = new cv.CascadeClassifier(cv.HAAR_FRONTALFACE_ALT2);
    const devicePort = 0;
    const numDetectionsTh = 10;
    const wCap = new cv.VideoCapture(devicePort);
    setInterval(() => {
      let image = wCap.read();
      const { objects, numDetections } = classifier.detectMultiScale(image.bgrToGray());
      objects.forEach((rect, i) => {
        const thickness = numDetections[i] < numDetectionsTh ? 1 : 2;
        drawBlueRect(image, rect, { thickness });
        renderImage(image, document.getElementById('camera'));
      });
    }, 10);
</script>`
<img width="800" alt="qq20180515-170952 2x" src="https://user-images.githubusercontent.com/21236162/40047723-ce3a2294-5862-11e8-8267-f6a804147ca0.png">

**Comment by justadudewhohacks** [comment]
When using webpack the constants that point to files are not defined, as it is not trivial to resolve them when the package is required. You can simply pass in the path to HAAR_FRONTALFACE_ALT2 xml file instead of using the constant.

**Comment by maxucheng0** [comment]
thanks!
