### ISSUE TITLE
no member named 'ForceSet' in 'v8::Object'

### ISSUE THREAD

**Issue by vidaldiego** [justadudewhohacks/opencv4nodejs#295]
Hi! I've just upgraded to node 10 and now I cannot rebuild opencv4nodejs. I got the following error:

In file included from ../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);

Thanks!

**Comment by vidaldiego** [comment]
Apparently there is a problem with library nan. Luckily the problem has already been solved in nan master's branch:
npm uninstall nan
npm install https://github.com/nodejs/nan
npm install opencv4nodejs

**Comment by justadudewhohacks** [comment]
Hm okay, I guess with node 10 we simply wait for the fix in nan to be released.
