### ISSUE TITLE
cvtColor(cv.COLOR_HSV2RGB)

### ISSUE THREAD

**Issue by pabx06** [justadudewhohacks/opencv4nodejs#296]
Hello i ma having trouble converting a filtered  HSV matrix to BGR for display=
My code

NB: red is HUE 0 to 10 and also 170-180

const cv = require('opencv4nodejs');
const IMG_DATA = "../TEST/TEST1.bmp";

// load image from file
const mat = cv.imread(IMG_DATA);
const hsv = mat.cvtColor(cv.COLOR_BGR2HSV);

// 0-10 hue
var min_red1 = new cv.Vec3(0, 100, 80);
var max_red1 = new cv.Vec3(10, 256, 256);
var image_red1 = hsv.inRange( min_red1, max_red1);

// 170-180 hue
var min_red2 = new cv.Vec3(170, 100, 80);
var max_red2 = new cv.Vec3(180, 256, 256);
var image_red2 = hsv.inRange( min_red2, max_red2);

//ADD two red
var image_red = image_red1.add(image_red2);
console.log(image_red);

// show image
var image_red_bgr = image_red.cvtColor(cv.COLOR_HSV2RGB);
cv.imshow('image_red',  image_red_bgr);
cv.waitKey();

![image](https://user-images.githubusercontent.com/4013370/40063211-1cf99230-585d-11e8-8960-7a3cd20052f5.png)

**Comment by pabx06** [comment]
opencv_version.py [<params>]
    params:
        --build: print complete build info
        --help:  print this help


General configuration for OpenCV 3.4.1 =====================================
  Version control:               unknown

  Extra modules:
    Location (extra):            /app/opencv_contrib-3.4.1/modules
    Version control (extra):     unknown

  Platform:
    Timestamp:                   2018-05-14T00:12:24Z
    Host:                        Linux 4.13.0-38-generic x86_64
    CMake:                       3.10.2
    CMake generator:             Unix Makefiles
    CMake build tool:            /usr/bin/make
    Configuration:               Release

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3
      requested:                 SSE3
    Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2 AVX512_SKX
      requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
      SSE4_1 (3 files):          + SSSE3 SSE4_1
      SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
      FP16 (2 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
      AVX (5 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
      AVX2 (9 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
      AVX512_SKX (1 files):      + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2 AVX_512F AVX512_SKX

  C/C++:
    Built as dynamic libs?:      YES
    C++11:                       YES
    C++ Compiler:                /usr/bin/c++  (ver 7.3.0)
    C++ flags (Release):         -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -Wno-implicit-fallthrough -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
    C++ flags (Debug):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -Wno-implicit-fallthrough -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
    C Compiler:                  /usr/bin/cc
    C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-narrowing -Wno-comment -Wno-implicit-fallthrough -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -O3 -DNDEBUG  -DNDEBUG
    C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-narrowing -Wno-comment -Wno-implicit-fallthrough -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -g  -O0 -DDEBUG -D_DEBUG
    Linker flags (Release):      
    Linker flags (Debug):        
    ccache:                      NO
    Precompiled headers:         YES
    Extra dependencies:          dl m pthread rt
    3rdparty dependencies:

  OpenCV modules:
    To be built:                 aruco bgsegm bioinspired calib3d ccalib core datasets dnn dnn_objdetect dpm face features2d flann freetype fuzzy hfs highgui img_hash imgcodecs imgproc java_bindings_generator line_descriptor ml objdetect optflow phase_unwrapping photo plot python2 python3 python_bindings_generator reg rgbd saliency shape stereo stitching structured_light superres surface_matching text tracking ts video videoio videostab xfeatures2d ximgproc xobjdetect xphoto
    Disabled:                    js world
    Disabled by dependency:      -
    Unavailable:                 cnn_3dobj cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev cvv dnn_modern hdf java matlab ovis sfm viz
    Applications:                tests perf_tests examples apps
    Documentation:               NO
    Non-free algorithms:         NO

  GUI: 
    GTK+:                        YES (ver 2.24.32)
      GThread :                  YES (ver 2.56.1)
      GtkGlExt:                  NO
    VTK support:                 NO

  Media I/O: 
    ZLib:                        /usr/lib/x86_64-linux-gnu/libz.so (ver 1.2.11)
    JPEG:                        /usr/lib/x86_64-linux-gnu/libjpeg.so (ver )
    WEBP:                        build (ver encoder: 0x020e)
    PNG:                         /usr/lib/x86_64-linux-gnu/libpng.so (ver 1.6.34)
    TIFF:                        /usr/lib/x86_64-linux-gnu/libtiff.so (ver 42 / 4.0.9)
    JPEG 2000:                   /usr/lib/x86_64-linux-gnu/libjasper.so (ver 1.900.1)
    OpenEXR:                     build (ver 1.7.1)

  Video I/O:
    DC1394:                      NO
    FFMPEG:                      YES
      avcodec:                   YES (ver 57.107.100)
      avformat:                  YES (ver 57.83.100)
      avutil:                    YES (ver 55.78.100)
      swscale:                   YES (ver 4.8.100)
      avresample:                NO
    GStreamer:                   NO
    libv4l/libv4l2:              NO
    v4l/v4l2:                    linux/videodev2.h
    gPhoto2:                     NO

  Parallel framework:            pthreads

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Intel IPP:                   2017.0.3 [2017.0.3]
           at:                   /app/opencv-3.4.1/build/3rdparty/ippicv/ippicv_lnx
    Intel IPP IW:                sources (2017.0.3)
              at:                /app/opencv-3.4.1/build/3rdparty/ippicv/ippiw_lnx
    Lapack:                      NO
    Eigen:                       NO
    Custom HAL:                  NO
    Protobuf:                    build (3.5.1)

  NVIDIA CUDA:                   NO

  OpenCL:                        YES (no extra features)
    Include path:                /app/opencv-3.4.1/3rdparty/include/opencl/1.2
    Link libraries:              Dynamic load

  Python 2:
    Interpreter:                 /usr/bin/python2.7 (ver 2.7.15)
    Libraries:                   /usr/lib/x86_64-linux-gnu/libpython2.7.so (ver 2.7.15rc1)
    numpy:                       /usr/lib/python2.7/dist-packages/numpy/core/include (ver 1.13.3)
    packages path:               lib/python2.7/dist-packages

  Python 3:
    Interpreter:                 /usr/bin/python3 (ver 3.6.5)
    Libraries:                   /usr/lib/x86_64-linux-gnu/libpython3.6m.so (ver 3.6.5)
    numpy:                       /usr/lib/python3/dist-packages/numpy/core/include (ver 1.13.3)
    packages path:               lib/python3.6/dist-packages

  Python (for build):            /usr/bin/python2.7

  Java:                          
    ant:                         NO
    JNI:                         NO
    Java wrappers:               NO
    Java tests:                  NO

  Matlab:                        NO

  Install to:                    /usr/local
-----------------------------------------------------------------

**Comment by pabx06** [comment]
developer@d353ab3a467d:/DATA/src$ npm ls
vision@1.0.0 /DATA/src
`-- opencv4nodejs@4.5.0
  +-- @types/node@10.0.9
  +-- macro-inferno@0.2.1
  | `-- nan@2.10.0 deduped
  +-- nan@2.10.0
  +-- native-node-utils@0.1.2
  | `-- nan@2.10.0 deduped
  `-- opencv-build@0.0.12
    `-- npmlog@4.1.2
      +-- are-we-there-yet@1.1.4
      | +-- delegates@1.0.0
      | `-- readable-stream@2.3.6
      |   +-- core-util-is@1.0.2
      |   +-- inherits@2.0.3
      |   +-- isarray@1.0.0
      |   +-- process-nextick-args@2.0.0
      |   +-- safe-buffer@5.1.2
      |   +-- string_decoder@1.1.1
      |   | `-- safe-buffer@5.1.2 deduped
      |   `-- util-deprecate@1.0.2
      +-- console-control-strings@1.1.0
      +-- gauge@2.7.4
      | +-- aproba@1.2.0
      | +-- console-control-strings@1.1.0 deduped
      | +-- has-unicode@2.0.1
      | +-- object-assign@4.1.1
      | +-- signal-exit@3.0.2
      | +-- string-width@1.0.2
      | | +-- code-point-at@1.1.0
      | | +-- is-fullwidth-code-point@1.0.0
      | | | `-- number-is-nan@1.0.1
      | | `-- strip-ansi@3.0.1 deduped
      | +-- strip-ansi@3.0.1
      | | `-- ansi-regex@2.1.1
      | `-- wide-align@1.1.2
      |   `-- string-width@1.0.2 deduped
      `-- set-blocking@2.0.0

**Comment by justadudewhohacks** [comment]
Hi `image_red` is a single channeled (gray) image since the `inRange` operation returns a single channeled mask. Thus you cannot convert it from RGB to HSV.

**Comment by pabx06** [comment]
Amazing good catch . Thanks. Opencv Error not yet to notch ...
Le mar. 15 mai 2018 à 21:12, justadudewhohacks <notifications@github.com> a
écrit :

**Comment by St1c** [comment]
Why is it that inRange returns single channeled mask, if it accepts vectors 1x3? I would assume, that each channel corresponds to limits set in the min and max vectors.

**Comment by St1c** [comment]
Ok, I think I get it now - inRange doesn't modify the values to match the limits, but rather returns the true/false state for given pixel
