### ISSUE TITLE
Overlaying image Mat onto another Mat problem

### ISSUE THREAD

**Issue by jasonsof** [justadudewhohacks/opencv4nodejs#297]
Hi thank you for this excellent opencv bindings project, I look forward to learning more about object detection with it along with learning node.js

I have for you here a very simple contrived example of what I'm trying to do but failing.  My expectation is that the image `img-out.jpg` would be a 250x250px blue image with a 50x50px white square in the centre.  What I am seeing is only the blue square though.

    const cv = require('opencv4nodejs');

    var large = new cv.Mat(250, 250, cv.CV_8UC3, [255, 0, 0]);
    var small = new cv.Mat(50, 50, cv.CV_8UC1, 255);

    large[[100,150],[100,150]] = small; // obviously this does not work

    cv.imwrite('/Sites/node/face_blur/img-out.jpg', large);

Any help with what is wrong here is appreciated

**Comment by justadudewhohacks** [comment]
You can use getRegion, which basically returns a reference to a region of the Mat, to copy a Mat into another one: 
```
const region = new cv.Rect(x, y, width, height)
small.copyTo(large.getRegion(region))
```

Make sure that region has the same width and height as your `small` Mat and that both of your Mat are of the same type.

**Comment by jasonsof** [comment]
Thank you for the explanation, `copyTo` was exactly what I needed
