### ISSUE TITLE
Could not find cv::reduce equivalent 

### ISSUE THREAD

**Issue by pabx06** [justadudewhohacks/opencv4nodejs#298]
Hello.
I would like to use the fast OpenCV cv:reduce function for the sake of speed instead instead of looping on eatch col and eatch row to compute the sum of pixel for all row and sum of pixel for all column.

Question: is the function missing from this opencv4nodejs binding ?

the fucntion: https://docs.opencv.org/3.4.1/d2/de8/group__core__array.html#ga4b78072a303f29d9031d56e5638da78e

![image](https://user-images.githubusercontent.com/4013370/40123198-f2fa81a0-5925-11e8-8c64-8ef9242e986c.png)

**Comment by justadudewhohacks** [comment]
Yep, it's currently not implemented.

**Comment by nicholasc** [comment]
Looking to implement this. I was thinking we would simply add this to the Mat class? Something along the lines of `const mat = mat.reduce(0, cv.REDUCE_SUM, cv.CV_32F);`

@justadudewhohacks ?

**Comment by justadudewhohacks** [comment]
Yep every method that operates on a Mat should be added as a class method to allow chaining.

**Comment by nicholasc** [comment]
This has been resolved with PR #340 and released in 4.6.0.

Closing.
