### ISSUE TITLE
VideoWriter.release() doesn't wait for VideoWriter.writeAsync(frame) or VideoWriter.writeAsync Promise returns early

### ISSUE THREAD

**Issue by legraphista** [justadudewhohacks/opencv4nodejs#299]
Sample code: 
```js
const cv = require('.');
const {execSync} = require('child_process');
const fs = require('fs');

function check() {
    console.error('size:', fs.statSync('./test.mp4').size);
    try {
        execSync('ffprobe -hide_banner ./test.mp4')
    } catch (e) {
        console.error(e.toString());
    }
}

const w = new cv.VideoWriter('./test.mp4', 0x00000021, 25, new cv.Size(3, 3), true);

(async () => {
    for (let i = 0; i < 100; i++) {
        const frame = new cv.Mat(
            [
                [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
                [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
                [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
            ], cv.CV_8UC3);
        await w.writeAsync(frame);
    }
    await w.release();
    check();
    console.error('checking again in 1 sec');
    setTimeout(() => check(), 1000);
})();

```

**Expected result:** 
both first and second checks to be identical and error free

**Actual result:**
```
$ node test
size: 1565
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f9611802a00] moov atom not found
./test.mp4: Invalid data found when processing input
Error: Command failed: ffprobe -hide_banner ./test.mp4
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f9611802a00] moov atom not found
./test.mp4: Invalid data found when processing input

checking again in 1 sec
size: 4115
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from './test.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.71.100
  Duration: 00:00:04.00, start: 0.000000, bitrate: 8 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 2x2, 4 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
```

**Other info:**
Replacing `await w.writeAsync(frame);` with `w.write(frame);` works as expected.

**OS + Version:** MacOS 10.13.4 (17E202) 
**Affected versions:** `>=3` (tested on 3.0.3, 3.5, 4.1, 4.5)
**OpenCV version:** 3.4.0 (HEAD: `047764f476e429e0ff63f9e23f7ac96f59539356`) 
**OpenCV_contrib:** HEAD: `81ca8dab8697ae6acc5d8bc45f03b6b10f4d7d24`

**Comment by justadudewhohacks** [comment]
Hey,

I think the problem is that by calling an async function binding, you are essentially spawning a new thread. I could imagine that the issue has to something with the event loop, but one would have to dig deeper into the inner workings of AsyncWorkers in nodejs.

But if you are pushing your probe command onto the event loop it works right? `setImmediate(() => check());` instead of `check()`, would this not be a viable solution to your problem?

**Comment by legraphista** [comment]
Yes, if you wait for the new event loop tick (aka stack empties, I/O is done), via `setImmediate`, then everything works as expected.
