### ISSUE TITLE
docs: SimpleBlobDetectorParams missing

### ISSUE THREAD

**Issue by eps1lon** [justadudewhohacks/opencv4nodejs#300]
Clicking on `SimpleBlobDetectorParams` in https://justadudewhohacks.github.io/opencv4nodejs/docs/SimpleBlobDetector#SimpleBlobDetector does not display the typings for those.

For anyone else looking for those: https://github.com/justadudewhohacks/opencv4nodejs/blob/master/lib/typings/SimpleBlobDetectorParams.d.ts

On another note: I did not quite get how to edit the docs. Contributing.md mentions a docs folder but it seems that the gh-pages are auto generated and I couldn't find a script entry for docs rebuild in package.json.

**Comment by justadudewhohacks** [comment]
Oh, the docs for that class is located here: https://justadudewhohacks.github.io/opencv4nodejs/docs/SimpleBlobDetectorParams#SimpleBlobDetectorParams.

Actually clicking on the class names in the docs page does not do anything right now, there are no links behind :D 

The source code for the github.io docs page is located here: https://github.com/justadudewhohacks/opencv4nodejs-github.io/. For each class and function the properties and function bodies are stored as JSON objects in the static/docs folder and then rendered as static pages with gatsby.js.
