### ISSUE TITLE
Not receiving proper errors

### ISSUE THREAD

**Issue by ekuusi** [justadudewhohacks/opencv4nodejs#301]
I'm running a Node.js backend with Express, and have added opencv4nodjs to the mix. It's working fine, but I'm having trouble troubleshooting my code as I'm often not receiving proper error messages. For example, I had the wrong path like so:

cv.imread('../test.jpg') when it should've been cv.imread('./test.jpg'). When the server reached this part of the code, it just stopped executing without providing any error messages. This happens on other occasions too when I have faulty inputs. In these cases it would be very useful to understand what the issues are and not have to resort to trial & error.

Is there something missing in my setup or is it a known thing that error logging is a bit lacking with this package?

**Comment by justadudewhohacks** [comment]
If the error is not handled by OpenCV with a proper error message or a function call eventually runs into a segfault, there is not much you can do about it, other then trying to come up with a custom solution to validate inputs (in your case checking if the file exists).
