### ISSUE TITLE
findContours with cv.RETR_EXTERNAL not working?

### ISSUE THREAD

**Issue by janblumenkamp** [justadudewhohacks/opencv4nodejs#302]
Hello everyone,

I am not sure if I am doing something wrong... I want to detect the boundary box in a drawing. For example this one:
![testcont](https://user-images.githubusercontent.com/5030127/40346683-e24bb2c6-5d9d-11e8-8e91-01fd86b8cc6c.png)

My code looks like this:
```
const sheet = cv.imread('testcont.png').bgrToGray();
const cont = sheet.findContours(cv.RETR_EXTERNAL, cv.CHAIN_APPROX_SIMPLE, new cv.Point2(0, 0));
console.log(cont);
sheet.drawContours(cont, new cv.Vec3(0, 255, 0), -1, 0, new cv.Point2(0, 0), 4, 2, 0);
cv.imwrite('out.png', sheet);
```
The console output is always 
```
[ Contour {
    hierarchy: Vec4 { z: -1, y: -1, x: -1, w: -1 },
    numPoints: 4,
    area: 546840,
    isConvex: true } ]
```
(except the area, it changes) and the drawn contour looks always the same (basically a box with a distance of a few pixel t the border), no matter what the input image looks like. If I pass the cv.RETR_TREE or cv.RETR_LIST arguments, the contours of the line are extracted correctly, but never the boundary box. What am I doing wrong? Why is the boundary box not extracted correctly?

Best,
Jan

**Comment by justadudewhohacks** [comment]
Hi,

I am not too familar with all the contour retrieval modes. But shouldn't you always get all the boundary points with cv.CHAIN_APPROX_SIMPLE and get the bounding box with cv.CHAIN_APPROX_NONE?

**Comment by janblumenkamp** [comment]
I tried both, it did not work. I followed a different approach now, without extracting the contour.
