### ISSUE TITLE
there are not enough methods: isContourConvex and contourArea

### ISSUE THREAD

**Issue by Aserus** [justadudewhohacks/opencv4nodejs#303]
there are no methods:
[isContourConvex()](https://docs.opencv.org/3.4.0/d3/dc0/group__imgproc__shape.html#ga8abf8010377b58cbc16db6734d92941b)
[ContourArea()](https://docs.opencv.org/3.4.0/d3/dc0/group__imgproc__shape.html#ga2c759ed9f497d4a618048a2f56dc97f1)

**Comment by justadudewhohacks** [comment]
These are properties of the Contour class. From the docs:
> Contour = {
numPoints : number ,
area : number ,
isConvex : boolean ,
hierarchy : Vec4
}

**Comment by Aserus** [comment]
Ou. Thanks)

**Comment by Aserus** [comment]
but i need this method for approx

this is a simple on Python
`for cnt in contours:	    
# Simplify contour
	    perimeter = cv2.arcLength(cnt, True)
	    approx = cv2.approxPolyDP(cnt, 0.03 * perimeter, True)
 	    if (len(approx) == 4 and  cv2.isContourConvex(approx) and maxAreaFound < cv2.contourArea(approx) < MAX_COUNTOUR_AREA):
 	     	    maxAreaFound = cv2.contourArea(approx)
 	     	    pageContour = approx`

**Comment by justadudewhohacks** [comment]
Not sure, which one you are missing here:

https://justadudewhohacks.github.io/opencv4nodejs/docs/Contour#Contour
https://justadudewhohacks.github.io/opencv4nodejs/docs/Contour#approxPolyDP
https://justadudewhohacks.github.io/opencv4nodejs/docs/Contour#arcLength

**Comment by Aserus** [comment]
How I can get area from approx?
or how get Contour object from array Point2?

**Comment by justadudewhohacks** [comment]
I see. That's the problem, the approxPolyDP binding should rather return a Contour object instead of an array of Point2.

**Comment by Aserus** [comment]
Yes. It is necessary to return a Contour or there was a function of converting from Point2 to Contour

**Comment by rainabba** [comment]
I think I just hit the same issue. Nothing has been done with this right? I've got good motivation to contribute, but I haven't done much with C++ in 20+ years except read it and I don't have a build environment setup for it. If you were to help me get setup @justadudewhohacks , I'd be willing to do what I can.

Looks like the OP and I are likely using the same example: https://bretahajek.com/2017/01/scanning-documents-photos-opencv/

**Comment by justadudewhohacks** [comment]
The author of this issue fixed with #350 .

**Comment by rainabba** [comment]
Nice. Thank you.

My offer about maintenance was sincere If not realistic enough :)
