### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by partizanos** [justadudewhohacks/opencv4nodejs#307]
Hello I have cmake  3.5.1 and I get a compilation error:
I am using ubuntu and i am runnng `npm i`
`----------------------------------------------------------
~/Desktop/opencv4nodejs(master*) » npm i                             user@user-Lenovo-B51-80

> opencv4nodejs@4.5.0 install /home/user/Desktop/opencv4nodejs
> node-gyp rebuild

make: Entering directory '/home/user/Desktop/opencv4nodejs/build'
  CXX(target) Release/obj.target/opencv4nodejs/cc/opencv4nodejs.o
In file included from ../node_modules/nan/nan.h:192:0,
                 from /home/user/Desktop/opencv4nodejs/node_modules/macro-inferno/src/ff.h:1,
                 from /home/user/Desktop/opencv4nodejs/node_modules/macro-inferno/src/macro-inferno.h:1,
                 from ../cc/macros.h:1,
                 from ../cc/ExternalMemTracking.h:1,
                 from ../cc/opencv4nodejs.cc:2:
../node_modules/nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../node_modules/nan/nan_maybe_43_inl.h:112:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
   return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
               ^
In file included from /home/user/Desktop/opencv4nodejs/node_modules/macro-inferno/src/ff.h:1:0,
                 from /home/user/Desktop/opencv4nodejs/node_modules/macro-inferno/src/macro-inferno.h:1,
                 from ../cc/macros.h:1,
                 from ../cc/ExternalMemTracking.h:1,
                 from ../cc/opencv4nodejs.cc:2:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’:
../node_modules/nan/nan.h:835:60: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, func, argc, argv);
                                                            ^
In file included from ../cc/opencv4nodejs.cc:1:0:
/home/user/.node-gyp/10.2.1/include/node/node.h:172:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/user/.node-gyp/10.2.1/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
In file included from /home/user/Desktop/opencv4nodejs/node_modules/macro-inferno/src/ff.h:1:0,
                 from /home/user/Desktop/opencv4nodejs/node_modules/macro-inferno/src/macro-inferno.h:1,
                 from ../cc/macros.h:1,
                 from ../cc/ExternalMemTracking.h:1,
                 from ../cc/opencv4nodejs.cc:2:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’:
../node_modules/nan/nan.h:850:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, symbol, argc, argv);
                                                              ^
In file included from ../cc/opencv4nodejs.cc:1:0:
/home/user/.node-gyp/10.2.1/include/node/node.h:165:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/user/.node-gyp/10.2.1/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
In file included from /home/user/Desktop/opencv4nodejs/node_modules/macro-inferno/src/ff.h:1:0,
                 from /home/user/Desktop/opencv4nodejs/node_modules/macro-inferno/src/macro-inferno.h:1,
                 from ../cc/macros.h:1,
                 from ../cc/ExternalMemTracking.h:1,
                 from ../cc/opencv4nodejs.cc:2:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’:
../node_modules/nan/nan.h:865:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, method, argc, argv);
                                                              ^
In file included from ../cc/opencv4nodejs.cc:1:0:
/home/user/.node-gyp/10.2.1/include/node/node.h:158:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/user/.node-gyp/10.2.1/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
In file included from /home/user/Desktop/opencv4nodejs/node_modules/macro-inferno/src/ff.h:1:0,
                 from /home/user/Desktop/opencv4nodejs/node_modules/macro-inferno/src/macro-inferno.h:1,
                 from ../cc/macros.h:1,
                 from ../cc/ExternalMemTracking.h:1,
                 from ../cc/opencv4nodejs.cc:2:
../node_modules/nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const’:
../node_modules/nan/nan.h:1479:5: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
     ));
     ^
In file included from ../cc/opencv4nodejs.cc:1:0:
/home/user/.node-gyp/10.2.1/include/node/node.h:172:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/user/.node-gyp/10.2.1/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
In file included from ../cc/CustomMatAllocator.h:11:0,
                 from ../cc/ExternalMemTracking.h:2,
                 from ../cc/opencv4nodejs.cc:2:
../cc/core/Vec.h: In static member function ‘static v8::Local<v8::Array> Vec::packJSVec4Array(std::vector<cv::Vec<double, 4> >)’:
../cc/core/Vec.h:44:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < jsVecs->Length(); i++) {
                     ^
In file included from /home/user/Desktop/opencv4nodejs/node_modules/native-node-utils/src/NativeNodeUtils.h:4:0,
                 from ../cc/macros.h:2,
                 from ../cc/ExternalMemTracking.h:1,
                 from ../cc/opencv4nodejs.cc:2:
/home/user/Desktop/opencv4nodejs/node_modules/native-node-utils/src/ArrayConverters.h: In instantiation of ‘static bool ArrayOfArraysConverterType<Converter, T, CastType>::unwrap(std::vector<std::vector<CastType> >*, v8::Local<v8::Value>) [with Converter = InstanceConverterType<Point3, cv::Point3_<float> >; T = cv::Point3_<double>; CastType = cv::Point3_<float>]’:
/home/user/Desktop/opencv4nodejs/node_modules/native-node-utils/src/AbstractConverter.h:94:51:   required from ‘static bool AbstractConverter<ConverterType, T>::arg(int, T*, Nan::NAN_METHOD_ARGS_TYPE) [with ConverterType = ArrayOfArraysConverterType<InstanceConverterType<Point3, cv::Point3_<float> >, cv::Point3_<double>, cv::Point3_<float> >; T = std::vector<std::vector<cv::Point3_<float> > >; Nan::NAN_METHOD_ARGS_TYPE = const Nan::FunctionCallbackInfo<v8::Value>&]’
../cc/modules/calib3d/calib3dBindings.h:230:73:   required from here
/home/user/Desktop/opencv4nodejs/node_modules/native-node-utils/src/ArrayConverters.h:73:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < jsArr->Length(); i++) {
                     ^
/home/user/Desktop/opencv4nodejs/node_modules/native-node-utils/src/ArrayConverters.h: In instantiation of ‘static bool ArrayOfArraysConverterType<Converter, T, CastType>::unwrap(std::vector<std::vector<CastType> >*, v8::Local<v8::Value>) [with Converter = InstanceConverterType<Point2, cv::Point_<float> >; T = cv::Point_<double>; CastType = cv::Point_<float>]’:
/home/user/Desktop/opencv4nodejs/node_modules/native-node-utils/src/AbstractConverter.h:94:51:   required from ‘static bool AbstractConverter<ConverterType, T>::arg(int, T*, Nan::NAN_METHOD_ARGS_TYPE) [with ConverterType = ArrayOfArraysConverterType<InstanceConverterType<Point2, cv::Point_<float> >, cv::Point_<double>, cv::Point_<float> >; T = std::vector<std::vector<cv::Point_<float> > >; Nan::NAN_METHOD_ARGS_TYPE = const Nan::FunctionCallbackInfo<v8::Value>&]’
../cc/modules/calib3d/calib3dBindings.h:231:73:   required from here
/home/user/Desktop/opencv4nodejs/node_modules/native-node-utils/src/ArrayConverters.h:73:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
opencv4nodejs.target.mk:231: recipe for target 'Release/obj.target/opencv4nodejs/cc/opencv4nodejs.o' failed
make: *** [Release/obj.target/opencv4nodejs/cc/opencv4nodejs.o] Error 1
make: Leaving directory '/home/user/Desktop/opencv4nodejs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.13.0-43-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/Desktop/opencv4nodejs
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv4nodejs@4.5.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv4nodejs@4.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-05-25T02_40_13_469Z-debug.log
` 

Any ideas?

**Comment by justadudewhohacks** [comment]
Probably the nan version has to be adjusted after the release of node 10. For now I would try to npm install the latest release of [nan](https://github.com/nodejs/nan), if you are using node 10.

**Comment by partizanos** [comment]
With which node version are u able to run it ?

**Comment by justadudewhohacks** [comment]
Node 9
