### ISSUE TITLE
require('opencv4nodejs')  error

### ISSUE THREAD

**Issue by 2Drcome333** [justadudewhohacks/opencv4nodejs#309]
OS: windows 7

I have already install:
nodejs
npm
opencv4nodejs  (through npm install --save opencv4nodejs)

but when I require('opencv4nodejs') in WeChat small program IDE
I get:

VM199:1 thirdScriptError 
 sdk uncaught third Error 
 module "pages/face/opencv4nodejs.js" is not defined 
 Error: module "pages/face/opencv4nodejs.js" is not defined
    at require (http://127.0.0.1:59325/appservice/__dev__/WAService.js:18:27142)
    at http://127.0.0.1:59325/appservice/__dev__/WAService.js:18:26997
    at http://127.0.0.1:59325/appservice/pages/face/face.js:5:10
    at require (http://127.0.0.1:59325/appservice/__dev__/WAService.js:18:27248)
    at http://127.0.0.1:59325/appservice/appservice:1026:9
console.error @ VM199:1
(anonymous) @ WAService.js:4
(anonymous) @ WAService.js:4
a @ VM204 appservice:1008
window.onerror @ VM199:1

Any ideas?

Thank you!

**Comment by justadudewhohacks** [comment]
`window.onerror`, are you trying to require opencv4nodejs in the browser/clientside? This won't work as it is a native node module.

**Comment by 2Drcome333** [comment]
I try to require opencv4nodejs in the clientside
Could I get any solutions to solve it?

**Comment by 2Drcome333** [comment]
Thinks

**Comment by wbern** [comment]
> Here are some articles about WeChat Mini Program:
> https://www.techinasia.com/wechat-mini-programs-launch
> https://walkthechat.com/wechat-mini-programs-simple-introduction/
> Official documentation: English | 中文
> 
> From technical perspective, a weapp is based on WeChat App on Android/iOS. There are 2 layers in a weapp: view layer and logical layer. View layer is like HTML and CSS. Logical layer is written in Javascript and runs in an environment that is similar as NodeJS. However, it lacks of many built-in NodeJS modules like http, https, Buffer, path, etc. Instead, WeChat Team provides a built-in library wx with which we can send http requests, login via WeChat, get system info, etc.

Source: https://github.com/Microsoft/ApplicationInsights-node.js/issues/385

Given the information above (severe lack of support, if any, from nodejs-like implementation), opencv4nodejs is by definition not supported in any non-nodejs powered environment, unfortunately.
