### ISSUE TITLE
Template Matching with Multiple Objects

### ISSUE THREAD

**Issue by Doaxan** [justadudewhohacks/opencv4nodejs#311]
Can anybody help me to remake this example under opencv4nodejs?
https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_imgproc/py_template_matching/py_template_matching.html#template-matching-with-multiple-objects

**Comment by Doaxan** [comment]
How to implement threshold?

**Comment by justadudewhohacks** [comment]
I would suggest you to go through the examples first and have a look at the docs page: https://justadudewhohacks.github.io/opencv4nodejs/docs/Mat. If after that you are still stuck, I am happy to help you out answering more precise questions.

**Comment by wbern** [comment]
Closing for now, but as mentioned, 95% of opencv examples online can be re-used for this library online, even if it's in python. Google and you shall find. 👍
