### ISSUE TITLE
Is Write video implemented?

### ISSUE THREAD

**Issue by komalpharate** [justadudewhohacks/opencv4nodejs#312]
Is function from python opencv
`  fileOut.write(frame)` implemented?

**Comment by arjun-kava** [comment]
checkout following link
https://justadudewhohacks.github.io/opencv4nodejs/docs/VideoWriter#write

**Comment by komalpharate** [comment]
Thank you
Where can I get bit more info about the arguments?

**Comment by arjun-kava** [comment]
I think following link might help you to find details of each parameter.
https://docs.opencv.org/3.0-beta/modules/videoio/doc/reading_and_writing_video.html?highlight=videowriter

**Comment by komalpharate** [comment]
Yes will try.
Thank you very much.

**Comment by komalpharate** [comment]
Hi,
Im not able to set Size parameter
I tried doing -
```
var fourccCode = new cv.VideoWriter.fourcc('X','V','I','D');
console.log(fourccCode)

vCap = new cv.VideoCapture("videofile.mp4");

w = vCap.get(3);
h = vCap.get(4);

const out = new cv.VideoWriter( filePath : "./opencvVideo.avi" , fourccCode : fourccCode , fps : 20 , frameSize : (parseInt(w), parseInt(h)) , isColor : boolean = true )

```

**Comment by MattCollins84** [comment]
My guess is you need to detect the end of the video using `frame.empty` (I think), and then stop the interval when it is done.

**Comment by nicholasc** [comment]
I would also suggest replacing the timer with a loop. Something along the lines of: 
```js
while(true) {
  const frame = vCap.read();
  if(frame.empty) break; // no frame means we reached the end of the video
  out.write(frame);
}
