### ISSUE TITLE
RTSP stream combined with CascadeClassifier crashes

### ISSUE THREAD

**Issue by Zeddy-** [justadudewhohacks/opencv4nodejs#313]
Hi, 
im trying to create an app that takes multiple RTSP sources and recognized faces and emotions. It started out great when i was testing with my local webcam. But as soon as i connected another source, which was an IP camera (in the same LAN) over RTSP it started lagging. And eventually throws an error and crashes.

PS C:\opencv4node> node index.js
[ INFO:0] Initialize OpenCL runtime...
[mpeg4 @ 0000011aa0273ae0] Error at MB: 3388
[mpeg4 @ 0000011aa0273160] illegal dc vlc
[mpeg4 @ 0000011aa0273160] Error at MB: 89

I tried to split the processes into pieces, but couldn't figure out how to change the code so that i can examine the frame separately from displaying it.

Here is my very simple example of 2 webcams with rectangle painting around faces:

```
const cv = require('opencv4nodejs');

const devicePort = 0;
const camCap = new cv.VideoCapture(devicePort);
const wCap = new cv.VideoCapture("rtsp://192.168.0.200");
wCap.set(cv.CAP_PROP_FPS, 30);
wCap.set(cv.CAP_FFMPEG, 1);


const classifier = new cv.CascadeClassifier(cv.HAAR_FRONTALFACE_ALT2);


function getFrames(wCap) {
    var frame = wCap.read();

    if (!frame.empty) {
        return frame;
    }
    else {
        wCap.reset();
        frame = wCap.read()
    }
    return frame;
}

async function drawFrame(cv, wCap, name, frame) {
    let done2 = false;
    while (!done2) {
        frame = await getFrames(wCap);

        frame = frame.bgrToGray();
        const faceRects = classifier.detectMultiScale(frame).objects; // line of doom
        if (faceRects) {
            faceRects.map(
                function (x) { frame.drawRectangle(x, cv.Vec(0, 0, 0), 5); }
            );
        }
        cv.imshow(name, frame);
        const key = cv.waitKey(delay);
        if (key > 0) {
            wCap.release();
            done2 = 1;
        }
    }
    wCap.release();
}


const delay = 1;
var frame;
var frame2;
drawFrame(cv, wCap, "RTP", frame);
drawFrame(cv, camCap, "cam", frame2);
```

**Comment by justadudewhohacks** [comment]
Can you log the frame please and `frame.empty`. My guess is that some frames from the stream are simply not read successfully and might be empty.

**Comment by Zeddy-** [comment]
Yeah i didnt handle empty frames
