### ISSUE TITLE
Error: VideoCapture::New - failed to open capture

### ISSUE THREAD

**Issue by MattCollins84** [justadudewhohacks/opencv4nodejs#315]
````javascript
const cap = new cv.VideoCapture('./roadtest1.mp4');
// Error: VideoCapture::New - failed to open capture
````

I get the same results with an RTSP stream as well.

This is on version `4.5.1` (autobuilt) on a fresh Ubuntu install, the only things i've installed are Node `8.11.2` and cmake ([following these instructions](https://askubuntu.com/questions/610291/how-to-install-cmake-3-2-on-ubuntu?answertab=votes#tab-top)).

I have not installed OpenCV independently at all.

I can do things like this, no problem:

````javascript
const img = new cv.Mat();
````

Any ideas?!

**Comment by MattCollins84** [comment]
Repeated this on a second install... exact same hardware, version of software etc...

Any known issues with a NVidia GeForce GTX 1080 Ti?

**Comment by justadudewhohacks** [comment]
`// Error: VideoCapture::New - failed to open capture` usually indicates that the file is not at the specified location, try to specify the path with path.resolve. Another issue could be that you are missing codecs for that file.

With RTSP it probably means, the endpoint is not responding.

**Comment by MattCollins84** [comment]
Sorry, I should have specified.. The RTSP is working fine from multiple different machines... Just these 2 new ones aren't working.

I can try `path.resolve`, however I'm pretty sure that isn't the issue as the script and the file are in the same directory as I'm running it from.

I'm guessing there's no way to get a more detailed error msg?

**Comment by justadudewhohacks** [comment]
As far as I am aware OpenCV does not report this. The error message actually comes from a check in the implementation of the nodejs binding:
``` c++
if (!self->cap.isOpened()) {
  FF_THROW("failed to open capture");
}
```

I can't imagine `cap.isOpened()` returning a wrong value here, but if in doubt you could uncomment the line in [cc/modules/io/VideoCapture.cc](https://github.com/justadudewhohacks/opencv4nodejs/blob/master/cc/modules/io/VideoCapture.cc), recompile the package and try to read frames from the cap. 

Did you check that you have the required videocodecs installed on these systems?

**Comment by MattCollins84** [comment]
I have just installed all the usual codecs and am still not getting anywhere.

I can't imagine that there is an issue with the library, and I am missing some kind of dependency somewhere... but I can't think what it might be

**Comment by MattCollins84** [comment]
Also, I can play the RTSP stream via VLC, which suggests to me that the required codec is ok

**Comment by MattCollins84** [comment]
I got it working... I think the issue was that I built the module without the required dependencies being available (ffmpeg in this instance). It might be useful to mention this in the documentation, I will create a pull request shortly

**Comment by xyx2011** [comment]
hey, @MattCollins84  I'm facing exactly the same problem, could you create a pull request for this issue, to show where to make the change, that would be fantastic. Thank you so much.

**Comment by MattCollins84** [comment]
I didn't make any changes... you need to make sure you have ffmpeg installed too, thats what the issue was for me

**Comment by xyx2011** [comment]
@MattCollins84  thanks!

**Comment by dreambit** [comment]
i have ffmpeg available, but it does not fix the problem(

**Comment by dreambit** [comment]
When i run npm install i can see this output 
```
Video I/O:
--     **DC1394:                      NO**
--     FFMPEG:                      NO
--       avcodec:                   NO
--       avformat:                  NO
--       avutil:                    NO
--       swscale:                   NO
--       avresample:                NO
--     GStreamer:                   NO
--     libv4l/libv4l2:              NO
--     v4l/v4l2:                    linux/videodev2.h
```

**Comment by goulash1971** [comment]
@dreambit - this may sound like a stupid question, but can you run ffmoeg from the terminal (sane session as when you try the nom install?)

**Comment by dreambit** [comment]
@goulash1971  hi
yes, ffmpeg is available.

I solved the problem by using docker, img m03geek/ffmpeg-opencv-dlib-node:alpine

**Comment by chinesebug** [comment]
@dreambit Hey! how do you using that image? I tried put 
```
FROM m03geek/opencv-dlib-node:alpine
RUN apk update && apk add -u --no-cache python make g++
RUN npm i opencv4nodejs
```
in the Dockerfile. But it tells me `Error: Cannot find module '/usr/lib/node_modules/opencv4nodejs'` after. Could you share how did you build it?

**Comment by dreambit** [comment]
Hi
Content of my docker file:

FROM m03geek/ffmpeg-opencv-dlib-node:alpine
RUN apk update && apk add -u --no-cache python make g++ git
WORKDIR /app
COPY package.json /app
RUN npm install
RUN npm install pm2 -g
COPY . /app
CMD ["pm2-runtime", "ecosystem.config.js", "--only", "my-app-name"]

**Comment by bebensiganteng** [comment]
Hi, I'm having a similar issue with this, I've tried the solution given by @dreambit but then I can't install node-canvas.

Could anybody share the npm & docker configuration, please?

Below is mine.

```
FROM justadudewhohacks/opencv-nodejs:node9-opencv3.4.1-contrib
WORKDIR /app
COPY ./package*.json /app/
COPY ./src/ /app/src/
RUN npm install -g nodemon && npm install
CMD ["nodemon", "-L", "./src/server.js"]
```

```
{
  "name": "03",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@tensorflow/tfjs-node": "^1.5.2",
    "axios": "^0.19.2",
    "canvas": "^2.6.1",
    "express": "^4.17.1",
    "face-api.js": "^0.22.1",
    "node-fetch": "^2.6.0",
    "socket.io": "^2.3.0",
    "socket.io-client": "^2.3.0"
  }
}

```
