### ISSUE TITLE
Question - api ...Async vs ...Sync

### ISSUE THREAD

**Issue by jeremychone** [justadudewhohacks/opencv4nodejs#316]
First, I really like this project and I am planning to use it for a big video machine learning project in the medical space.

However, a detail that somehow bother me is how the default API names are the blocking/sync ones while the async are suffixed with ...Async. Usually, apis that offers both have the default name being the Async version the sync with the suffix ...Sync

It seems to be a silly detail, but developers tends to use the default names, and in our case we always favor the use async/await api when available.

But perhaps there is a good usage reason why the default method names are the Sync one? Is there any downside to use the async version with await for all those calls?

**Comment by justadudewhohacks** [comment]
I agree with you, it's more common to have async functions to be the default ones in JS libraries. But there are some reasons for the opposite design of the opencv4nodejs API:

1. Initially there was no async API, so and once I decided to provide an async API as well, they have been added gradually.
2. Simplicity. There is no async OpenCV API for python and c++. I don't want people that come from OpenCV python or c++ or even people that are new to JS and OpenCV having to bother about Callbacks, Promises or async await when they just get started with the package.
3. (Biggest reason) Quite some operations shouldn't necessarely be performed async (although the API allows you to do so if desired) as they are executing ridiculously fast in nodejs. Also keep in mind, that every async operation spawns a new async worker (thread), so it might not always be worth spawning a new thread, especially for lightweight ops.

**Comment by jeremychone** [comment]
@justadudewhohacks Thanks for the answer. 

I was suspecting 3), so it makes sense. There is definitely a cost to making things async/libuv. 

So all API calls are directly calling the opencv, right? There are no batching of any sort, correct?

**Comment by justadudewhohacks** [comment]
Correct, every call is directly made to the OpenCV API, so performancewise you can expect the same as with c++ or python, if that was the question.

**Comment by jeremychone** [comment]
@justadudewhohacks Thanks a lot, very helpful. 

The context of the question was to compare it with the "node sharp" approach of wrapping C/C++ lib by batching the api commands until toBuffer or save are ran. Not saying node opencv should be like that, but I just wanted to confirm my assumptions. 

Anyway, great work I am sold and will be giving your lib a try. Thanks a lot for the answer, greatly appreciated. We can definitely close this issue.

**Comment by justadudewhohacks** [comment]
Sound like an interesting approach, I haven't heard of node sharp before. But as far as opencv4nodejs is concerned, there is no kind of batching of commands.

**Comment by jeremychone** [comment]
yes, I think you are right, in OpenCV binding it might not make sense. node sharp (https://github.com/lovell/sharp) and libvips are very good and fast, and scale very well (they pool by core and all), but definitely more limited. 

It's great that opencv4nodejs  takes a simpler approach and focus on exposing opencv.
