### ISSUE TITLE
fastNlMeansDenoisingColored kills Node without error when ran

### ISSUE THREAD

**Issue by Tom-Hudson** [justadudewhohacks/opencv4nodejs#317]
When attempting to run fastNlMeansDenoisingColored(imageMat), my node process is killed and I cannot see any errors.

Is this an async method or am I doing something wrong?

**Comment by justadudewhohacks** [comment]
Can you provide some example code? It should work just fine. It's a synchronous method.

**Comment by Tom-Hudson** [comment]
My bad. It was something I had wrote that killed the Node process. Just co-incidence that line of code was about to be hit when it was happening. I'll close now.
