### ISSUE TITLE
"Error: VideoCapture::New - failed to open capture" on raspberry pi

### ISSUE THREAD

**Issue by JeremyKirkham** [justadudewhohacks/opencv4nodejs#318]
I've added the opencv4nodejs library to my raspberry pi package, I'm trying to access the picam 2 video camera. The script I'm running is as following:

```
import * as cv from 'opencv4nodejs'

async function main() {
  const wCap = new cv.VideoCapture(0);
  const intvl = setInterval(() => {
    let frame = wCap.read();
    // loop back to start on end of stream reached
    if (frame.empty) {
      wCap.reset();
      frame = wCap.read();
    }
    console.log(frame);
  }, 0);
}

main()
```

FWIW, I'm running this inside docker on a raspberry pi 3b+, using resin.io to deploy the images.

**Comment by justadudewhohacks** [comment]
Hm, maybe it's better to ask this in the OpenCV forum/repo, since this seems not to be related to opencv4nodejs itself.

**Comment by JeremyKirkham** [comment]
Thanks, have opened on OpenCV.

**Comment by alcalawil** [comment]
`sudo modprobe bcm2835-v4l2` worked for me
