### ISSUE TITLE
cv.Vec4 constructor documentation mismatch

### ISSUE THREAD

**Issue by skenqbx** [justadudewhohacks/opencv4nodejs#319]
opencv4nodejs: v4.5.1
opencv: v3.4.1

The documentation for `cv.Vec` states

```
constructor ( x : number , y : number )
constructor ( x : number , y : number , z : number )
constructor ( x : number , y : number , z : number , w : number )
```

but the implementation works as follows

```
const vec = new cv.Vec4(1, 2, 3, 4);
console.log(vec); // Vec4 { z: 4, y: 3, x: 2, w: 1 }
```
Calling the constructor without arguments yields `Error: Vec::New - expected arguments (w), x, y, (z)`,
which seems to proof the implementation right.

This is confusing and I would think the code should follow the documentation for logical reasons.

Cheers & Thank you for this module!

**Comment by justadudewhohacks** [comment]
You are right, it has to be: `constructor (w : number, x : number , y : number , z : number  )`. Thanks for reporting!

**Comment by justadudewhohacks** [comment]
fixed
