### ISSUE TITLE
Use Point3 instead of Point2 as function argument

### ISSUE THREAD

**Issue by skenqbx** [justadudewhohacks/opencv4nodejs#321]
Is it possible to allow passing a `cv.Point3` instance to e.g. `drawCircle()`?

The _z-axis_ would simply be ignored for this operation.

Use-Case: To consistently use arrays of points and still have a reference to related points I store an array index as `z` value. This allows me to re-organize & filter the points without loosing information.
This is arguably syntactic sugar, as `new cv.Point2(point3.x, point3.y)` works just fine.

**Comment by justadudewhohacks** [comment]
In theory possible sure, but this would also be the case for every other single method, that accepts Point2s. For the sake of consistency one would have to change all the other bindings as well, so not sure if that's worth it. Does OpenCV handle it the way you describe?

**Comment by skenqbx** [comment]
No, it does not. Nevermind.
