### ISSUE TITLE
Error thrown when using decomposeHomographyMatAsync

### ISSUE THREAD

**Issue by Tom-Hudson** [justadudewhohacks/opencv4nodejs#322]
I am looking to get a homography decomp but I can't seem to get it without it throwing an error.

I currently have something like this (assume img1, img2, keyPoints1 & keyPoints2 are all correct):
```
const homography = cv.findHomography(keyPoints1, keyPoints2);

const decomp = await img1.decomposeHomographyMatAsync(homography.homography);
```

Using `warpPerspectiveAsync`, I can generate the 'warped' image (which validates my request to assume above), but the below error is thrown with calling `decomposeHomographyMatAsync`:
```
const warped = img1.warpPerspectiveAsync(homography.homography);
cv.imshowWait('warped', test);
```

**Error**
```
OpenCV Error: (H.cols == 3 && H.rows == 3) in cv::decomposeHomographyMat, in file ~/homography_decomp.cpp, line 455, status -215
```

Is this a bug or am I doing something wrong

**Comment by justadudewhohacks** [comment]
Hi,

I think it should be `await homography.decomposeHomographyMatAsync(K)`, where `K` is the intrinsic camera matrix. The image itself doesn't have anything to do with the homography matrix, assuming `img1` is an image matrix in your code.

**Comment by Tom-Hudson** [comment]
Thanks @justadudewhohacks - your suggestion worked. my bad!
