### ISSUE TITLE
Failing in the electron builded application

### ISSUE THREAD

**Issue by Gektor40k** [justadudewhohacks/opencv4nodejs#325]
Hello @justadudewhohacks! 
I have a problem, and i think its probably easy to solve, but I can not solve it. =( 
I tried to build a test application that uses opencv4nodejs according to the instructions.
And it's succeful builded, but when I try to run it, I get the following error:
![image](https://user-images.githubusercontent.com/34543701/41191635-3607d56e-6bfb-11e8-9911-fd9152ead20f.png)
I googled this error, but I did not find a working answer, maybe you know how to fix the version problem? npm rebuild does not help for me(
My package.json is: 
{
  "name": "opencvtest",
  "version": "1.0.0",
  "description": "",
  "main": "./index.js",
  "dependencies": {
    "fs": "latest",
    "opencv4nodejs": "2.38.0"
  },
  "cmake-js": {
    "runtime": "electron",
    "runtimeVersion": "1.6.11"
  },
  "scripts": {
    "start": "electron .",
    "build": "electron-packager . opencvtest --platform=win32 --arch=x64 --electron-version=1.6.11 --app-version=1.0.0 --out=dist --ignore=dist --prune",
    "electron-rebuild": "electron-rebuild -w opencv4nodejs"
  },
  "author": "me",
  "license": "ISC"
}
so - my steps after npm install (along with electron-rebuild, electron-prebuilt and electron-packager):
1) npm run electron-rebuild
2) npm run start (testing, and this working)
3) npm run build (building, and then a have a error with wrong versions)

Do you have any ideas about that?
Thank you for your time ;)

**Comment by Gektor40k** [comment]
the problem was solved, it was necessary simply to explicitly write certain versions of the electron in the package.json.
{
  "name": "opencvtest",
  "version": "1.0.0",
  "description": "",
  "main": "./index.js",
  "dependencies": {
    "electron": "^1.8.2",
    "electron-packager": "^12.1.0",
    "electron-prebuilt": "^1.4.13",
    "electron-rebuild": "^1.7.3",
    "fs": "latest",
    "opencv4nodejs": "2.38.0"
  },
  "cmake-js": {
    "runtime": "electron",
    "runtimeVersion": "1.6.11"
  },
  "scripts": {
    "start": "electron .",
    "build": "electron-packager . opencvtest --platform=win32 --arch=x64 --electron-version=1.8.2 --app-version=1.0.0 --out=dist --ignore=dist --prune",
    "electron-rebuild": "electron-rebuild -w opencv4nodejs"
  },
  "author": "me",
  "license": "ISC"
}

 I apologize for this :(
 this issue should be closed

**Comment by justadudewhohacks** [comment]
Awesome! :)
