### ISSUE TITLE
Best way to stream to web page

### ISSUE THREAD

**Issue by MattCollins84** [justadudewhohacks/opencv4nodejs#332]
Hey... another day another use case!

I am wanting to read from a camera, potentially make some changes to the image, and then display it on a web front-end.

At the moment I am capturing the frames from the camera easily enough and encoding them as such:

````javascript
cv.imencode('.jpg', frame.resizeToMax(320))
````

I am using Socket.IO to send to the front-end, and turn this into a base64 string, which I can use to display the image on a canvas. However, it is very slow, and I am hoping there is a better way! Any thoughts?

**Comment by justadudewhohacks** [comment]
Could you measure, which is the slow part in this approach? There is always a Transmission delay between client and server, but i am assuming you know that :D

**Comment by ShankyTiwari** [comment]
Hi @MattCollins84, Did you solve your streaming problem?

Thanks,

**Comment by MattCollins84** [comment]
Closing as there is more info in #346
