### ISSUE TITLE
getRegion() fails when reading image asynchronously 

### ISSUE THREAD

**Issue by bkanaki** [justadudewhohacks/opencv4nodejs#333]
Hello,

Based on your Async examples, I try the following:

```
cv.imreadAsync('./car_face.jpg', (err, img) => {
  if (err) { return console.error(err); }

  console.log('File read...');
  // Get the region of interest
  const roi = img.getRegion(region.x, region.y, region.width, region.height);
  console.log('Cropped the roi...')
  ...
});
```
but this fails with the following error message:

```
Assertion failed: (object->InternalFieldCount() > 0), function Unwrap, file ../../nan/nan_object_wrap.h, line 33.
Abort trap: 6
```

Is there something wrong in my code?

**Comment by justadudewhohacks** [comment]
The error thrown is just confusing and should probably be fixed. The thing is that img.getRegion expects a cv.Rect instead of the coordinates, e.g. `img.getRegion(new.cv.Rect(region.x, region.y, region.width, region.height));`.

**Comment by bkanaki** [comment]
Oops, not sure why I missed that having used it multiple times. But as you suggested, the error message was confusing. Thanks for your feedback.
