### ISSUE TITLE
Check constructor calls to be called with 'new'

### ISSUE THREAD

**Issue by justadudewhohacks** [justadudewhohacks/opencv4nodejs#337]
To avoid error messages such as #336 it would be good to check, whether a constructor has been called with the 'new' keyword and throw an error, which is catchable with a better error message instead. It would probably sufficient to check for `info.IsConstructCall()` in the constructor.

**Comment by nicholasc** [comment]
I know we want to move away from macros as much as possible, in this case, it seems like a proper use. That way, we can check this systematically in every class constructor. 

I'm taking a wild guess here but wouldn't this be more relevant in the macro-inferno lib?

I'm curious to get your take on this.

**Comment by justadudewhohacks** [comment]
I am not generally against macros, if they make sense. I just started out with using macros for everything, which resulted in unmaintainable code, thus I kinda wanted to move away from that.

If you have solution for this issue go ahead, macros allowed ;). You can add it directly in opencv4nodejs I think, I don't want to stuff more things into macro-inferno, which I don't really use anymore.

**Comment by oyyd** [comment]
Just run into this and I think if we don't want more macros, handling this in js might come into consideration. 

As all our classes are upper camel case(if not, they need a fix), we can simply monkey-patch them and throw a user friendly message when these classes are misused. However, it may cause reduced performance especially for those frequently used classes(I'm not sure without benchmark though).

**Comment by justadudewhohacks** [comment]
I think monkey patching is not necessary, Simply checking for `info.IsConstructCall()` and throwing an error should be sufficient.
