### ISSUE TITLE
Take only one photo

### ISSUE THREAD

**Issue by MisaZ10** [justadudewhohacks/opencv4nodejs#344]
Hello, I need take only one photo, how can I do ?

I try
        let frame = vCap.read();
        vCap.reset();
       useFrame(frame);

**Comment by MisaZ10** [comment]
I finaly use 
const vCap = new cv.VideoCapture(config.CAMPORT, 1);

function checkFace() {
        let frame = vCap.read();
	const intvl = setInterval(() => {
	    let otherframe = vCap.read();
	    if (otherframe.empty) {
	      vCap.reset();
	      return clearInterval(intvl);
	    }
	    const key = cv.waitKey(10);
	    done = key !== -1 && key !== 255;
	    if (done) {
	      return clearInterval(intvl);
	    }
  	}, 0);
        return useFrame(frame);
}

**Comment by justadudewhohacks** [comment]
Awesome! I am assuming, you figured out how to do this, if not feel free to reopen.
