### ISSUE TITLE
Lib dir does not exist when manually building through windows 10

### ISSUE THREAD

**Issue by jamesvoong** [justadudewhohacks/opencv4nodejs#345]
Hi,

I am currently trying to manually build opencv4nodejs and successfully ran:

npm install opencv-build

I then changed the following environment variables to the following:

```
OPENCV_BIN_DIR = C:\Program Files\nodejs10\node_modules\opencv-build\opencv\build\x64\vc15\bin
OPENCV_LIB_DIR = C:\Program Files\nodejs10\node_modules\opencv-build\opencv\build\x64\vc15\lib
OPENCV_INCLUDE_DIR = C:\Program Files\nodejs10\node_modules\opencv-build\opencv; C:\Program Files\nodejs10\node_modules\opencv-build\opencv\build\opencv2
OPENCV4NODEJS_DISABLE_AUTOBUILD = 1
```

and ran: npm install --save opencv4nodejs

which gave me the error:
Error: specified lib dir does not exist: C:\Program Files\nodejs10\node_modules\opencv-build\opencv\build\x64\vc15\lib;

I have also attached a snippet from the log:
```
864 verbose stack Error: opencv4nodejs@4.6.0 install: `node-gyp rebuild`
864 verbose stack Exit status 1
864 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs10\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
864 verbose stack     at EventEmitter.emit (events.js:182:13)
864 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs10\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
864 verbose stack     at ChildProcess.emit (events.js:182:13)
864 verbose stack     at maybeClose (internal/child_process.js:961:16)
864 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
865 verbose pkgid opencv4nodejs@4.6.0
866 verbose cwd C:\Program Files\nodejs10
867 verbose Windows_NT 10.0.17134
868 verbose argv "C:\\Program Files\\nodejs10\\node.exe" "C:\\Program Files\\nodejs10\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "opencv4nodejs"
869 verbose node v10.5.0
870 verbose npm  v6.1.0
871 error code ELIFECYCLE
872 error errno 1
873 error opencv4nodejs@4.6.0 install: `node-gyp rebuild`
873 error Exit status 1
874 error Failed at the opencv4nodejs@4.6.0 install script.
874 error This is probably not a problem with npm. There is likely additional logging output above.
875 verbose exit [ 1, true ]
```

Would anyone know the mistake I am making in my attempt to install opencv4nodejs?

Thank you,
James

I have attached the recorded logs here:
[2018-06-27T07_07_55_105Z-debug.log](https://github.com/justadudewhohacks/opencv4nodejs/files/2140167/2018-06-27T07_07_55_105Z-debug.log)

A screenshot of the issue:
![screenshot](https://user-images.githubusercontent.com/18180310/41959053-cd643e22-79a0-11e8-9da2-87e6668ac55e.png)

Logs seen in the screenshot/powershell
[powershellresults.txt](https://github.com/justadudewhohacks/opencv4nodejs/files/2140188/powershellresults.txt)

**Comment by justadudewhohacks** [comment]
Hmm hard to say, what's going on here. Might be an issue due to the whitespace in the path `C:\Program Files\` or maybe a permission issue. I would try to install it somewhere else than und Program Files to be honest.

**Comment by justadudewhohacks** [comment]
Almost certainly an issue with the whitespace in your path.

**Comment by meisammofidi** [comment]
does not work. Whitespace in path is not issue or at least does not solve the problem
