### ISSUE TITLE
Streaming to web page is very slow

### ISSUE THREAD

**Issue by ShankyTiwari** [justadudewhohacks/opencv4nodejs#346]
Hi there,
I am working on a Webcam face detection and everything is fine but when I render the result on the webpage it becomes too laggy though the app is running on the local server.
```javascript
const frameResized = frame.resizeToMax(320);
// detect faces
const faceRects = detectFaces(frameResized);
if (faceRects.length) {
    // draw detection
    faceRects.forEach(faceRect => drawBlueRect(frameResized, faceRect));
}
socketIO.emit('face', {
    buffer: cv.imencode('.jpg', frameResized)
});
```

I am using the result(Buffer) of ```cv.imencode('.jpg', frameResized)``` to display on web page using socket.io. But it's very slow.

The **[repo](https://github.com/ShankyTiwari/Face-detection-NodeJs-Opencv)** can be found here. Any suggestions?

Thanks.

**Comment by justadudewhohacks** [comment]
Hi please consider my comment here #332. Please measure what the bottlenecks are, cv.imencode, transmission or client side rendering.

**Comment by ShankyTiwari** [comment]
Hi, @justadudewhohacks , Thanks for replying. 

Yes, before posing this issue, I saw your comment on [#332](https://github.com/justadudewhohacks/opencv4nodejs/issues/332), but it didn't help me. Also, I looked into other issues as well and I googled about this but found nothing that can help me. 

Below is my JS code and in my opinion, there is nothing too heavy. Am just converting buffer to a base64 string, that's all. Do you think below code can be improved?
```javascript
'use strict';

const socket = io.connect('http://localhost:5000/');

const canvas = document.getElementById('canvas-video');
const context = canvas.getContext('2d');
const img = new Image();

context.fillStyle = '#333';
context.fillText('Loading...', canvas.width / 2 - 30, canvas.height / 3);

socket.on('face', function (data) {
	const uint8Arr = new Uint8Array(data.buffer);
	const str = String.fromCharCode.apply(null, uint8Arr);
	const base64String = btoa(str);

	img.onload = function () {
		context.drawImage(this, 0, 0, canvas.width, canvas.height);
	};
	img.src = 'data:image/png;base64,' + base64String;
});

```

Thanks,

**Comment by MattCollins84** [comment]
Hey @ShankyTiwari I got it working with almost identical code to yours. The only difference that I can see is that I am using `jpg` rather than `png`. I'm not sure if that would make a huge difference.

The other thing that made a big difference is how often I am pulling a frame from the camera. When I had it set too quickly, it seemed to be flooding the front-end. Calculating the correct rate, using the FPS value of the `VideoCapture` helped.

`Math.ceil(1000 / fps)` as the timer for your `setInterval`

**Comment by ShankyTiwari** [comment]
Ah, I didn't think that way. Now it works properly, thanks @MattCollins84. If anyone else is stuck there, the Github repo can be found **[here](https://github.com/ShankyTiwari/Face-detection-NodeJs-Opencv)**.

**Comment by ShankyTiwari** [comment]
Hi @justadudewhohacks, There one more small problem. My webcam captures entire image in Green color as shown below,
![example](https://user-images.githubusercontent.com/15548024/42120692-3b6b51be-7c3d-11e8-96d1-95cdf63e7eb2.png)
Is there anything I can do about this?
