### ISSUE TITLE
applyColorMap

### ISSUE THREAD

**Issue by MattCollins84** [justadudewhohacks/opencv4nodejs#347]
Hi,

I am looking to implement something like this: https://github.com/intel-iot-devkit/python-cv-samples/blob/master/examples/motion-heatmap/motion-heatmap.py

On line 66, it uses `applyColorMap()`, and I can't find the equivalent in this module.. is it implemented yet?

I am trying to implement a motion heatmap, does anyone have any example code for this using `opencv4nodejs`?

Thanks,
Matt

**Comment by justadudewhohacks** [comment]
Hi,

`applyColorMap()` is currently not implemented.
