### ISSUE TITLE
Cannot extend cv.Point2

### ISSUE THREAD

**Issue by MattCollins84** [justadudewhohacks/opencv4nodejs#352]
Hi,

I am trying to create my own wrapper around this module for my own purposes, and to do this I am trying to extend the various classes, such as `cv.Rect`, `cv.Point`, etc...

I can easily extend something like Rect:

```javascript
class NewRect extends cv.Rect {

  constructor(x: number, y: number, width: number, height: number) {
    super(x, y, width, height);
  }

  foo() {
    console.log('foo')
  }
}
const r = new NewRect(10, 10, 10, 10);
console.log(r); // NewRect { height: 10, width: 10, y: 10, x: 10 }
r.foo(); // foo
```

But when extending Point, I am struggling:

```javascript
class NewPoint extends cv.Point2 {

  constructor(x: number, y: number) {
    super(x, y);
  }
  foo() {
    console.log('foo')
  }

}

const p = new NewPoint(10, 10);
console.log(p); // Point2 { y: 10, x: 10 }
p.foo(); // TypeError: p.foo is not a function
```

For some reason, it seems that when I create a new instance of `NewPoint`, it still thinks it is a `Point2`?

I have tried extending `cv.Point`, which is what `cv.Point2` is subclassed from, but this also doesn't work (and the typings suggest that I cannot pass anything into the constructor for `cv.Point`.

Has anyone come across this before?

**Comment by justadudewhohacks** [comment]
Shouldn't your example be `const p = new NewPoint(10, 10);` instead of `const p = new Point(10, 10);`?

**Comment by MattCollins84** [comment]
Sorry yes it should be, I modified my code slightly for the example (my extended classes are called `Point` and `Rect` and it was confusing for the example above) and forgot to change it in all places. Good spot.

That wasn't contributing to my problem, however
