### ISSUE TITLE
How to make face recognition work better

### ISSUE THREAD

**Issue by rafaP** [justadudewhohacks/opencv4nodejs#353]
Hello,

I have been using the opencv4nodejs for face recognition, but it gives me the wrong persons when i predict from a live video stream or even from a image file. I have 3 persons and 7 pictures for person, i do the training, save it and load it to the live stream listener, that gets data from unity application.

Maybe i should use other pictures, or maybe other ligthning?

I have changed the recognizer to this values: cv.LBPHFaceRecognizer(2,8,8,8,130.0);
And it gave better result, but still....
How can i make it less  wrong on the result?

**Comment by justadudewhohacks** [comment]
The face recognizers from OpenCV are not very stable, especially when you are having faces in different poses. If you want to have something more stable, you could try a CNN based approach, like [face-recognition.js](https://github.com/justadudewhohacks/face-recognition.js), which can be used along with opencv4nodejs.
