### ISSUE TITLE
OpenCV4NodeJS Not installing

### ISSUE THREAD

**Issue by mtareiling** [justadudewhohacks/opencv4nodejs#356]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description
OpenCV is not installing and is giving errors, i don;t know how to fix these and i think i have tried anything. please help!
[help.txt](https://github.com/opencv/opencv/files/2189784/help.txt)

**Comment by justadudewhohacks** [comment]
Hi,

Please provide the terminal log (not the npm log). Otherwise we can't help you.

**Comment by mtareiling** [comment]
'help.txt'

**Comment by mtareiling** [comment]
How can i show you the Terminal log? @justadudewhohacks

**Comment by justadudewhohacks** [comment]
Uhm, simply pipe the terminal output into a text file, or copy and paste it. Or atleast copy and paste the error message displayed in your terminal into here.

**Comment by justadudewhohacks** [comment]
You need to install cmake

**Comment by manishboricha** [comment]
I am trying to installing this on MacOS Mojave 10.14.3

Getting below error at the end of the installation : 

793 timing stage:rollbackFailedOptional Completed in 3425ms
794 timing stage:runTopLevelLifecycles Completed in 1078945ms
795 verbose stack Error: opencv-build@0.0.17 install: `node ./install.js`
795 verbose stack Exit status 1
795 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
795 verbose stack     at EventEmitter.emit (events.js:197:13)
795 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
795 verbose stack     at ChildProcess.emit (events.js:197:13)
795 verbose stack     at maybeClose (internal/child_process.js:978:16)
795 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
796 verbose pkgid opencv-build@0.0.17
797 verbose cwd /Users/manishboricha/eclipse-workspace/Kings_iOS
798 verbose Darwin 18.2.0
799 verbose argv "/usr/local/Cellar/node/11.9.0/bin/node" "/usr/local/bin/npm" "i" "-g" "opencv4nodejs"
800 verbose node v11.9.0
801 verbose npm  v6.5.0
802 error code ELIFECYCLE
803 error errno 1
804 error opencv-build@0.0.17 install: `node ./install.js`
804 error Exit status 1
805 error Failed at the opencv-build@0.0.17 install script.
805 error This is probably not a problem with npm. There is likely additional logging output above.
806 verbose exit [ 1, true ]
