### ISSUE TITLE
'set()' within a nested for loop

### ISSUE THREAD

**Issue by ScottRocha** [justadudewhohacks/opencv4nodejs#357]
Trying to create a "heatmap" mask based off of the value of a RGB channel and the only way I can see doing this is with a nested for loop with an if/else chain.

This takes forever to do normally for larger images, so i have added this check / set to a Promise array.
I noticed that this finishes very quick, typically within a second, but the "set" doesn't stick.

```
const promises = [];

let height = 0;
let width = 0;

const heightMax = config.image.height;
const widthMax = config.image.width;

for (; height < heightMax; height++) {

  for (; width < widthMax; width++) {

    promises.push(new Promise((rslv) => {

      const pixel = diffJpeg.at(height, width);

      if (pixel.x >= 100) {

        return rslv(imageMask.set(height, width, [ 123, 0, 255 ]));

      } else if (pixel.x >= 80) {

        return rslv(imageMask.set(height, width, [ 0, 123, 255 ]));

      } else if (pixel.x >= 70) {

        return rslv(imageMask.set(height, width, [ 0, 123, 255 ]));

      } else if (pixel.x >= 60) {

        return rslv(imageMask.set(height, width, [ 0, 112, 123 ]));

      } else {

        return rslv();

      }

    }));

  }

}

Promise.all(promises).then(() => doSomething()).catch();
```

**Comment by ScottRocha** [comment]
If this function is not truly synchronous then maybe a solution would be to create a sync / async function.

**Comment by ScottRocha** [comment]
It looks like another solution to my problem would be the implementation of the "setTo" function. If this is implemented I could just do an "inRange" to create a mask for the different levels then just use "setTo" with a "Vec3" provided as the  set to value and the mask as the mask.

as per: https://docs.opencv.org/2.4/modules/core/doc/basic_structures.html?highlight=Ptr#mat-setto

**Comment by justadudewhohacks** [comment]
Looping over an entire image is not a good idea as it is pretty slow, as you noticed. Usually there is a better way to do this in OpenCV.

You could mimic `setTo` by doing something like this `mask.and(new Mat(height, width, type, [ 123, 0, 255 ]))`. Or if you want to submit a PR for `setTo`, that would also be nice :)

**Comment by ScottRocha** [comment]
It looks like 'inRange()' only returns a 1 channel Mat, and I think because of this I can't do an 'and()' with a 3 channel Mat. (It causes the "app" to crash). I wish I knew more about C++ and bindings in general or I would have the PR done by now! Sorry for the inconvenience.

**Comment by ScottRocha** [comment]
I think I have a working prototype of the 'setTo()' function complete. I will create a PR shortly. The only thing I have not yet implemented is a test.

**Comment by rainabba** [comment]
In case this is of any benefit to this issue, you may want to check out https://github.com/justadudewhohacks/opencv4nodejs/issues/329#issuecomment-418781220
