### ISSUE TITLE
std::runtime_error

### ISSUE THREAD

**Issue by georgetk1996** [justadudewhohacks/opencv4nodejs#359]
![screenshot from 2018-07-19 12-40-46](https://user-images.githubusercontent.com/18638870/42927232-5b9fd79e-8b23-11e8-818c-ce107981c9a9.png)

This is the error showing in my terminal. After showing the error at 1st time, I installed libgtk2.0-dev & pkg-config. Still the error comes. I'm running it on Linux Mint.

--- Code I'm trying to execute ---

const cv = require('opencv4nodejs');
const detectAndComputeAsync = (det, img) =>
  det.detectAsync(img)
    .then(kps => det.computeAsync(img, kps)
                      .then(desc => ({ kps, desc }))
    );

const img1 = cv.imread('./a.jpg');
const img2 = cv.imread('./b.jpeg');

const detectorNames = [
  'AKAZE',
  'BRISK',
  'KAZE',
  'ORB'
];

const createDetectorFromName = name => new cv[`${name}Detector`]();

// create 4 promises -> each detector detects and computes descriptors for img1 and img2
const promises = detectorNames
  .map(createDetectorFromName)
  .map(det =>
    // also detect and compute descriptors for img1 and img2 async
    Promise.all([detectAndComputeAsync(det, img1), detectAndComputeAsync(det, img2)])
      .then(allResults =>
        cv.matchBruteForceAsync(
          allResults[0].desc,
          allResults[1].desc
        )
        .then(matches => ({
          matches,
          kps1: allResults[0].kps,
          kps2: allResults[1].kps
        }))
      )
);

Promise.all(promises)
  .then((allResults) => {
    allResults.forEach((result, i) => {
      const drawMatchesImg = cv.drawMatches(
        img1,
        img2,
        result.kps1,
        result.kps2,
        result.matches
      );
      cv.imshowWait(detectorNames[i], drawMatchesImg);
      cv.destroyAllWindows();
    });
  })
.catch(err => console.error(err));

**Comment by justadudewhohacks** [comment]
After installing `libgtk2.0-dev`  you have to recompile your OpenCV build. If you are using the auto build, try reinstalling `opencv-build`, by clearing it from your node_modules folder for example.

**Comment by georgetk1996** [comment]
Removed **opencv-build**  from **node_modules** folder. Now what? Should I run  **npm install --save opencv4nodejs** again?

**Comment by justadudewhohacks** [comment]
Actually, since you also have to recompile opencv4nodejs you could just remove opencv-build and opencv4nodejs and run `npm i opencv4nodejs` again. Or simply `npm uninstall opencv4nodejs && npm i opencv4nodejs`.

**Comment by georgetk1996** [comment]
I removed node_modules folder and doing npm install --save opencv4nodejs again.
Thanks for this node-opencv integration dude. I've been searching this for a while. Need to experiment feature-matching. I'll surely share my results. Thanks!

(Have a desire to help you in this, but i'm not a pro :P =D)

**Comment by justadudewhohacks** [comment]
Great to hear!

No need to be a pro. I am not a pro. This project is happy to take any kind of contributions! Adding new bindings to the package, in case you are missing some, should hopefully be straight forward, as the concept to implement these is the same, over and over again.

If you need help just ask or join us on [slack](https://slack.bri.im/). :)

**Comment by georgetk1996** [comment]
Thanks bro for the invitation. 
Btw previous comment works and I got output. Trying to modify it to display some percentage of feature matching.
