### ISSUE TITLE
Build Error :: Import opencv4nodejs in react application

### ISSUE THREAD

**Issue by bnadaf** [justadudewhohacks/opencv4nodejs#363]
Trying to require opencv4nodejs in React application with webpack and gulp. I have added opencv4nodejs with npm install opencv4nodejs.
node v10.5.0
npm v6.2.0
opencv4nodejs v4.7.0

Build Error when adding  import * as cv from 'opencv4nodejs'

ERROR in ./node_modules/opencv4nodejs/lib/commons.js
Module not found: Error: Can't resolve 'fs' in 'node_modules\opencv4nodejs\lib'
 @ ./node_modules/opencv4nodejs/lib/commons.js 1:11-24
 @ ./node_modules/opencv4nodejs/lib/cv.js
 @ ./node_modules/opencv4nodejs/lib/opencv4nodejs.js

ERROR in ./node_modules/opencv4nodejs/node_modules/opencv-build/index.js
Module not found: Error: Can't resolve 'fs' in 'node_modules\opencv4nodejs\node_modules\opencv-build'
 @ ./node_modules/opencv4nodejs/node_modules/opencv-build/index.js 2:11-24
 @ ./node_modules/opencv4nodejs/lib/cv.js
 @ ./node_modules/opencv4nodejs/lib/opencv4nodejs.js

WARNING in ./node_modules/opencv4nodejs/lib/cv.js
15:7-68 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/opencv4nodejs/lib/cv.js
 @ ./node_modules/opencv4nodejs/lib/opencv4nodejs.js
 @ ./src/client/views/Grid.js

WARNING in ./node_modules/opencv4nodejs/lib/cv.js
17:7-70 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/opencv4nodejs/lib/cv.js
 @ ./node_modules/opencv4nodejs/lib/opencv4nodejs.js

ERROR in ./node_modules/opencv4nodejs/node_modules/opencv-build/install/utils.js
Module not found: Error: Can't resolve 'child_process' in 'node_modules\opencv4nodejs\node_modules\opencv-build\install'
 @ ./node_modules/opencv4nodejs/node_modules/opencv-build/install/utils.js 1:34-58
 @ ./node_modules/opencv4nodejs/node_modules/opencv-build/index.js
 @ ./node_modules/opencv4nodejs/lib/cv.js
 @ ./node_modules/opencv4nodejs/lib/opencv4nodejs.js

**Comment by justadudewhohacks** [comment]
Did you have a look at the [example](https://github.com/justadudewhohacks/opencv-electron/blob/master/webpack-reactjs) showing how to use opencv4nodejs with electron, react and webpack?

I am assuming you are using electron or nw.js? If not, keep in mind, that this is not a clientside library and needs a nodejs runtime.

**Comment by justadudewhohacks** [comment]
With express.js it should work. You will have to return the images processed on the serverside to your client, either by stream them via websockets, or encoding them to base64 and sending them back.
