### ISSUE TITLE
/var/lang/lib/libstdc++.so.6: version `CXXABI_1.3.9' not found 

### ISSUE THREAD

**Issue by igorescobar** [justadudewhohacks/opencv4nodejs#364]
Hey guys,

I'm trying to deploy this inside of a AWS lamda function and when I import the library I get this error:

```
/var/lang/lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /var/task/node_modules/opencv-build/opencv/build/lib/libopencv_core.so.3.4)
```

You guys have any idea how to work around this? Seems like lambda environment are adding this `/var/lang/lib` to  the `LD_LIBRARY_PATH` and therefore it is using a old version of `libstdc++` which comes with the `gcc`.

**Comment by olivierto** [comment]
i have exactly the same problem! how did you manage to solve this?

**Comment by realanmup** [comment]
i was using 'gm' layer and i got stuck to this. has anyone figured it out?
