### ISSUE TITLE
TypeError: cv3.TrackerKCF is not a constructor

### ISSUE THREAD

**Issue by raphaelbarreto** [justadudewhohacks/opencv4nodejs#365]
How do I instantiate a TrackerKCF?
I'm getting this error with the following code:

```
const cv3 = require("opencv4nodejs");
var tracker = new cv3.TrackerKCF();
```
According to the [docs](https://justadudewhohacks.github.io/opencv4nodejs/docs/TrackerKCF#TrackerKCF), it looks like it's how it was supposed to be called.

**Comment by justadudewhohacks** [comment]
What's the error you get? Did you compile with extra modules? Check `console.log(cv.xmodules)` to see which extra modules have been compiled into the package.

**Comment by raphaelbarreto** [comment]
I've used the prebuilt windows x64 package. As soon as I get to the PC I'll try to pull the CV.xmodules and post here.

**Comment by raphaelbarreto** [comment]
Just an update, I've just tested on python using openCV and the TrackerKCF works perfectly.
Is it not exposed on opencv4nodejs?

**Comment by justadudewhohacks** [comment]
It is exposed, you are just not compiling opencv4nodejs with extra modules apparently. The install script will look for the library files for each extra module in your library dir, if it doesn't find a library, it doesn't compile the module.

**Comment by raphaelbarreto** [comment]
It seems it had built the module.
![trackerkcf_built](https://user-images.githubusercontent.com/1252830/43419982-e9c89f44-9418-11e8-8030-e79c96bc18c8.JPG)

Do I need to enable a module manually?

**Comment by raphaelbarreto** [comment]
Nevermind. I've removed the opencv4nodejs, deleted package-lock.json and reinstalled with autobuild and it's working now. Thanks!
