### ISSUE TITLE
npm install issues in Windows 10

### ISSUE THREAD

**Issue by rofoto** [justadudewhohacks/opencv4nodejs#366]
Hi, 

  I am having issues installing on windows 10, I have tried both pre-compiling opencv and doing the auto install. Last logs attached here. 

Any help would be appreciated.

Thanks again
[2018-07-30T03_08_20_794Z-debug.log](https://github.com/justadudewhohacks/opencv4nodejs/files/2239569/2018-07-30T03_08_20_794Z-debug.log)

**Comment by entmike** [comment]
Did you compile opencv source code first?

**Comment by justadudewhohacks** [comment]
Unfortunately npm log doesn't help, I need your terminal log to determine the issue.

**Comment by rofoto** [comment]
Apologies for the delay in response. Apologies for the noob question but how can I get the terminal logs you need to help find the issue. SO and google have both failed me. 

thanks

**Comment by rofoto** [comment]
@entmike   

  Yes I also tried with a manual build of Opencv.

**Comment by justadudewhohacks** [comment]
Closing for now, because of inactivity. If you still need help  copy and paste the log from your terminal in here please.
