### ISSUE TITLE
Support for limiting number of threads 

### ISSUE THREAD

**Issue by AssaultKoder95** [justadudewhohacks/opencv4nodejs#368]
I am using opencv4nodejs for a server-side application, I have read that OpenCV creates new threads per request which is actually increasing my CPU consumption. 
http://www.anoopjohnson.com/2010/10/opencv-performance-and-threads/

I wanted to know if there any method exists that can perform same as cv::setNumThreads() if you are using the C++ library and cvSetNumThreads() if you are using the Python wrapper.

**Comment by justadudewhohacks** [comment]
The binding for `setNumThreads`  is currently not implemented, but should be easy to implement. Always happy to take PRs.

**Comment by AssaultKoder95** [comment]
Hi @justadudewhohacks 
I tried implementing the feature, the issue that I faced is quite abnormal.

I implemented two methods in core.cc 

`NAN_METHOD(Core::SetNumThreads) {
  // std::cout << info[0]->NumberValue();
  int threadCount = info[0]->NumberValue();
  cv::setNumThreads(threadCount);
}

NAN_METHOD(Core::GetNumThreads) {
  int threadCount = cv::getNumThreads();
  std::cout << threadCount;
}`

When I run setNumThreads, the info[0] variable displays the value passed as the argument,
while the getNumThreads displays the number of logical CPU's present in my machine

For reference:
![Uploading Screen Shot 2018-08-09 at 1.23.20 PM.png…](setNumThreads)
 
https://docs.opencv.org/3.4.2/db/de0/group__core__utils.html#gae78625c3c2aa9e0b83ed31b73c6549c0

**Comment by justadudewhohacks** [comment]
Hi,

So what's the issue?

**Comment by AssaultKoder95** [comment]
The value that I set using this setNumThreads, does not get updated when I check it using getNumThreads
 
I verified the same using a simple console program, I have OpenCV installed as well & when I ran same command in Python it resulted in same value

**Comment by AssaultKoder95** [comment]
Hey @justadudewhohacks 

I tried some other way arounds as well but still not able to figure out why it doesn't set threads using setNumThreads function

**Comment by oyyd** [comment]
Hi, @AssaultKoder95. Are you still working on this? If not, I could pick this up.

**Comment by AssaultKoder95** [comment]
Not working on this issue as of now, you can take this up, in case you need help, let me know :)
