### ISSUE TITLE
Tracker returning Rect even if lost tracking

### ISSUE THREAD

**Issue by raphaelbarreto** [justadudewhohacks/opencv4nodejs#369]
Hi,

On OpenCV documentation here: https://docs.opencv.org/3.4.1/d0/d0a/classcv_1_1Tracker.html#a549159bd0553e6a8de356f3866df1f18
tracker.update() is supposed to return a boolean saying either it was able to track the object or failed to do so. On python's bindings, you can get both bounding box and return value from this function.
opencv4nodejs is always returning a Rect, so I can't tell if it lost track or not.

**Comment by justadudewhohacks** [comment]
True, would probably be a simple adjustment in the tracker update binding [here](https://github.com/justadudewhohacks/opencv4nodejs/blob/dfc0605771a5eed91295f06f72607d96a5be9098/cc/modules/tracking/Tracker.cc#L31-L33), if you want to submit a PR.
