### ISSUE TITLE
morphologyEx not found

### ISSUE THREAD

**Issue by Aserus** [justadudewhohacks/opencv4nodejs#37]
Hello. This library is very cool.
But I can't find method morphologyEx

https://docs.opencv.org/3.2.0/d3/dbe/tutorial_opening_closing_hats.html

**Comment by justadudewhohacks** [comment]
I will add the bindings asap.

**Comment by justadudewhohacks** [comment]
Merged and published to npm.

**Comment by Aserus** [comment]
Thanks
