### ISSUE TITLE
Node-gyp rebuild error: 'cannot open include file 'errno.h': No such file or directory

### ISSUE THREAD

**Issue by godwwinpeace22** [justadudewhohacks/opencv4nodejs#370]
I installed the package and the build ran succesfuly
but crashed with the error below when running `node-gyp rebuild`
`npm install face-recognition
openssl config failed: error:02001003:system library:fopen:No such process
openssl config failed: error:02001003:system library:fopen:No such process

> face-recognition@0.9.3 install C:\Web_Development\face-recognition.js-master\node_modules\face-recognition
> node-gyp rebuild

C:\Web_Development\face-recognition.js-master\node_modules\face-recognition>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
openssl config failed: error:02001003:system library:fopen:No such process
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
cl : Command line warning D9025: overriding '/MT' with '/MD' [C:\Web_Development\face-recognition.js-mast
er\node_modules\face-recognition\build\facerec.vcxproj]
cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Web_Development\face-recognition.js-mas
ter\node_modules\face-recognition\build\facerec.vcxproj]
cl : Command line warning D9025: overriding '/MT' with '/MD' [C:\Web_Development\face-recognition.js-mast
er\node_modules\face-recognition\build\facerec.vcxproj]
cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Web_Development\face-recognition.js-mas
ter\node_modules\face-recognition\build\facerec.vcxproj]
  index.cc
cl : Command line warning D9025: overriding '/MT' with '/MD' [C:\Web_Development\face-recognition.js-mast
er\node_modules\face-recognition\build\facerec.vcxproj]
cl : Command line warning D9025: overriding '/GR-' with '/GR' [C:\Web_Development\face-recognition.js-mas
ter\node_modules\face-recognition\build\facerec.vcxproj]
  ImageRGB.cc
c:\users\unplugged\.node-gyp\8.11.3\include\node\uv-errno.h(25): fatal error C1083: Cannot open include f
ile: 'errno.h': No such file or directory (compiling source file ..\cc\ImageRGB.cc) [C:\Web_Development\f
ace-recognition.js-master\node_modules\face-recognition\build\facerec.vcxproj]
c:\users\unplugged\.node-gyp\8.11.3\include\node\uv-errno.h(25): fatal error C1083: Cannot open include f
ile: 'errno.h': No such file or directory (compiling source file ..\cc\index.cc) [C:\Web_Development\face
-recognition.js-master\node_modules\face-recognition\build\facerec.vcxproj]
  ImageGray.cc
  CvImage.cc
c:\users\unplugged\.node-gyp\8.11.3\include\node\uv-errno.h(25): fatal error C1083: Cannot open include f
ile: 'errno.h': No such file or directory (compiling source file ..\cc\ImageGray.cc) [C:\Web_Development\
face-recognition.js-master\node_modules\face-recognition\build\facerec.vcxproj]
c:\users\unplugged\.node-gyp\8.11.3\include\node\uv-errno.h(25): fatal error C1083: Cannot open include f
ile: 'errno.h': No such file or directory (compiling source file ..\cc\CvImage.cc) [C:\Web_Development\fa
ce-recognition.js-master\node_modules\face-recognition\build\facerec.vcxproj]
  Rect.cc
  MmodRect.cc
c:\users\unplugged\.node-gyp\8.11.3\include\node\uv-errno.h(25): fatal error C1083: Cannot open include f
ile: 'errno.h': No such file or directory (compiling source file ..\cc\MmodRect.cc) [C:\Web_Development\f
ace-recognition.js-master\node_modules\face-recognition\build\facerec.vcxproj]
  FullObjectDetection.cc
c:\users\unplugged\.node-gyp\8.11.3\include\node\uv-errno.h(25): fatal error C1083: Cannot open include f
ile: 'errno.h': No such file or directory (compiling source file ..\cc\Rect.cc) [C:\Web_Development\face-
recognition.js-master\node_modules\face-recognition\build\facerec.vcxproj]
  Point.cc
c:\users\unplugged\.node-gyp\8.11.3\include\node\uv-errno.h(25): fatal error C1083: Cannot open include f
ile: 'errno.h': No such file or directory (compiling source file ..\cc\FullObjectDetection.cc) [C:\Web_De
velopment\face-recognition.js-master\node_modules\face-recognition\build\facerec.vcxproj]
c:\users\unplugged\.node-gyp\8.11.3\include\node\uv-errno.h(25): fatal error C1083: Cannot open include f
ile: 'errno.h': No such file or directory (compiling source file ..\cc\Point.cc) [C:\Web_Development\face
-recognition.js-master\node_modules\face-recognition\build\facerec.vcxproj]
  Array.cc
  ChipDetails.cc
c:\users\unplugged\.node-gyp\8.11.3\include\node\uv-errno.h(25): fatal error C1083: Cannot open include f
ile: 'errno.h': No such file or directory (compiling source file ..\cc\Array.cc) [C:\Web_Development\face
-recognition.js-master\node_modules\face-recognition\build\facerec.vcxproj]
c:\users\unplugged\.node-gyp\8.11.3\include\node\uv-errno.h(25): fatal error C1083: Cannot open include f
ile: 'errno.h': No such file or directory (compiling source file ..\cc\ChipDetails.cc) [C:\Web_Developmen
t\face-recognition.js-master\node_modules\face-recognition\build\facerec.vcxproj]
  utils.cc
  ImageWindow.cc
c:\users\unplugged\.node-gyp\8.11.3\include\node\uv-errno.h(25): fatal error C1083: Cannot open include f
ile: 'errno.h': No such file or directory (compiling source file ..\cc\utils.cc) [C:\Web_Development\face
-recognition.js-master\node_modules\face-recognition\build\facerec.vcxproj]
c:\users\unplugged\.node-gyp\8.11.3\include\node\uv-errno.h(25): fatal error C1083: Cannot open include f
ile: 'errno.h': No such file or directory (compiling source file ..\cc\ImageWindow.cc) [C:\Web_Developmen
t\face-recognition.js-master\node_modules\face-recognition\build\facerec.vcxproj]
  ShapePredictor.cc
  FrontalFaceDetector.cc
c:\users\unplugged\.node-gyp\8.11.3\include\node\uv-errno.h(25): fatal error C1083: Cannot open include f
ile: 'errno.h': No such file or directory (compiling source file ..\cc\ShapePredictor.cc) [C:\Web_Develop
ment\face-recognition.js-master\node_modules\face-recognition\build\facerec.vcxproj]
  FaceDetectorNet.cc
c:\users\unplugged\.node-gyp\8.11.3\include\node\uv-errno.h(25): fatal error C1083: Cannot open include f
ile: 'errno.h': No such file or directory (compiling source file ..\cc\FrontalFaceDetector.cc) [C:\Web_De
velopment\face-recognition.js-master\node_modules\face-recognition\build\facerec.vcxproj]
  FaceRecognizerNet.cc
c:\users\unplugged\.node-gyp\8.11.3\include\node\uv-errno.h(25): fatal error C1083: Cannot open include f
ile: 'errno.h': No such file or directory (compiling source file ..\cc\FaceDetectorNet.cc) [C:\Web_Develo
pment\face-recognition.js-master\node_modules\face-recognition\build\facerec.vcxproj]
c:\users\unplugged\.node-gyp\8.11.3\include\node\uv-errno.h(25): fatal error C1083: Cannot open include f
ile: 'errno.h': No such file or directory (compiling source file ..\cc\FaceRecognizerNet.cc) [C:\Web_Deve
lopment\face-recognition.js-master\node_modules\face-recognition\build\facerec.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Web_Development\face-recognition.js-master\node_modules\face-recognition
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! face-recognition@0.9.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the face-recognition@0.9.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\unplugged\AppData\Roaming\npm-cache\_logs\2018-08-04T11_00_36_736Z-debug.log`

What could be the isssue ???

**Comment by justadudewhohacks** [comment]
This is not the face-recognition.js repo.

Anyways, I've never seen that before. Looks like some libuv related node header files are missing. Maybe try to upgrade / reinstall node-gyp and or node.

**Comment by godwwinpeace22** [comment]
Oh, thats true! I have tried the both packages but got errors relating to node-gyp and msbuild tools. I will try reinstall/upgrade as you suggested, thanks.

**Comment by justadudewhohacks** [comment]
Closing for now, because of inactivity.
