### ISSUE TITLE
Support for accumulateWeighted

### ISSUE THREAD

**Issue by jbfp** [justadudewhohacks/opencv4nodejs#374]
Hi, I'm looking for the [cv::accumulateWeighted](https://webcache.googleusercontent.com/search?q=cache:kCSC8gtKJ0EJ:https://docs.opencv.org/3.4.2/d7/df3/group__imgproc__motion.html) function from the imgproc module but I can't seem to find it in these bindings. Is this function not supported or is it perhaps called something different?

**Comment by justadudewhohacks** [comment]
Hi,

Usually the bindings in this module should have the same name as the OpenCV function. There is no binding for accumulateWeighted yet.

**Comment by justadudewhohacks** [comment]
cv.accumulateWeighted is available in version 5.4.0
