### ISSUE TITLE
Mat need reshape operation!

### ISSUE THREAD

**Issue by qyou** [justadudewhohacks/opencv4nodejs#376]
When I use `readNetFromCaffe` to load a dnn model, I get a 4 dimensional matrix result as follows
![image](https://user-images.githubusercontent.com/1219601/43958008-6e554aac-9cdc-11e8-9d1a-f7a9c8181f36.png)
```
code like this:
...
const outputBlob = net.forward()
console.log(outputBlob.sizes)  // -> [1, 2, 768, 1024]
const buffer = outputBlob.getData()
console.log(buffer.length) // -> only 4 ???
```
The buffer only has four bytes and I can't get the whole data. 
Why no reshape operation supplied in the Mat class? How can I do the right thing to get the 2 matrix with size(768, 1024)? Thanks.

**Comment by justadudewhohacks** [comment]
Dealing with Mats bigger than 3 dimensions is currently not well supported. Maybe you can flatten the mat into a 2D mat, like this:  `mat.flattenFloat(mat.sizes[2], 2 * mat.sizes[3]);`, similar to what I did in the [dnnSSDCoco example](https://github.com/justadudewhohacks/opencv4nodejs/blob/master/examples/dnnSSDCoco.js#L41).

Maybe it is also possible to simply implement mat.at for 4D Mats as well. @asilvas added support for getting and setting values for 3D Mats a while ago in the following PRs: #261 and #264, in case you want to investigate in this and submit a PR.

**Comment by qyou** [comment]
@justadudewhohacks Yes, it works! Thank you very much!
