### ISSUE TITLE
npm linux install failing - "Error: opencv-build@0.014 install: 'node ./install.js'

### ISSUE THREAD

**Issue by ksteinberg** [justadudewhohacks/opencv4nodejs#378]
System Details: 

* Linux version 2.6.32-042stab111.11 (root@kbuild-rh6-x64.eng.sw.ru) (gcc version 4.4.6 20120305 (Red Hat 4.4.6-4) (GCC) ) #1 SMP Tue Sep 1 18:19:12 MSK 2015
* Cmake 3.12.1
* git installed
* repository set to private in package.json file

------------------------------- Error output from log --------------------------------------

331 silly saveTree       ├─┬ gauge@2.7.4
331 silly saveTree       │ ├── aproba@1.2.0
331 silly saveTree       │ ├── object-assign@4.1.1
331 silly saveTree       │ ├── signal-exit@3.0.2
331 silly saveTree       │ └── wide-align@1.1.3
331 silly saveTree       └── set-blocking@2.0.0
332 verbose stack Error: opencv-build@0.0.14 install: `node ./install.js`
332 verbose stack Exit status 1
332 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
332 verbose stack     at EventEmitter.emit (events.js:182:13)
332 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
332 verbose stack     at ChildProcess.emit (events.js:182:13)
332 verbose stack     at maybeClose (internal/child_process.js:962:16)
332 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:249:5)
333 verbose pkgid opencv-build@0.0.14
334 verbose cwd /home/punch/reel
335 verbose Linux 2.6.32-042stab111.11
336 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "--save" "opencv4nodejs"
337 verbose node v10.8.0
338 verbose npm  v6.2.0
339 error code ELIFECYCLE
340 error errno 1
341 error opencv-build@0.0.14 install: `node ./install.js`
341 error Exit status 1
342 error Failed at the opencv-build@0.0.14 install script.
342 error This is probably not a problem with npm. There is likely additional logging output above.

**Comment by justadudewhohacks** [comment]
Could you post the log from your terminal, or atleast the error message? The npmlog doesn't contain errors thrown by node-gyp.

**Comment by ksteinberg** [comment]
[2018-08-14T11_50_42_380Z-debug.log](https://github.com/justadudewhohacks/opencv4nodejs/files/2288880/2018-08-14T11_50_42_380Z-debug.log)

**Comment by justadudewhohacks** [comment]
Is that an npm log file again? As I said, the error messages are not shown.

**Comment by ksteinberg** [comment]
Sorry about that...guess I forgot to set the loglevel switch...
Anyways, this morning the problem has morphed a bit..get a new error about the git call
I have included the stdout text below as well as attached the log

------------------- stdout --------------------------------------------

[root@s132-148-82-214 reel]# sudo npm install --save  --loglevel verbose opencv4nodejs
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node',
npm verb cli   '/usr/bin/npm',
npm verb cli   'install',
npm verb cli   '--save',
npm verb cli   '--loglevel',
npm verb cli   'verbose',
npm verb cli   'opencv4nodejs' ]
npm info using npm@6.2.0
npm info using node@v10.9.0
npm verb npm-session 73d15d54cdc34b84
npm http fetch GET 304 https://registry.npmjs.org/opencv4nodejs 186ms (from cache)
npm timing stage:loadCurrentTree Completed in 1591ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 9ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 417ms
npm http fetch GET 200 https://registry.npmjs.org/@types%2fnode 45ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/macro-inferno 61ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/opencv-build 89ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/nan 94ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/native-node-utils 91ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/npmlog 23ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/console-control-strings 51ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/set-blocking 54ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/are-we-there-yet 56ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/gauge 62ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/aproba 57ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/object-assign 64ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/signal-exit 65ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/wide-align 65ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 872ms
npm timing stage:loadIdealTree Completed in 1460ms
npm timing stage:generateActionsToTake Completed in 35ms
npm verb correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /root/.npm/_locks/staging-bad55bdad38dafec.lock for /home/punch/reel/node_modules/.staging
npm timing audit compress Completed in 27ms
npm info audit Submitting payload of 15039bytes
npm timing audit submit Completed in 343ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 343ms
npm timing audit body Completed in 1ms
npm timing action:extract Completed in 444ms
npm timing action:finalize Completed in 17ms
npm timing action:refresh-package-json Completed in 40ms
npm info lifecycle aproba@1.2.0~preinstall: aproba@1.2.0
npm info lifecycle console-control-strings@1.1.0~preinstall: console-control-strings@1.1.0
npm info lifecycle nan@2.10.0~preinstall: nan@2.10.0
npm info lifecycle object-assign@4.1.1~preinstall: object-assign@4.1.1
npm info lifecycle are-we-there-yet@1.1.5~preinstall: are-we-there-yet@1.1.5
npm info lifecycle set-blocking@2.0.0~preinstall: set-blocking@2.0.0
npm info lifecycle signal-exit@3.0.2~preinstall: signal-exit@3.0.2
npm info lifecycle wide-align@1.1.3~preinstall: wide-align@1.1.3
npm info lifecycle gauge@2.7.4~preinstall: gauge@2.7.4
npm info lifecycle npmlog@4.1.2~preinstall: npmlog@4.1.2
npm info lifecycle @types/node@10.7.1~preinstall: @types/node@10.7.1
npm info lifecycle macro-inferno@0.2.1~preinstall: macro-inferno@0.2.1
npm info lifecycle native-node-utils@0.1.2~preinstall: native-node-utils@0.1.2
npm info lifecycle opencv-build@0.0.14~preinstall: opencv-build@0.0.14
npm info lifecycle opencv4nodejs@4.7.2~preinstall: opencv4nodejs@4.7.2
npm timing action:preinstall Completed in 5ms
npm info linkStuff aproba@1.2.0
npm info linkStuff console-control-strings@1.1.0
npm info linkStuff nan@2.10.0
npm info linkStuff object-assign@4.1.1
npm info linkStuff are-we-there-yet@1.1.5
npm info linkStuff set-blocking@2.0.0
npm info linkStuff signal-exit@3.0.2
npm info linkStuff wide-align@1.1.3
npm info linkStuff gauge@2.7.4
npm info linkStuff npmlog@4.1.2
npm info linkStuff @types/node@10.7.1
npm info linkStuff macro-inferno@0.2.1
npm info linkStuff native-node-utils@0.1.2
npm info linkStuff opencv-build@0.0.14
npm info linkStuff opencv4nodejs@4.7.2
npm timing action:build Completed in 6ms
npm info lifecycle aproba@1.2.0~install: aproba@1.2.0
npm info lifecycle console-control-strings@1.1.0~install: console-control-strings@1.1.0
npm info lifecycle nan@2.10.0~install: nan@2.10.0
npm info lifecycle object-assign@4.1.1~install: object-assign@4.1.1
npm info lifecycle are-we-there-yet@1.1.5~install: are-we-there-yet@1.1.5
npm info lifecycle set-blocking@2.0.0~install: set-blocking@2.0.0
npm info lifecycle signal-exit@3.0.2~install: signal-exit@3.0.2
npm info lifecycle wide-align@1.1.3~install: wide-align@1.1.3
npm info lifecycle gauge@2.7.4~install: gauge@2.7.4
npm info lifecycle npmlog@4.1.2~install: npmlog@4.1.2
npm info lifecycle @types/node@10.7.1~install: @types/node@10.7.1
npm info lifecycle macro-inferno@0.2.1~install: macro-inferno@0.2.1
npm info lifecycle native-node-utils@0.1.2~install: native-node-utils@0.1.2
npm info lifecycle opencv-build@0.0.14~install: opencv-build@0.0.14

> opencv-build@0.0.14 install /home/punch/reel/node_modules/opencv-build
> node ./install.js

info install if you want to use an own OpenCV installation set OPENCV4NODEJS_DISABLE_AUTOBUILD
info install library dir does not exist: /home/punch/reel/node_modules/opencv-build/opencv/build/lib
info install running install script...
error: unknown option `single-branch'
usage: git clone [options] [--] <repo> [<dir>]

    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
    --progress            force progress reporting
    -n, --no-checkout     don't create a checkout
    --bare                create a bare repository
    --mirror              create a mirror repository (implies bare)
    -l, --local           to clone from a local repository
    --no-hardlinks        don't use local hardlinks, always copy
    -s, --shared          setup as shared repository
    --recursive           initialize submodules in the clone
    --template <path>     path the template repository
    --reference <repo>    reference repository
    -o, --origin <branch>
                          use <branch> instead of 'origin' to track upstream
    -b, --branch <branch>
                          checkout <branch> instead of the remote's HEAD
    -u, --upload-pack <path>
                          path to git-upload-pack on the remote
    --depth <depth>       create a shallow clone of that depth

ERR! child process exited with code 129
npm verb lifecycle opencv-build@0.0.14~install: unsafe-perm in lifecycle false
npm verb lifecycle opencv-build@0.0.14~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/punch/reel/node_modules/opencv-build/node_modules/.bin:/home/punch/reel/node_modules/.bin:/sbin:/bin:/usr/sbin:/usr/bin:/home/punch/cmake-dir/bin
npm verb lifecycle opencv-build@0.0.14~install: CWD: /home/punch/reel/node_modules/opencv-build
npm info lifecycle opencv-build@0.0.14~install: Failed to exec install script
npm timing action:install Completed in 259ms
npm verb unlock done using /root/.npm/_locks/staging-bad55bdad38dafec.lock for /home/punch/reel/node_modules/.staging
npm timing stage:rollbackFailedOptional Completed in 60ms
npm timing stage:runTopLevelLifecycles Completed in 4073ms
npm verb stack Error: opencv-build@0.0.14 install: `node ./install.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
npm verb stack     at EventEmitter.emit (events.js:182:13)
npm verb stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:182:13)
npm verb stack     at maybeClose (internal/child_process.js:961:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
npm verb pkgid opencv-build@0.0.14
npm verb cwd /home/punch/reel
npm verb Linux 2.6.32-042stab111.11
npm verb argv "/usr/bin/node" "/usr/bin/npm" "install" "--save" "--loglevel" "verbose" "opencv4nodejs"
npm verb node v10.9.0
npm verb npm  v6.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv-build@0.0.14 install: `node ./install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv-build@0.0.14 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 4959ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-20T10_59_28_949Z-debug.log

------ log file -----

[2018-08-20T10_59_28_949Z-debug-a.log.txt](https://github.com/justadudewhohacks/opencv4nodejs/files/2302119/2018-08-20T10_59_28_949Z-debug-a.log.txt)

**Comment by justadudewhohacks** [comment]
What's the git version you are using, that it doesn't know about the  'single-branch' option, did you try upgrading it to a recent version?

**Comment by justadudewhohacks** [comment]
Closing for now, because of inactivity.

**Comment by nerkdesign** [comment]
Just for information, I had the same issue, I went to ./node_moduls/opencv-build/ and ran : 
#node install.js, after that, no more issue.

**Comment by gh0st2sh3ll** [comment]
Hi, if you are still facing this problem: 
Running `node install.js` did not work for me, but what did help was unlinking the brew formula `tesseract`: 

`brew uninstall tesseract`

It was one of the answers in this issue: 
[https://github.com/justadudewhohacks/opencv4nodejs/issues/401](url)
