### ISSUE TITLE
How about the Scene Text Recognition library?

### ISSUE THREAD

**Issue by JonasWestAlro** [justadudewhohacks/opencv4nodejs#38]
Hi, 

Thanks for this library :)

Do you know if you're going to support the Scene Text Recognition any time soon? We need to extract and decode text (or hex numbers) from a webcam picture.

**Comment by JonasWestAlro** [comment]
Yes, that was exactly what I was talking about :) 

To be honest, I am not sure that I understand the difference (I am fairly new to OpenCV) - but I need to detect and decode hex numbers that are printed on boxes?

I tried other libs like: https://github.com/desmondmorris/node-tesseract but it doesn't perform very well because of its language dependencies (I think). So I would like to do it all in OpenCV instead (also because the application needs OpenCV anyway).

**Comment by carlosen14** [comment]
I don't know much about bindings, but i know they use tesseract i did use that software weeks ago, it was kind of trikky to make all work.. Maybe it give you an idea..

https://github.com/openalpr/openalpr

**Comment by JonasWestAlro** [comment]
@carlosen14 Thanks. That could be useful as well. 

@justadudewhohacks  Would be great! Thanks 👍  :)

**Comment by justadudewhohacks** [comment]
I added some stuff from the contrib text module and also two basic usage examples for character recognition and word recognition from the trained BeamSearchDecoder CNN model. The features will be available when I published v2.14.

Good luck playing around with it, let me know if this was useful for your project =)

**Comment by justadudewhohacks** [comment]
New version is now published.
