### ISSUE TITLE
Build with facemark module fails for OpenCV 3.4.2 and 3.4.3

### ISSUE THREAD

**Issue by s1hofmann** [justadudewhohacks/opencv4nodejs#381]
I'm on macOS 10.12 with manually installed OpenCV 3.4.2.

When trying to install opencv4nodejs, with auto build disabled, the build exists with following error message:

```
In file included from ../cc/modules/face/Facemark.cc:4:
../cc/modules/face/FacemarkBindings.h:22:23: error: no member named 'addTrainingSample' in 'cv::face::Facemark'
      results = self->addTrainingSample(image, landmarks);
                ~~~~  ^
../cc/modules/face/FacemarkBindings.h:63:13: error: no member named 'getData' in 'cv::face::Facemark'
      self->getData(&data);
      ~~~~  ^
../cc/modules/face/FacemarkBindings.h:82:13: error: no member named 'getFaces' in 'cv::face::Facemark'
      self->getFaces(image, faces);
      ~~~~  ^
../cc/modules/face/FacemarkBindings.h:103:13: error: no member named 'training' in 'cv::face::Facemark'
      self->training();
      ~~~~  ^
../cc/modules/face/Facemark.cc:117:9: error: no member named 'setFaceDetector' in 'cv::face::Facemark'
      ->setFaceDetector((cv::face::FN_FaceDetector)detector, callback);
        ^
```

**Comment by justadudewhohacks** [comment]
Latest version running on Travis is OpenCV 3.4.1. Maybe they changed the facemark api from 3.4.1 to 3.4.2.

**Comment by rezakho** [comment]
Yes!
The facemark api is changed in OpenCV 3.4.2 and there is no way to install "opencv4nodejs" on mac now!!!
Do you have any plan for it?

**Comment by justadudewhohacks** [comment]
Simply install it with any other OpenCV version, like 3.4.1 or use the auto build.

I will adopt the OpenCV 3.4.2 related changes soon as I have some spare time.

**Comment by bhupathyap** [comment]
Fails in Ubuntu too. switched to version 3.4.1.work Fine

**Comment by justadudewhohacks** [comment]
OpenCV 3.4.2 and 3.4.3 support is coming in the following days.

**Comment by rezakho** [comment]
Thanks!
