### ISSUE TITLE
Detect custom object on image

### ISSUE THREAD

**Issue by DimaPateuk** [justadudewhohacks/opencv4nodejs#384]
@justadudewhohacks , really impressive tool, but i have got a question:
Is it possible to detect custom object on image, like poker cards:

![image](https://user-images.githubusercontent.com/7772191/44517765-36a5a080-a6d1-11e8-8fbf-623fb0c4dfcd.png)

**Comment by justadudewhohacks** [comment]
You can certainly think of an algorithm to implement the desired object detector with opencv.
