### ISSUE TITLE
Error: The specified module could not be found. [Windows 10]

### ISSUE THREAD

**Issue by Frixoe** [justadudewhohacks/opencv4nodejs#388]
I installed `opencv4nodejs` last night and it was working just fine but when I opened my laptop this morning and tried to `require("opencv4nodejs")` it gave me this error:

```
internal/modules/cjs/loader.js:718
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Users\suryansh\Desktop\d\node-opencv-test\node_modules\opencv4nodejs\build\Release\opencv4nodejs.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\suryansh\Desktop\d\node-opencv-test\node_modules\opencv4nodejs\lib\cv.js:17:8)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```

**I have looked at #84 and #50** and tried to fix the error by looking at the solutions provided but the only way I have been able to fix the error is **by downloading the module again.**

I don't think any of my System variable paths are wrong. *I do have another version of OpenCV in the directory: `C:\OpenCV24\opencv` which I do not think is causing the issue,* since I haven't created system variables for it.

**OS: Windows 10**
**System Variables:**
![issuecap](https://user-images.githubusercontent.com/21309909/44624799-9e641300-a8ac-11e8-9dff-e1bd9ffc4332.PNG)

**In my "Path":**
![issue2cap](https://user-images.githubusercontent.com/21309909/44624816-ff8be680-a8ac-11e8-9ae7-e36f8e84ea6c.PNG)

I hope you figure out why this is happening and let me know as soon as possible.

Downloading the module again and again just to fix a small error like this one, will be very tedious and unnecessarily time consuming.

**Thank you for your module and your time!**

**Comment by justadudewhohacks** [comment]
When that occurs, could you verify that `opencv4nodejs.node` still exist under the directory printed (it should)? Then you can open this file with dependency walker to figure out, which runtime dependencies are missing.

**Comment by Frixoe** [comment]
I opened up `opencv4nodejs.node` with *Dependency Walker* and this is what it said:
![issue3cap](https://user-images.githubusercontent.com/21309909/44628370-0e958780-a8f3-11e8-9088-d7d2bb32969e.PNG)

I have no idea what to make of this. I also don't know which dependency is missing.

**Comment by justadudewhohacks** [comment]
I think you can ignore the window specific stuff, scroll a bit down and look for dlls related to opencv. For example if the opencv runtime libraries are not found on your system, you might see something like this: 
![tmp](https://user-images.githubusercontent.com/31125521/44628547-f436ca80-a941-11e8-8e95-9ae8b08489c7.png)

**Comment by Frixoe** [comment]
I'm getting the exact same errors.

What do I do about these errors? Try to find these .dlls online and download them separately?

**Comment by justadudewhohacks** [comment]
No, these dlls should be located in your OpenCV bin folder, `OPENCV_BIN_DIR`, which you added to your system path.

By the way, since you are using an own build of OpenCV, I assume you set `OPENCV4NODEJS_DISABLE_AUTOBUILD=1` when you installed the package. Otherwise it will clone and build opencv from source, which will conflict with the OpenCV binaries in your system path.

**Comment by justadudewhohacks** [comment]
Then what kind of files are in that directory? The dlls should be there once you compiled or downloaded OpenCV.

**Comment by Frixoe** [comment]
These are the files in the directory:
![issue5cap](https://user-images.githubusercontent.com/21309909/44694787-78fa1500-aa24-11e8-877e-b782bc85e4a3.PNG)

**Comment by justadudewhohacks** [comment]
Okay, that's odd, apparently the opencv library opencv4nodejs is built against doesn't match your downloaded OpenCV version, otherwise it would look for opencv_world instead (opencv_world is just a compound library containing all the modules).

My guess is, that you build opencv4nodejs against the auto build by mistake (since dependency walker shows you version 3.4.1 dlls as well?, which is the verison, the auto build script installs currently).

I would suggest setting `OPENCV4NODEJS_DISABLE_AUTOBUILD=1` in your envs as well and then reinstall opencv4nodejs.

**Comment by Frixoe** [comment]
Alright, the error seems to be fixed now.

Thanks!

**Comment by zhangyi0424** [comment]
> 
> 
> No, these dlls should be located in your OpenCV bin folder, `OPENCV_BIN_DIR`, which you added to your system path.
> 
> By the way, since you are using an own build of OpenCV, I assume you set `OPENCV4NODEJS_DISABLE_AUTOBUILD=1` when you installed the package. Otherwise it will clone and build opencv from source, which will conflict with the OpenCV binaries in your system path.

It fixed when i change my system enviroment `OPENCV_BIN_DIR` and added it to the system path.Thanks~!
