### ISSUE TITLE
calibrateCamera() does not update distortionCoefficients array

### ISSUE THREAD

**Issue by andrewwalters** [justadudewhohacks/opencv4nodejs#392]
calibrateCamera() and calibrateCameraExtended() do not update the distortionCoefficients array that is passed in. Instead it retains whatever values were passed in.

I'm not familiar with unwrapping of arrays in the C++ bindings, but it seems like it is done by value and not by reference. I was able to verify that the underlying native OpenCV call was updating the coefficients, and I was able to see them by adding them to the return value, e.g. by adding the following to CalibrateCameraWorker::getReturnValue():

`Nan::Set(ret, Nan::New("dc").ToLocalChecked(), DoubleArrayConverter::wrap(distCoeffs));`

**Comment by justadudewhohacks** [comment]
Ahh I see, the distCoeff array is treated as input only here.

Your solution to return them in the output object is perfectly fine. Do you want to open a PR with that change?

**Comment by andrewwalters** [comment]
Submitted PR #393. While fixing, I found that stereoCalibrate() had a similar issue so fixed that too.
