### ISSUE TITLE
cv.Vec color and getRegion problems

### ISSUE THREAD

**Issue by marzochi** [justadudewhohacks/opencv4nodejs#402]
Hello, thanks for everything.

I've two problems.

1) I use Vec, Vec2, Vec3, Vec4 same problem with color. It show only one line true color. Filling with gray color.
```
CONTOUR_COLOR = new cv.Vec(0, 255, 0);
...
mRgba.drawContours( [contour], CONTOUR_COLOR, { thickness: CONTOUR_WIDTH } );
```
![image](https://user-images.githubusercontent.com/8195419/45263032-b00bf580-b42a-11e8-8c2d-68cb46ae2ed4.png)

When I try without electron same codes: ( I think problem with only electron )
![image](https://user-images.githubusercontent.com/8195419/45263361-8f469e80-b430-11e8-9b6e-042663aaa458.png)

2) I need some parts of image. So I use getRegion method but. Selected are (ROI) is here:
Firstly I drawed this area to mRgba mat. After I select with getRegion and into another canvas.
Selected area:
![Selected area](https://user-images.githubusercontent.com/8195419/45263063-64a61700-b42b-11e8-82ed-d4dad0a57832.png)
New canvas:
![canvas](https://user-images.githubusercontent.com/8195419/45263074-9919d300-b42b-11e8-9de3-6b903e2cfb96.png)

My codes:
```
region = new cv.Rect( 100, 100, 200, 400 );

mRgba.drawRectangle(
	region,
	new cv.Vec(0, 0, 255),
	2,
	cv.LINE_8
);

cropped = rotated.getRegion( region );

canvas2 = document.getElementById('processed');
canvas2.height = cropped.rows;
canvas2.width = cropped.cols;

var imgData = new ImageData(
	new Uint8ClampedArray(cropped.getData()),
	cropped.cols,
	cropped.rows
);

var ctx = canvas2.getContext('2d');
ctx.putImageData(imgData, 0, 0);
```
And result without electron:
![image](https://user-images.githubusercontent.com/8195419/45263373-f401f900-b430-11e8-983f-5f701dacd5f9.png)

Thanks in advance.

**Comment by justadudewhohacks** [comment]
Hi,

1: I am not sure, but I think you can't draw contours in a rgba Mat like that, since your color vector is also 3d. Simply convert the Mat to RGB or BGR, do the drawing, then convert it back to RGBA. If you want to maintain the alpha channel, you can extract the channels.

2: Not sure of what type `rotated` is, but I guess you are confusing the color channels here. By default the image data for a canvas has to be RGBA, but usually color matrices in OpenCV are in BGR format.

**Comment by marzochi** [comment]
Hi, thanks for reply. I didn't understand. Everything is right with using `node script.js` But running same codes with electron result is fail. I've completed protect bu not work with electron :)

![image](https://user-images.githubusercontent.com/8195419/45264949-10139380-b44d-11e8-9a32-ab65de69a521.png)

My codes

```
mRgba = img.channels === 1 ? img.cvtColor(cv.COLOR_GRAY2RGBA) : img.cvtColor(cv.COLOR_BGR2RGBA);
nGray = mRgba.cvtColor(cv.COLOR_BGR2GRAY);
mGray = nGray.bilateralFilter(BILATERAL_D, SIGMA_COLOR, SIGMA_SPACE);
mEdge = mGray.canny(CANNY_TRESHOLD1, CANNY_TRESHOLD2);
contours = mEdge.findContours(cv.RETR_EXTERNAL, cv.CHAIN_APPROX_NONE);
contour = contours.sort((c0, c1) => c1.area - c0.area)[0];

rotatedRect = contour.minAreaRect();

contourAngle = rotatedRect.angle;
if (rotatedRect.size.width < rotatedRect.size.height) {
	contourAngle = contourAngle + 90;
}

rotMat = cv.getRotationMatrix2D(rotatedRect.center, contourAngle);
rotated = mRgba.warpAffine(rotMat);


var imgData = new ImageData(
	new Uint8ClampedArray(rotated.getData()),
	rotated.cols,
	rotated.rows
);
var ctx = canvas.getContext('2d');
ctx.putImageData(imgData, 0, 0);
```

**Comment by marzochi** [comment]
I paste RGB graphic into original image. And I drawed a rectangle. I think this is best example for you.

![image](https://user-images.githubusercontent.com/8195419/45265055-8b297980-b44e-11e8-9305-0a0aec53a235.png)

```
	rotated.drawRectangle(
		new cv.Rect( 100, 100, 200, 200 ),
		new cv.Vec(0, 0, 255),
		5,
		cv.LINE_8
	);
	area = rotated;
```

**Comment by piercus** [comment]
@marzochi i think your issue is related to #480 

you cannot use `.getData()` after `.getRegion(rect)`

to fix this, you need to use `mat.getRegion(rect).copyTo(otherMat)` and then `otherMat.getData()`

Please confirm it fixes your problem

**Comment by marzochi** [comment]
@piercus Thanks for comment. But I'll solve the problem another way; I save the image as file, then show as img on html like this:
![image](https://user-images.githubusercontent.com/8195419/50826724-85389c00-134d-11e9-8e34-5abe357cc128.png)

I'll try thanks a lot
