### ISSUE TITLE
video stream + face recognition

### ISSUE THREAD

**Issue by geoffreyp** [justadudewhohacks/opencv4nodejs#410]
Hello,
can we open a video stream and use face recognition system (view in example with simple image) with this lib ?

**Comment by justadudewhohacks** [comment]
Yep, face detection examples from video stream, webcam stream etc are [here](https://github.com/justadudewhohacks/opencv4nodejs/tree/master/examples/faceDetect). For face recognition, you can either try your luck with the FaceRecognizers from opencv (face recognition examples), or if you need robust face recognition, you can use opencv4nodejs with [face-recognition.js](https://github.com/justadudewhohacks/face-recognition.js).

**Comment by geoffreyp** [comment]
thanks !
