### ISSUE TITLE
Auto Install: Could not find any instance of Visual Studio

### ISSUE THREAD

**Issue by cyluxx** [justadudewhohacks/opencv4nodejs#413]
I have followed the installations instructions for the opencv4nodejs auto build:
1. download and install cmake
2. npm install --global windows-build-tools
3. npm install --save opencv4nodejs

However the installation is interrupted after the source files were successfully checked out and it seems that Visual Studio is not found:
```
CMake Error at CMakeLists.txt:127 (project):
Generator
Visual Studio 15 2017 Win64
could not find any instance of Visual Studio.
```
Am I missing something crucial here?

**Comment by cyluxx** [comment]
Seems to work for me now.

First, I uninstalled the windows build tools and removed the node package.

Then I reinstalled with the **--vs2015** tag:
```
npm install --global windows-build-tools --vs2015
```

**Comment by thug1705** [comment]
System restart is required also.
