### ISSUE TITLE
SimpleBlobDetector

### ISSUE THREAD

**Issue by cotejp** [justadudewhohacks/opencv4nodejs#42]
It would be awesome to have bindings for SimpleBlobDetector. This is the kind of higher level object that allows a variety of opportunities.

Thanks for your great work!

**Comment by justadudewhohacks** [comment]
SimpleBlobDetector is now available. Let me know if something is not working as intended or if you need something else.

**Comment by cotejp** [comment]
Wow! That was amazingly fast! Thanks a lot. I'll give it a try this week and get back to you. Cheers!

**Comment by justadudewhohacks** [comment]
Closing this issue. Let me know if you experience problems with the added bindings.
