### ISSUE TITLE
Is there any documents to use the internal function?

### ISSUE THREAD

**Issue by hscspring** [justadudewhohacks/opencv4nodejs#428]
i want to use `cv.drawDetection` to draw box for faces and i also want to tag something beside the box. 
the reminder is `drawDetection(img: Mat, inputRect: Rect, opts?: DrawDetectionParams)`, i'm not sure how to use `opts`.

i have found there are not any clear document to refer this. 

would anybody can help?

**Comment by fildaniels** [comment]
Hi
Have a look to the file cv.d.ts within lib/typings :

export type DrawParams = {
  thickness?: number;
  lineType?: number;
  color?: Vec3;
}

export interface DrawDetectionParams extends DrawParams {
  segmentFraction?: number;
}

And have a look to the OpenCV documentation on drawing lines for the explanation of each option (I just guess the last one « segmentFraction » is the « shift » parameter of the line function but I didn’t test...).

**Comment by justadudewhohacks** [comment]
Yes, exactly what @fildaniels said. "segmentFraction" is basically the length of the the lines at the rectangle corners. Since it's a fraction of the entire rectangle width / height it should be a value between 0 and 1.

**Comment by hscspring** [comment]
thank @justadudewhohacks  and @fildaniels very much, i've solved it.  
those opts params can be set in an object like this 
`cv.drawDetection(img, new cv.Rect(x,y,w,h), {thickness: 1, clolor: new cv.Vec3(255, 0, 0)});  // this color means blue`.  
and  i also found this [doc](https://justadudewhohacks.github.io/opencv4nodejs/docs/) somewhat helps.
