### ISSUE TITLE
Setting VideoCapture to device 0 instantly crashes program. Surrounding with try-catch doesn't help.

### ISSUE THREAD

**Issue by KolCrooks** [justadudewhohacks/opencv4nodejs#430]
I am trying to use real time video capture using electron. I am trying to set video capture from the main process and no matter what it instantly crashes the program.
Here is the code that crashes it:
```javascript
/**
 * @summary Set the capture device for the camera object
 * @param {Int} device The device id 
 */
var setCamera = (device) => {
    try{
        capDevice = cv.VideoCapture(device);
        return {
            res: true,
            device: device,
            error: ""
        }
    }catch(e){
        return {
            res: false,
            device: device,
            error: e.message
        } 
    }
}
```
I am passing in 0 as the device id and it crashes it without any message. When i try and set it as different id's it just gives me the error `VideoCapture::New - failed to open capture`. I am not sure if this is because the electron main process doesn't like it or what. I am on linux fyi.

Update! I have been able to get an error message and it still doesn't help. Here is the error:
```Error
electron --inspect-brk=19767 .: ../../nan/nan_object_wrap.h:55: void Nan::ObjectWrap::Wrap(v8::Local<v8::Object>): Assertion `object->InternalFieldCount() > 0' failed.
Crash dump id: 7bb81f09-ab62-441b-b23c-26c9ccad4336
```

**Comment by allexzander** [comment]
Hey @KolCrooks have you found the solution yet? I am looking into using this module for webcam shots, but stumbled upon this issue.

I've noticed you are not using 'new' in your code, when creating the VideoCapture device, may it be the cause of your issue?

In the landing page of this module the example shows usage of VideoCapture with 'new' keyword. Like this:

// open capture from webcam
```
const devicePort = 0;
const wCap = new cv.VideoCapture(devicePort);
```

in oppose of your way of usage 
`capDevice = cv.VideoCapture(device);`

Would this work for you? Or, maybe I just got confused here, and there's really an issue with this part of module's functionality?

**Comment by KolCrooks** [comment]
> Hey @KolCrooks have you found the solution yet? I am looking into using this module for webcam shots, but stumbled upon this issue.
> 
> I've noticed you are not using 'new' in your code, when creating the VideoCapture device, may it be the cause of your issue?
> 
> In the landing page of this module the example shows usage of VideoCapture with 'new' keyword. Like this:
> 
> // open capture from webcam
> 
> ```
> const devicePort = 0;
> const wCap = new cv.VideoCapture(devicePort);
> ```
> in oppose of your way of usage
> `capDevice = cv.VideoCapture(device);`
> 
> Would this work for you? Or, maybe I just got confused here, and there's really an issue with this part of module's functionality?

That worked, Thanks so much!
