### ISSUE TITLE
Please help - Could not install opencv4nodejs

### ISSUE THREAD

**Issue by dqlambor** [justadudewhohacks/opencv4nodejs#431]
Hi Bro,
I tried to install both opencv4nodejs and opencv-build using npm, but still get  the same error:

Checking out files: 100% (5967/5967), done.
-- Selecting Windows SDK version 10.0.17134.0 to target Windows 6.1.7601.
CMake Error at CMakeLists.txt:127 (project):
  Failed to run MSBuild command:

    C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/
Bin/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 15.8.169+g1ccb72aefa for .NET Framework
    Copyright (C) Microsoft Corporation. All rights reserved.

    MSBUILD : error MSB1009: Project file does not exist.
    Switch: VCTargetsPath.vcxproj

  Exit code: 1

-- Configuring incomplete, errors occurred!
See also "C:/Windows/System32/node_modules/opencv-build/opencv/build/CMakeFiles/
CMakeOutput.log".
ERR! child process exited with code 1
npm WARN system32@1.0.0 No description
npm WARN system32@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv-build@0.0.15 install: `node ./install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv-build@0.0.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2018-10-16T10_05_33_1
95Z-debug.log

C:\Windows\System32>

PLease help to look at this.
Many thanks,

**Comment by justadudewhohacks** [comment]
I updated the issue template. If this is still an issue, please recreate it respecting the template.
