### ISSUE TITLE
cv.VideoCapture size

### ISSUE THREAD

**Issue by muhammadsamir11** [justadudewhohacks/opencv4nodejs#44]
How can i define cv.VideoCapture size

**Comment by justadudewhohacks** [comment]
I didn't implement CAP_PROPs yet, will add them in a sec.

**Comment by justadudewhohacks** [comment]
Published a new version. You should be able to set VideoCapture properties now. For instance for frame size:
`cap.set(cv.CAP_PROP_FRAME_WIDTH, ... );`
`cap.set(cv.CAP_PROP_FRAME_HEIGHT, ... );`
