### ISSUE TITLE
Error: The specified module could not be found.

### ISSUE THREAD

**Issue by adwellj** [justadudewhohacks/opencv4nodejs#440]
Like many others, I get the below error. However, this works in some projects and not in others.

What's really interesting (and likely telling of the root issue) is that if I execute 'node app.js' from a cmd window it works, but not if I do that same command through a cmd window within VS Code. For this reason, I'm guessing this is a x86 vs. x64 process issue perhaps.

Thoughts?

Error: The specified module could not be found.
\\?\C:\Users\josha\Source\repos\opencv_test\node_modules\opencv4nodejs\build\Release\opencv4nodejs.node
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\josha\Source\repos\opencv_test\node_modules\opencv4nodejs\lib\cv.js:17:8)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)

**Comment by Wawy123** [comment]
I get the same error everytime when i run the code

**Comment by justadudewhohacks** [comment]
That's odd, are you using an x86 version of vscode?

**Comment by adwellj** [comment]
No, but I was using an x86 version of CMake. I was doing this because I had previously gotten issues about CMake not being found, but I'm guessing that was due to a PATH issue.

I just got it working now, with the help of your Docker strategy (global install) and going through the [node-gyp install instructions](https://github.com/nodejs/node-gyp/blob/master/README.md#on-windows) to make sure everything is perfect on that end.

I uninstalled CMake and installed the x64 version. Rebooted and verified "cmake --version" worked.
I also noticed that Visual Studio Build Tools was failing (I already have Visual Studio 2015 and 2017 installed), so I did `npm config set msvs_version 2017`.
I then decided to install globally and set NODE_PATH, so that once I had it installed for one project, I didn't have to worry about it getting messed up again.

So far all of my test projects are running. I'm going to verify on a couple more machines tonight and tomorrow, and will update this issue.

**Comment by Wawy123** [comment]
So i reinstalled node.js, opencv and cmake for like 3 times and i still get the error


C:\tests>node main.js
internal/modules/cjs/loader.js:736
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\tests\node_modules\opencv4nodejs\build\Release\opencv4nodejs.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:736:18)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\tests\node_modules\opencv4nodejs\lib\cv.js:17:8)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)

I don't really know what to do at this point. Maybe you can povide something so i can check that my enviromental variables point to the correct directory?

**Comment by justadudewhohacks** [comment]
An error during process.dlopen indicates, that you are missing runtime dependencies. Most likely the path to the OpenCV binaries is not in your system path?

**Comment by Wawy123** [comment]
There are two bin folders:

C:\OpenCV\opencv\build\bin
C:\OpenCV\opencv\build\x64\vc15\bin


i tryed both of them.

echo %OPENCV_BIN_DIR% (in cmd) returned the right path but when i ran the code that requires opencv4nodejs i got the same error.

**Comment by justadudewhohacks** [comment]
I would suggest having a look at this issue: #388

**Comment by Wawy123** [comment]
Well...

I did all the things as in the #388 , opened opencv4nodejs.node with dependency walker and all that seems to be missing is: 
![capture](https://user-images.githubusercontent.com/18677535/47718727-64671280-dc49-11e8-9fb3-f714f5db7521.PNG)

i also deleted old version of opencv and installed version 3.4.3, but no success (i set OPENCV4NODEJS_DISABLE_AUTOBUILD to 1) 

Thanks for your time! I will try to figure something out i guess

**Comment by Wawy123** [comment]
I will try updating my windows since im running win 7 with no updates... will take approx. 2h

**Comment by Wawy123** [comment]
UPDATE! 
So i went to the other pc(with win7 but updated) and i installed everything and it worked! will try on my machine now

**Comment by adwellj** [comment]
@Wawy123, do you happen to have Visual Studio already installed?
I believe that's what was causing a problem for me when using the auto install option. What I believe helped me was to `npm config set msvs_version 2017` as detailed in the node-gyp install directions.

I kept trying to the manual install, but was never able to get it to work.

**Comment by adwellj** [comment]
@Wawy123, here's a gist that I just created that documented the steps I used to resolve my issues. Hopefully it will be of some help. https://gist.github.com/adwellj/61e7f202bcfe5b96f312293e9c812ca6

Note that I used a global install of opencv4nodejs for my projects, so drop the `-g` flag if you don't want to do that.

**Comment by justadudewhohacks** [comment]
yes I have vs2017 installed, sometimes setting up nodegyp properly can be nasty

**Comment by adwellj** [comment]
Followed the same process on a couple other machines and all have worked correctly. Closing this issue.

Thanks.

**Comment by DharmnathShinde** [comment]
woked fine for me just uninstall the node and again install then tried .
