### ISSUE TITLE
opencv4nodejs system cannot find the path specified in windows

### ISSUE THREAD

**Issue by Parameshvadivel** [justadudewhohacks/opencv4nodejs#442]
opencv4nodejs: npm install --save opencv4nodejs in command prompt. 

  -- Installing: C:/Users/Vaishnav/Desktop/pyrky_nodejs_poorani/pyrky_nodejs_poorani/node_modules/opencv4nodejs/node_mo
  dules/opencv-build/opencv/build/etc/lbpcascades/lbpcascade_silverware.xml
FinalizeBuildStatus:
  Deleting file "x64\Release\INSTALL\INSTALL.tlog\unsuccessfulbuild".
  Touching "x64\Release\INSTALL\INSTALL.tlog\INSTALL.lastbuildstate".
Done Building Project "C:\Users\Vaishnav\Desktop\pyrky_nodejs_poorani\pyrky_nodejs_poorani\node_modules\opencv4nodejs\n
ode_modules\opencv-build\opencv\build\INSTALL.vcxproj" (default targets).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:40.18
ERR! opencv\samples\winrt_universal\VideoCaptureXAML\video_capture_xaml\video_capture_xaml.Shared\video_capture_xaml.Shared.vcxitems.filters - The system cannot find the path specified.
opencv\samples\winrt_universal\VideoCaptureXAML\video_capture_xaml\video_capture_xaml.Windows\Assets\haarcascade_frontalface_alt.xml - The system cannot find the path specified.
opencv\samples\winrt_universal\VideoCaptureXAML\video_capture_xaml\video_capture_xaml.Windows\video_capture_xaml.Windows.vcxproj.filters - The system cannot find the path specified.
opencv\samples\winrt_universal\VideoCaptureXAML\video_capture_xaml\video_capture_xaml.Windows\video_capture_xaml.Windows_TemporaryKey.pfx - The system cannot find the path specified.
opencv\samples\winrt_universal\VideoCaptureXAML\video_capture_xaml\video_capture_xaml.WindowsPhone\Assets\SplashScreen.scale-240.png - The system cannot find the path specified.
opencv\samples\winrt_universal\VideoCaptureXAML\video_capture_xaml\video_capture_xaml.WindowsPhone\Assets\Square71x71Logo.scale-240.png - The system cannot find the path specified.
opencv\samples\winrt_universal\VideoCaptureXAML\video_capture_xaml\video_capture_xaml.WindowsPhone\video_capture_xaml.WindowsPhone.vcxproj - The system cannot find the path specified.
opencv\samples\winrt_universal\VideoCaptureXAML\video_capture_xaml\video_capture_xaml.WindowsPhone\video_capture_xaml.WindowsPhone.vcxproj.filters - The system cannot find the path specified.
opencv\samples\winrt_universal\VideoCaptureXAML\video_capture_xaml\video_capture_xaml.WindowsPhone\video_capture_xaml.WindowsPhone_TemporaryKey.pfx - The system cannot find the path specified.

npm WARN firebase-functions@2.1.0 requires a peer of firebase-admin@~6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN pyrky@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv-build@0.0.15 install: `node ./install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv-build@0.0.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Vaishnav\AppData\Roaming\npm-cache\_logs\2018-10-30T11_27_02_194Z-debug.log

**Comment by justadudewhohacks** [comment]
Not sure what you are trying to do, the samples are not built by the autobuild.

**Comment by NiveditaKhoch** [comment]
brew install cmake and . then try to run this it should work
