### ISSUE TITLE
ellipse function is missing

### ISSUE THREAD

**Issue by Gacha20** [justadudewhohacks/opencv4nodejs#443]
I used this example : https://docs.opencv.org/master/db/d28/tutorial_cascade_classifier.html 

But the problem is that the ellipse function is not available.
Is there an alternative ?

**Comment by justadudewhohacks** [comment]
Its just called drawEllipse: mat.drawEllipse(...): [docs](
https://github.com/justadudewhohacks/opencv4nodejs/blob/c07bb63ea33a93ef618bee4026f602be855a80a8/lib/typings/Mat.d.ts#L124-L125)
