### ISSUE TITLE
cv.Mat from screen data?

### ISSUE THREAD

**Issue by Wawy123** [justadudewhohacks/opencv4nodejs#446]
I am working on a project where i would get screen data, convert it to cv.Mat and then display it(at somewhat decent framerate maybe).

Is there any function in opencv4nodejs to read screen as cv.Mat or image?

**Comment by Wawy123** [comment]
I would make something like this at the end: https://www.youtube.com/watch?v=7YC8A0j1MXA  - but this is in python

**Comment by Wawy123** [comment]
Ok :) i tryed capturing screen with robotjs but i will need to write something to re-arrange the values in the array because openCV uses b,g,r instead of rgb correct?

**Comment by adwellj** [comment]
@Wawy123 I do believe that's correct.
I think you'll need to do something like `let imgRGB = imgBGR.cvtColor(cv.COLOR_BGR2RGB);`

**Comment by adwellj** [comment]
Some examples of conversion are near the bottom of the README.
https://github.com/justadudewhohacks/opencv4nodejs#useful-mat-methods
https://github.com/justadudewhohacks/opencv4nodejs#drawing-a-mat-into-html-canvas

At the top of 'Drawing a Mat into HTML canvas it shows converting to RGBA, so I'm assuming that the constant for converting to RGB is the same, but drop the 'A'.

**Comment by Wawy123** [comment]
I found a workaround! Thanks for your time

**Comment by asd59422** [comment]
@idkRage 
bro~ I need your help, do you have any contact information?

**Comment by asd59422** [comment]
> 我最後會做類似的事情：[https://www.youtube.com/watch?v](https://www.youtube.com/watch?v=7YC8A0j1MXA) =7YC8A0j1MXA - 但這是使用 python 寫的

@idkRage are you still there~
