### ISSUE TITLE
Detect blurry images with Laplacian Variance

### ISSUE THREAD

**Issue by G33kLabs** [justadudewhohacks/opencv4nodejs#448]
Hello !

I'm trying to adapt that : `cv2.Laplacian(image, cv2.CV_64F).var()` from [https://www.pyimagesearch.com/2015/09/07/blur-detection-with-opencv/](https://www.pyimagesearch.com/2015/09/07/blur-detection-with-opencv/) 

For yet i'm in : `_frame.laplacian(cv.CV_64F)`, but I don't find variance function to Mat structure.
=> Is there one tip to get that calculation ?

Thanks !

**Comment by justadudewhohacks** [comment]
Hmm maybe this is what you are looking for? http://answers.opencv.org/question/53985/is-there-a-built-in-function-to-calculate-the-variance-of-a-cvmat/

Bindings for Mat.meanStdDev are implemented.

**Comment by G33kLabs** [comment]
Thank you ! Yes it was a part of the answer @justadudewhohacks :)

Here is how the g33k of my team done that : 
```
# Convert to gray
_imgGray = _img.bgrToGray()

# Detect blurry level
_laplacian = _imgGray.laplacian(cv.CV_64F)

# Get the standard deviation
_meanStdDev = _laplacian.meanStdDev()
_stdDevArray = _meanStdDev.stddev.getDataAsArray()
_stdDeviation = _stddevarray[0]

# Get the variation
_variation = Math.pow(_stdDeviation, 2)
```

And has expected, the threesold of 100 is pertinent

**Comment by jazozaya** [comment]
@G33kLabs - Thanks for sharing the code!

**Comment by juvaly** [comment]
@G33kLabs thanks for the code!

I've encountered the following issue.

The line:
```_stdDeviation = _stddevarray[0]``` outputs an array of number, which cannot be passed into the first parameter of Math.pow which expects a number and not an array of number.

Should it be ```_stdDeviation = _stddevarray[0][0]``` instead?
