### ISSUE TITLE
[Install Failed on Windows 10] ERR! opencv_contrib\modules\hdf - directory not empty

### ISSUE THREAD

**Issue by nombrekeff** [justadudewhohacks/opencv4nodejs#449]
Versions:
* using `npm@6.1.0`
* using `node@v8.9.1`
* using `windows10@1803`

I followed the requirements listed here: https://github.com/justadudewhohacks/opencv4nodejs#on-windows

Installed with: `npm install opencv4nodejs --save`
Im trying to install in windows 10, and it seams it does everything ok, it outputs:
```bash
Compiled Correctly
    0 Warning(s)
    0 Errors
```
But after this it shows:

```bash
ERR! opencv_contrib\modules\hdf - directory is not empty

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv-build@0.0.15 install: `node ./install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv-build@0.0.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Any idea what the problem could be?

Thanks!

**Comment by nombrekeff** [comment]
I just tried doing it again, now it has gone a bit further:
now it outputs:
```
ERR! opencv\doc\TUTORI~1\INTROD~1\ANDROI~1 - directory is not empty

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv-build@0.0.15 install: `node ./install.js`
npm ERR! Exit status 1```

**Comment by nombrekeff** [comment]
Hi, I tested in an empty project, first time didnt work either, but second time it was successfull!

I will try to gather some more info on what was the issue and post it here, in case it happens again, if I find anything.

Cheers! Great lib man, migrated from node-opencv, this is way more mantained and documented!

**Comment by oyyd** [comment]
You can run `npm install opencv-build` separately to see if it could successfully install OpenCV. I have no idea what does `directory is not empty` mean though.

**Comment by nombrekeff** [comment]
Okey thanks! I will check that.
I will close this issue for now!

**Comment by sayhicoelho** [comment]
i'm facing with the same issue.
