### ISSUE TITLE
Support with OpenCV.js (HTML5 canvas)

### ISSUE THREAD

**Issue by Gacha20** [justadudewhohacks/opencv4nodejs#457]
Is the library implements a support for OpenCV.js ?

> https://docs.opencv.org/3.4/dd/d00/tutorial_js_video_display.html 

It would allow us to manage openCV with HTML5 canvas.

**Comment by justadudewhohacks** [comment]
OpenCV.js provides some OpenCV modules as a wasm binary, which runs in the browser. opencv4nodejs is targetting nodejs and doesn't run in the browser. These are two completely different things.
