### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by vbh25** [justadudewhohacks/opencv4nodejs#460]
I have installed cmake & windows build tools on windows 10.
Where should we run this command?
I am trying to run below command inside opencv4nodejs-master folder. 
npm install --save opencv4nodejs

**Comment by vbh25** [comment]
can you help in installation?

**Comment by justadudewhohacks** [comment]
The error message pretty much says it. Why are you installing opencv4nodejs in the opencv4nodejs folder. I dont understand what you are trying to do.

**Comment by vbh25** [comment]
Sorry, beginner in nodejs. 
opencv4nodejs installation successful. 
Then ran npm i in open opencv4nodejs-master folder.
How can I run the examples?

**Comment by justadudewhohacks** [comment]
cd into the examples folder, type npm install and then run one of the examples, e.g. node matchFeatures.js.

**Comment by vbh25** [comment]
Thanks for your response.

Facing an issue in running facemark example.
Error: could not find landmarks model.

Other examples are running fine.

**Comment by justadudewhohacks** [comment]
You need to download the model (see error message). Closing here, since installation issue is solved.

**Comment by vbh25** [comment]
Ok, thank you

**Comment by veetechh** [comment]
There was no "face" folder in data folder. So I created "face" folder & copied the lbfmodel.yaml there.
And ran node facemark.js.
Still the error exists!!

**Comment by sureshaHospet** [comment]
> Sorry, beginner in nodejs. opencv4nodejs installation successful. Then ran npm i in open opencv4nodejs-master folder. How can I run the examples?

Could you please let me know, which commands/steps used to fix "npm ERR! Refusing to install package with name "opencv4nodejs" under a package"

**Comment by UrielCh** [comment]
try the last version: https://github.com/UrielCh/opencv4nodejs
