### ISSUE TITLE
stream video from webcam

### ISSUE THREAD

**Issue by fajaryoedha** [justadudewhohacks/opencv4nodejs#465]
can you give me simple code for read video from webcam and show using imshow, i have tried but the picture is black white and not good

**Comment by bookjan** [comment]
I think you can find it out on "examples" folder.

**Comment by wbern** [comment]
@fajaryoedha let us know if anything confuses you in the examples sections!

**Comment by intensite** [comment]
Hello,  if you could provide an entry point in the example section or a simple readme file on how to use the examples.  Right now I am a bit overwhelmed.  Something that would allow us to validate all the components are correctly installed would be a great start.  Then an "heloworld" type of minimal script.

**Comment by lucasemiliomf** [comment]
You can check an example of streaming in the example "utils.js". Your webcam is an object of the type VideoCapture, to capture an image you use the function read() and after that you can treat it as a Mat object. To stream it just add a loop and keep reading until a stop condition. I think it's clear in the example, but feel free to ask anything.
