### ISSUE TITLE
VideoWriter

### ISSUE THREAD

**Issue by illyah** [justadudewhohacks/opencv4nodejs#48]
Will there be a wrapper for cv::VideoWriter?

**Comment by justadudewhohacks** [comment]
Sure, pretty soon.

**Comment by illyah** [comment]
Thank you!

**Comment by justadudewhohacks** [comment]
VideoWriter is available now. You should be able to use it similarly to the original opencv API:
```
  const code = cv.VideoWriter.fourcc('MJPG');
  const file = './video.avi';
  const fps = 24;
  const writer = new cv.VideoWriter(file, code, fps, new cv.Size(800, 600));
```
Let me know if there are any issues. Good luck!
