### ISSUE TITLE
`mat.getRegion(rect).getData()` is different than `mat.getRegion(rect).getDataAsArray()`

### ISSUE THREAD

**Issue by piercus** [justadudewhohacks/opencv4nodejs#480]
## Scenario

```javascript
const matC3 = new cv.Mat([
   [[255, 255, 255], [255, 255, 255], [255, 255, 255]],
   [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
], cv.CV_8UC3);
const region = matC3.getRegion(new cv.Rect(0, 0, 2, 2));
const buf = region.getData();
console.log(new Uint8Array(buf)[6], region.getDataAsArray()[1][0][0])
```

## Actual
prints 

```
255, 0
```

## Expected

should print

```
0, 0
```

May be related to #402 ?

**Comment by piercus** [comment]
This problem comes from opencv library

From https://stackoverflow.com/a/12931889

> Warning: In this case, miniMat is a subregion of imgray. This means that if you modify the former, you also modify the latter. Use miniMat.copyTo(anotherMat) to avoid this.

So the fix is to do `.copyTo()` to use a new Matrix

```javascript
const matC3 = new cv.Mat([
   [[255, 255, 255], [255, 255, 255], [255, 255, 255]],
   [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
], cv.CV_8UC3);

const region = new cv.Mat(2,2,cv.CV_8UC3);
matC3.getRegion(new cv.Rect(0, 0, 2, 2)).copyTo(region);
const buf = region.getData();
console.log(new Uint8Array(buf)[6], region.getDataAsArray()[1][0][0])
```

Anyway, i think this is misleading and in this specific situation `getData()` should either : 
* return a 3x2 buffer
* throw an error 

@justadudewhohacks what do you think ?

**Comment by justadudewhohacks** [comment]
Ahh ok, I see what you mean. I agree that this is kind of confusing, but it's also behaves consistently with how OpenCV does.

We could atleast document this somehow in the readme, I feel like `mat.getRegion` does cause a lot of misconceptions, if one is not aware of what it's actually doing.

**Comment by piercus** [comment]
I think `getData()` should raise an error if `mat.data` size is not consistent with `mat.cols` and `mat.rows`.
Because the output is inconsistent in this case

I'm not sure how we can find the size of `mat.data` in `GetDataWorker` without using `mat.cols` or `mat.rows`.

It is possible ?

**Comment by justadudewhohacks** [comment]
Hmm, I don't think it's possible without checking for cols and rows. Is there actually any way to deal with this in OpenCV?
