### ISSUE TITLE
Creating a Mat from VideoCapture frame

### ISSUE THREAD

**Issue by domvon** [justadudewhohacks/opencv4nodejs#486]
Great package! Question, is there a way to create a Mat from a VideoCapture frame? I am trying to pass that frame mat to detector.detect(frame_mat) to get the keypoints. Thanks.

**Comment by adwellj** [comment]
Check the lower half of the IO section: https://github.com/justadudewhohacks/opencv4nodejs#io

.read / .readAsync return a mat (or a Promise / callback with a mat).

// open capture from webcam
const devicePort = 0;
const wCap = new cv.VideoCapture(devicePort);

// open video capture
const vCap = new cv.VideoCapture('./path/video.mp4');

// read frames from capture
const frame = vCap.read();
vCap.readAsync((err, frame) => {
  ...
});

// loop through the capture
const delay = 10;
let done = false;
while (!done) {
  let frame = vCap.read();
  // loop back to start on end of stream reached
  if (frame.empty) {
    vCap.reset();
    frame = vCap.read();
  }

  // ...

  const key = cv.waitKey(delay);
  done = key !== 255;
}

**Comment by domvon** [comment]
Never mind, I kept getting this error "FeatureDetector::Detect - Error: expected argument 0 to be of type Mat" which seemed to imply that a frame is not a Mat, but it was actually due to a typo.
