### ISSUE TITLE
npm install Fails

### ISSUE THREAD

**Issue by ShadabFaiz** [justadudewhohacks/opencv4nodejs#487]
Hope this fits with the new temple issue.

NPM Install Fails.

Error
``` node
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring incomplete, errors occurred!
See also "/home/Faiz/Organization/Repos/Image_Analysis/using_opencv4nodejs/node_modules/opencv-build/opencv/build/CMakeFiles/CMakeOutput.log".
See also "/home/Faiz/Organization/Repos/Image_Analysis/using_opencv4nodejs/node_modules/opencv-build/opencv/build/CMakeFiles/CMakeError.log".
ERR! child process exited with code 1 (for more info, set '--loglevel silly') 
npm WARN using_opencv4nodejs@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv-build@0.0.16 install: `node ./install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv-build@0.0.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/Faiz/.npm/_logs/2019-01-10T05_14_47_127Z-debug.log
```

cmake is installed.
Node ver: 8.12.0
OS: Fedora 28 64-bit

**Comment by SilentViking** [comment]
I had the same issue as you on Fedora 29.   Make sure you follow the linux\unix section for https://github.com/nodejs/node-gyp. I was missing gcc-c++.

**Comment by ShadabFaiz** [comment]
> I had the same issue as you on Fedora 29. Make sure you follow the linux\unix section for https://github.com/nodejs/node-gyp. I was missing gcc-c++.

Yeah. That was the issue.

**Comment by primalAbe** [comment]
Anyone face this issue with Windows 10? Noting on previous comments: if it's a missing gcc-c++ issue, I don't know how that would be an issue as I have successfully installed node-gyp, globally. 

Also, I've been able to successfully use opencv4nodejs using the instructions provided with Docker and didn't face this issue. 

I'm trying to install this opencv4nodejs within a Firebase functions directory after having initialized the Firebase app.

Has anyone been able to do this successfully?

**Comment by ShadabFaiz** [comment]
I'm not sure if node-gyp install gcc-c++ internally, but installing it manually did fix my problem

**Comment by primalAbe** [comment]
I finally got it to work locally. Alas, it was for nothing because deploying firebase functions will fail because it can't compile the c++ files with cmake since cmake is not supported by firebase (i.e., the firebase VM does not have it installed and it cannot be installed manually).

**Comment by 4sh3** [comment]
I have this problem with OSX.

**Comment by yashprit** [comment]
Facing same issue on 
Node: 10.10.0
NPM: 6.4.1
Electron: 5.0.7
MacOS Mojave
