### ISSUE TITLE
Camera Calibration

### ISSUE THREAD

**Issue by fouber** [justadudewhohacks/opencv4nodejs#490]
I'm working on [camera calibration](https://docs.opencv.org/3.0-beta/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html), need to use the ``remap`` and ``initUndistortRectifyMap`` function, but I have noticed that these functions are currently not supported. Is there any alternative?

**Comment by originals** [comment]
The function undistort is available:

> The function is simply a combination of initUndistortRectifyMap() (with unity R ) and remap() (with bilinear interpolation). See the former function for details of the transformation being performed.

I am trying to use that now, only the result so far is not what i am expecting ( big distortion, instead of small correction)

**Comment by fouber** [comment]
@originals thanks

**Comment by Petersdavis** [comment]
@originals Will this approach cache the results from initUndistortRectifyMap()?  We are using undistort pretty frequently on a jetson nano and are finding it takes about 200~300 ms per frame.
