### ISSUE TITLE
Recipe for building for AWS lambda with package size limit

### ISSUE THREAD

**Issue by karlbernard2** [justadudewhohacks/opencv4nodejs#495]
Has anyone successfully built a package for AWS lambda distribution?

The following closed issue discuss that subject, however the resulting package size issue has not beed addressed:

https://github.com/justadudewhohacks/opencv4nodejs/issues/113

I've followed the recipe for building native module here:
https://aws.amazon.com/blogs/compute/nodejs-packages-in-lambda/

But the resulting node_modules ends up being over 1gb, leading to this error from Lambda:
"Unzipped size must be smaller than 262144000 bytes"

**Comment by mtford90** [comment]
After a frustrating couple of days here is the layer I came up with for lambdas running 10.15: https://dropfile.nl/get/hK96J

It's quite large (unzips to 159mb...) but thankfully still remained within the limits for my lambda. Might be possible to reduce the size further by deleting unused libraries etc from the node_modules.

**Comment by barnc** [comment]
@mtford90 Any chance you still have a copy of that layer? That link has unfortunately expired.

**Comment by garysun-webdev** [comment]
> After a frustrating couple of days here is the layer I came up with for lambdas running 10.15: https://dropfile.nl/get/hK96J
> 
> 
> 
> It's quite large (unzips to 159mb...) but thankfully still remained within the limits for my lambda. Might be possible to reduce the size further by deleting unused libraries etc from the node_modules.
> 
> 
> 
> 

Can you share the copy of your layer again? The link has been expired. Thanks a lot.
