### ISSUE TITLE
Auto Build Failed - node-gyp rebuild

### ISSUE THREAD

**Issue by davidb1** [justadudewhohacks/opencv4nodejs#504]
Getting the following when using auto build (SyntaxError: invalid syntax)

[2019-02-13T23_10_33_460Z-debug.log](https://github.com/justadudewhohacks/opencv4nodejs/files/2862617/2019-02-13T23_10_33_460Z-debug.log)

# Error Message

```
Done Building Project "C:\Users\-\Documents\-\node_modules\opencv-build\opencv\build\INSTALL.vcxproj" (default targets).


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:07.45

> opencv4nodejs@4.14.1 install C:\Users\-\Documents\-\node_modules\opencv4nodejs
> node-gyp rebuild


C:\Users\-\Documents\-\node_modules\opencv4nodejs>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\-\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\-\Documents\-\node_modules\opencv4nodejs
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN mangajs@1.0.0 No description
npm WARN mangajs@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv4nodejs@4.14.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv4nodejs@4.14.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\-\AppData\Roaming\npm-cache\_logs\2019-02-13T23_10_33_460Z-debug.log


```

*OpenCV version* (example 3.4.1): Auto build

*With OpenCV-contrib?* (extra modules): no

*OS*: Windows 10

**Comment by HanLiang920** [comment]
I have the same problem as you. Can you solve this problem? How is it solved?

**Comment by felipebutcher** [comment]
@davidb1 if you closed the issue it's nice to comment how did you solve so other people with the same problem know.

**Comment by davidb1** [comment]
Was missing some requirements which are stated on the main page, think I just installed node-gyp:
npm install -g node-gyp

**Comment by FlyAndNotDown** [comment]
You can change python version from 3.x to 2.x and change environment variable, the problem can be fixed

**Comment by thegreekjester** [comment]
Hello, I am getting the same error. How would I go about changing my python version, because I do have 3.x. Thank you for any answers!

**Comment by DaveGeneral** [comment]
I get the same error on my mac. I think user FlyAndNotDown get the point, as you can see in the upper lines of the messages, It's syntax error occurred in the python-related file, it's the differences between the py2 and py3, so if you set up anaconda, the solution below:
 -you can use "conda create -n py27 python=2.7",
 -then "source activate py27", 
 -then "npm install" will be ok.

**Comment by sajithgr** [comment]
> I get the same error on my mac. I think user FlyAndNotDown get the point, as you can see in the upper lines of the messages, It's syntax error occurred in the python-related file, it's the differences between the py2 and py3, so if you set up anaconda, the solution below:
> -you can use "conda create -n py27 python=2.7",
> -then "source activate py27",
> -then "npm install" will be ok.

please help how to solve this in windows10??
