### ISSUE TITLE
Unknown layer type: yolo

### ISSUE THREAD

**Issue by MattCollins84** [justadudewhohacks/opencv4nodejs#506]
I am trying to run the `dnnDarknetYOLORealTimeObjectDetection.js` example, and get this error:

# Error Message
````
const net = cv.readNetFromDarknet(cfgFile, weightsFile);
               ^
ReadNetFromDarknet - OpenCV Error: (Unknown layer type: yolo) in ReadDarknetFromCfgFile, in file /tmp/opencv-20180529-55469-97fkx6/opencv-3.4.1/modules/dnn/src/darknet/darknet_io.cpp, line 503, status -212
````

If I swap out the YOLO v3 config files for the YOLO v2, it works.

# Manual Build - Environment Information
*OpenCV version* (example 3.4.1): 3.4.?
I am unsure which patch version I am using, I installed via `brew`,  but for some reason if I try `opencv_version` in the terminal I get `2.4.13.6`.

In the past I have tried manually installing OpenCV (different versions) and there may be some conflict here? When I do `console.log(cv.version)` in my code, I get `{ major: 3, minor: 4 }`.

*With OpenCV-contrib?* (extra modules): yes

*OS*: MacOSX Majave

**Comment by Seikon** [comment]
Hi @MattCollins84 Have you checked you have the corrects pre-trained models files?
