### ISSUE TITLE
Feature: Prebuilt bindings

### ISSUE THREAD

**Issue by s1hofmann** [justadudewhohacks/opencv4nodejs#518]
Currently opencv4nodejs bindings have to be built when installing the lib.
This leads to rather long running build jobs which are running e.g. `npm ci` to verify package integrity.

I propose to enable the usage of prebuilt bindings, which would allow to skip the rebuild and would allow for faster installation.

**Comment by wenq1** [comment]
Just like puppeteer and puppeteer-core. Exactly what's needed

**Comment by s1hofmann** [comment]
@wenq1 Glad to hear.

I just want to point out that I created this fork to be able to work with prebuilt bindings as soon as possible.
As soon as it gets [merged into upstream](https://github.com/justadudewhohacks/opencv4nodejs/pull/519), I'll deprecate the package.

**Comment by wenq1** [comment]
HogDescriptor does segfault on prebuilt binaries: confirmed during runtime. I fallback using standalone libsvm instead.

**Comment by s1hofmann** [comment]
I assume you're on macOS? At least that's what I noticed when building the pre-built package.
Are you receiving segfaults when using the default lib?

**Comment by wenq1** [comment]
Yes segfault is received.

**Comment by s1hofmann** [comment]
Thanks for the update!
