### ISSUE TITLE
Face recognizer

### ISSUE THREAD

**Issue by ryandons** [justadudewhohacks/opencv4nodejs#52]
Hello justadudewhohacks,

I am using this library for quite some time now. First of all thanks  for setting this up and for all the work you have put into this, this is a very great project! It is nice to see, that there are constantly new features implemented here.

I would like to suggest the face recognition module (Facerecognizers Eigen, Fisher and  LBPH), which are available in opencv contrib.

Thanks alot!

**Comment by justadudewhohacks** [comment]
Hey ryandons,

Thank you, it's always nice to get any kind of feedback. Will add the recognizers later today.

**Comment by justadudewhohacks** [comment]
FaceRecognizers are now available.

**Comment by ryandons** [comment]
Whoa, that was fast. Amazing, thank you!!

**Comment by justadudewhohacks** [comment]
I also added two faceRecognition examples.
