### ISSUE TITLE
HOGDescriptor::detectMultiScale

### ISSUE THREAD

**Issue by fildaniels** [justadudewhohacks/opencv4nodejs#54]
It would be terrific to have bindings for HOGDescriptor::setSVMDetector(HOGDescriptor::getDefaultPeopleDetector()) and HOGDescriptor::detectMultiScale. This is awesome for pedestrian detection.

Many thanks for your great work!

**Comment by justadudewhohacks** [comment]
Good point. Will be added asap.

**Comment by justadudewhohacks** [comment]
Added the bindings you requested + some other missing ones for HOG and published to npm. Let me know if something is not working as intended.

**Comment by fildaniels** [comment]
Hey You are awesome !
It works for me like a charm.
I thank you very much
