### ISSUE TITLE
Mat.dct() throwing error

### ISSUE THREAD

**Issue by Frixoe** [justadudewhohacks/opencv4nodejs#557]
I'm trying to implement a Perceptual Hashing algorithm which requires me to compute the DCT of an image.

However, calling the function `Mat.dct()` on an image Mat throws the following error:
> **OpenCV Error: (type == CV_32FC1 || type == CV_64FC1) in dct, in file /home/suryansh/dev/tests/perceptual-hashing/node_modules/opencv-build/opencv/opencv/modules/core/src/dxt.cpp, line 4244, status -215**

I really need this to work for a project.

Thank you!

*OpenCV version* (example 3.4.1): **3.4.6**

*With OpenCV-contrib?* (extra modules): **yes**

*OS*: **Manjaro i3 18.0.4**

**Comment by justadudewhohacks** [comment]
Apparently you can't run dct on your image like that, did you try to convert your image to one of these types `(type == CV_32FC1 || type == CV_64FC1)?`

**Comment by Frixoe** [comment]
> Apparently you can't run dct on your image like that, did you try to convert your image to one of these types `(type == CV_32FC1 || type == CV_64FC1)?`

@justadudewhohacks I did and it works now. Closing the issue. That was very stupid of me.
