### ISSUE TITLE
VideoCapture does not work

### ISSUE THREAD

**Issue by FloStar3000** [justadudewhohacks/opencv4nodejs#590]
Hi, I am trying to read a .mp4 file with VideoCapture.
Maybe it's because I am trying this on a server.

System: 
Google Compute Engine
Machine Type: n1-highcpu-4 (4 vCPUs, 3,6 GB Memory)
Node v10.16.0
npm 6.9.0

Following test code: 
`const cv = require("opencv4nodejs")
const cap = new cv.VideoCapture("video.mp4")`

# Error Message

Getting the following error:

$ node test.js 
VIDIOC_REQBUFS: Inappropriate ioctl for device

/home/flostar3000/test/test.js:2
const cap = new cv.VideoCapture("video.mp4")
            ^
VideoCapture::New - failed to open capture

*OpenCV4NodeJS version* 5.1.0

*OS*: Ubuntu 16.04

**Comment by justadudewhohacks** [comment]
You are likely missing something on your system. See [this](https://stackoverflow.com/questions/53504289/opencv-videocapture-error-vidioc-reqbufs-inappropriate-ioctl-for-device) post.

**Comment by piercus** [comment]
Were having the same problem here,

The problem is related to Gstreamer not installed on the system, you can see it in the installation logs (i know there are a lot of logs but you will find it :muscle: )
```
--   Video I/O:
--     DC1394:                      NO
--     FFMPEG:                      NO
--       avcodec:                   NO
--       avformat:                  NO
--       avutil:                    NO
--       swscale:                   NO
--       avresample:                NO
--     GStreamer:                   NO
--     libv4l/libv4l2:              NO
--     v4l/v4l2:                    linux/videodev2.h
```

In order to fix it you can do, on linux 
```
sudo apt install libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good
```

And then reinstall.

You need to make sure that opencv installation contains GStreamer like in 
```
--   Video I/O:
--     DC1394:                      NO
--     FFMPEG:                      NO
--       avcodec:                   NO
--       avformat:                  NO
--       avutil:                    NO
--       swscale:                   NO
--       avresample:                NO
--     GStreamer:                   
--       base:                      YES (ver 1.14.5)
--       video:                     YES (ver 1.14.5)
--       app:                       YES (ver 1.14.5)
--       riff:                      YES (ver 1.14.5)
--       pbutils:                   YES (ver 1.14.5)
--     libv4l/libv4l2:              NO
--     v4l/v4l2:                    linux/videodev2.h
-- 
```

Then it should work !
