### ISSUE TITLE
How exactly does convertTo work

### ISSUE THREAD

**Issue by victorzzt** [justadudewhohacks/opencv4nodejs#596]
*I don't know if it's appropriate to ask about usage issue here.*
*But it's about using the mat.convertTo*

#### Eg. If I want to convert a grayscale image to an RGB
`let noise = new cv.Mat(300, 400, cv.CV_8UC1);`
`//< ... Capture or manipulation ... >`
`noise.convertTo( cv.CV_8UC3, 0, 1 );`

After using convert to, when I console log it, the channels still shows 1
>Mat {
  step: 400,
  elemSize: 1,
  sizes: [ 300, 400 ],
  empty: 0,
  depth: 0,
  dims: 2,
  channels: 1,
  type: 0,
  cols: 400,
  rows: 300 }

#### Tried another way of using from: [This post](https://stackoverflow.com/questions/22174002/why-does-opencvs-convertto-function-not-work)
`noise.cvtColor(cv.COLOR_GRAY2RGB);`
`noise.convertTo( cv.CV_8UC3, 0, 1 );`
or
`noise = noise.convertTo( cv.CV_8UC3, 0, 1 );`

The mat still stays channel 1, no error message that means the API exists.

*What did I do incorrectly*

Additional question on the library:
* When I was trying to get the window display, it seems APIs like "namedWindow" or "resizeWindow" isn't exposed or moved to some sub-module, but seems still present in cv3's document.
* Which version of API document is better for reference?

Thanks.

**Comment by justadudewhohacks** [comment]
Hi,

> What did I do incorrectly

You forgot to assign the return value of cvtColor to your Mat: `noise = noise.cvtColor(cv.COLOR_GRAY2RGB);`.

> When I was trying to get the window display, it seems APIs like "namedWindow" or "resizeWindow" isn't exposed or moved to some sub-module, but seems still present in cv3's document.

Bindings for these methods are not implemented yet, happy to take PRs. For now you have to use cv.imshow.

> Which version of API document is better for reference?

Use the OpenCV docs for the OpenCV version that you are using and check the [typings](https://github.com/justadudewhohacks/opencv4nodejs/tree/master/lib/typings) of this repo to see, if the binding is implemented.

**Comment by victorzzt** [comment]
Thanks, I'll reference to them.
