### ISSUE TITLE
How do I create a new custom model and retrain Opencv4nodjs with it?

### ISSUE THREAD

**Issue by OluAgunloye** [justadudewhohacks/opencv4nodejs#599]
Hello!

I'm a bit ignorant when it comes to creating and retraining OpenCV4 with new, custom models.  Would anyone like to help out with an answer that will certainly help others in the future, or just by pointing us in the right direction? I imagine this is a fairly common concern (the need to create new custom classes).  

*OS*: MacOSX

**Comment by justadudewhohacks** [comment]
not sure what kind of models you are referring to, i dont think you should use opencv / if its possible with opencv to train own deep learning modules, if you are referring to that
