### ISSUE TITLE
xmodules and xfeatures2d are not found and undefined respectively

### ISSUE THREAD

**Issue by OluAgunloye** [justadudewhohacks/opencv4nodejs#605]
![image](https://user-images.githubusercontent.com/6617770/61997403-ac935400-b066-11e9-8be4-6990bd5126b7.png)

*OpenCV version* (example 3.4.1): 3.4.1

*With OpenCV-contrib?* (extra modules): no

*OS*:  MacOSX

**Comment by OluAgunloye** [comment]
I'm trying to run matchFeatures.js

**Comment by justadudewhohacks** [comment]
xfeatures2d (xmodules in general) are opencv contrib modules

**Comment by nmerkle** [comment]
I had the same problem. It is not: `cv.xmodules.xfeatures2d`, but `cv.modules.xfeatures2d.` Then it works.
