### ISSUE TITLE
getAffineTransform support?

### ISSUE THREAD

**Issue by codyseibert** [justadudewhohacks/opencv4nodejs#61]
Hey there,

It would be really nice if there was built in support for **getAffineTransform** (which doesn't seem to exist atm) to be used inside the **warpAffine** method.  I will try to fork this project and see if I can add this support myself if I have time, but if anyone can beat me to it, I'd really appreciate it.

If there is already a way to easily do this, let me know. 

Thanks!

**Comment by justadudewhohacks** [comment]
Hey Cody,
you are right the binding for getAffineTransform is missing. I can find some time tomorrow to add it. Currently working on a guide for contributors to get started easier.

**Comment by justadudewhohacks** [comment]
The new features are now published to npm.

**Comment by codyseibert** [comment]
👍
