### ISSUE TITLE
Successfull install but get Segmentation Fault randomllly

### ISSUE THREAD

**Issue by sirShakir** [justadudewhohacks/opencv4nodejs#643]
The opencv4nodejs projects installed successfully but crashes frequently due to Segmentation Fault. Im using a raspberry pi zero. I put the SD card in raspberry pi B+ and it never crashes from SegFault. What it making it crash on Pi zero? Also I have another raspberry pi zero I built during opencv4nodejs@5.1.0; it works great and doest crash due segFault. I wasnt able to clone becasue of noobs.

**Comment by piercus** [comment]
Not enough info to study

**Comment by DevOps-Arts** [comment]
hi guys i can run any linux app on raspberry pi zero contact with me on gmail : [cybersecurty922@gmail.com](mailto:cybersecurty922@gmail.com)
skype: live:rehmanazhar922

i created my custom raspberry pi zeo image of armel architecture armel can run all

all the raasp os are armhf thats why error : armv7

Pakistani Hacker: Pakistan zindabaad!

**Comment by DevOps-Arts** [comment]
> Not enough info to study

hi guys i can run any linux app on raspberry pi zero contact with me on gmail : [cybersecurty922@gmail.com](mailto:cybersecurty922@gmail.com)
skype: live:rehmanazhar922

i created my custom raspberry pi zeo image of armel architecture armel can run all

all the raasp os are armhf thats why error : armv7

Pakistani Hacker: Pakistan zindabaad!
