### ISSUE TITLE
imwriteAsync : callback error seems not working...

### ISSUE THREAD

**Issue by fildaniels** [justadudewhohacks/opencv4nodejs#66]
Hi
I'm not absolutely sure but it seems that Error null is returned even if there is a writing issue (I've tested by trying to write an image in a non existant folder).
Thanks again for you great work!

**Comment by justadudewhohacks** [comment]
Hey,

Yeah you are right I didn't catch any exceptions in imwrite. But I think OpenCV's imwrite also fails silently e.g. throws no excecption, but I might be wrong.

**Comment by fildaniels** [comment]
Indeed! You are perfectly right (I've just done the same kind of test with OpenCV's imwrite  and your are not wrong : "at the same cause, the same effects")
