### ISSUE TITLE
electron-rebuild fails

### ISSUE THREAD

**Issue by lionel590** [justadudewhohacks/opencv4nodejs#672]
*OpenCV version* : 4.1.2
Node version: 13.2.0
*With OpenCV-contrib?: no
*OS*: Windows 10
set OPENCV4NODEJS_DISABLE_AUTOBUILD=1
Environement variable & path > OK

opencv4nodejs _(npm install --save opencv4nodejs_) **compiles and installs properly** see bellow 

But when when I do launch electron-rebuild then I get the famous error >  **_Cannot open include file: 'opencv2/core.hpp'"!_****

Any clue ?

> opencv4nodejs@5.5.0 install C:\nodeparse\node_modules\opencv4nodejs
> node ./install/install.js

info install using lib dir: C:/tools/opencv/build/x64/vc15/lib
info install found the following libs:
info install world : C:\tools\opencv\build\x64\vc15\lib\opencv_world412.lib

info install setting the following defines:
info defines OPENCV4NODEJS_FOUND_LIBRARY_WORLD

info install setting the following includes:
info includes C:/tools/opencv/build/include

info install setting the following libs:
info libs C:/tools/opencv/build/x64/vc15/lib/opencv_world412.lib
info install spawning node gyp process: node-gyp rebuild --jobs max

C:\nodeparse\node_modules\opencv4nodejs>if not defined npm_config_node_gyp (node "C:\Users\Lionel.Barreiro\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --jobs max )  else (node "C:\Users\Lionel.Barreiro\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --jobs max )
  opencv4nodejs.cc
  ...........
win_delay_load_hook.cc
Creating library C:\nodeparse\node_modules\opencv4nodejs\build\Release\opencv4nodejs.lib and object C:\nodeparse\node_modules\opencv4nodejs\build\Release\opencv4nodejs.exp
  opencv4nodejs.vcxproj -> C:\nodeparse\node_modules\opencv4nodejs\build\Release\\opencv4nodejs.node

**Comment by fakob** [comment]
@lionel590 did you solve this issue or find a workaround?

**Comment by AramAnd** [comment]
@lionel590 how did you solve this ?
