### ISSUE TITLE
LINUX cannot find module after build Release/opencv4nodejs

### ISSUE THREAD

**Issue by droidMakk** [justadudewhohacks/opencv4nodejs#676]
#223 Similar to this

I'm receiving a similar issue while trying to import in nodejs project.
`const cv = require('opencv4nodejs')`;

It runs fine in windows. But in Linux I'm receiving issues.
> Cannot find module '/.../node_modules/opencv4nodejs/build/Release/opencv4nodejs' 
*OpenCV version* 4.1.0

*With OpenCV-contrib?* (extra modules): yes

*OS*:  Linux

**Comment by minhdang241** [comment]
I get the same error when installing opencv4nodejs on the raspbian.

**Comment by droidMakk** [comment]
I used it raspberry pi.
The best way is to disable to autobuild
### linux and osx:
`export OPENCV4NODEJS_DISABLE_AUTOBUILD=1`
### on windows:
`set OPENCV4NODEJS_DISABLE_AUTOBUILD=1`

Then follow the steps to create the custom build.
[https://www.pyimagesearch.com/2015/10/26/how-to-install-opencv-3-on-raspbian-jessie/](LINK)

**Comment by droidMakk** [comment]
> I get the same error when installing opencv4nodejs on the raspbian.

Let me know if you need any help.

**Comment by wahengchang** [comment]
work very fine to me, thx :)
linux and osx:
```
export OPENCV4NODEJS_DISABLE_AUTOBUILD=1
```

**Comment by sumanthvakacharla** [comment]
I am still getting the same error. I have tried export OPENCV4NODEJS_DISABLE_AUTOBUILD=1
**LOGS:**
[BaseDriver] Verifying screenshot size and aspect ratio
[BaseDriver] Screenshot aspect ratio '0.5625' (1242x2208) matched screen aspect ratio '0.5625' (414x736)
[BaseDriver] Scaling screenshot from 1242x2208 to match screen at 414x736
[debug] [Support] Initializing opencv
[debug] [Support] Loading local package 'opencv4nodejs'
[debug] [Support] Failed to load local package 'opencv4nodejs': Cannot find module '/Users/sumanthvakacharla/.virtualenvs/TrackiOS-pip3/lib/node_modules/opencv4nodejs/build/Release/opencv4nodejs'
[debug] [Support] Require stack:
[debug] [Support] - /Users/sumanthvakacharla/.virtualenvs/TrackiOS-pip3/lib/node_modules/opencv4nodejs/lib/cv.js
[debug] [Support] - /Users/sumanthvakacharla/.virtualenvs/TrackiOS-pip3/lib/node_modules/opencv4nodejs/lib/opencv4nodejs.js
[debug] [Support] - /Users/sumanthvakacharla/.virtualenvs/TrackiOS-pip3/lib/node_modules/appium/node_modules/appium-support/build/lib/node.js
[debug] [Support] - /Users/sumanthvakacharla/.virtualenvs/TrackiOS-pip3/lib/node_modules/appium/node_modules/appium-support/build/lib/image-util.js
[debug] [Support] - /Users/sumanthvakacharla/.virtualenvs/TrackiOS-pip3/lib/node_modules/appium/node_modules/appium-support/build/index.js
[debug] [Support] - /Users/sumanthvakacharla/.virtualenvs/TrackiOS-pip3/lib/node_modules/appium/build/lib/logsink.js
[debug] [Support] - /Users/sumanthvakacharla/.virtualenvs/TrackiOS-pip3/lib/node_modules/appium/build/lib/main.js
[debug] [Support] Loading global package '/Users/sumanthvakacharla/.virtualenvs/TrackiOS-pip3/lib/node_modules/opencv4nodejs'
[debug] [Support] Failed to load global package 'opencv4nodejs': Cannot find module '/Users/sumanthvakacharla/.virtualenvs/TrackiOS-pip3/lib/node_modules/opencv4nodejs/build/Release/opencv4nodejs'
