### ISSUE TITLE
build link error

### ISSUE THREAD

**Issue by nooperpudd** [justadudewhohacks/opencv4nodejs#68]
os: win10 x64
node version: node 7.9.0 x64
opencv version: 3.3.1 x64

opencv4nodejs.obj : error LNK2001: unresolved external symbol "public: static void __cdecl Dnn::Init(class v8::Local<cla
ss v8::Object>)" (?Init@Dnn@@SAXV?$Local@VObject@v8@@@v8@@@Z) [C:\Users\Phil\WebstormProjects\untitled1\node_modules\ope
ncv4nodejs\build\opencv4nodejs.vcxproj]
C:\Users\Phil\WebstormProjects\untitled1\node_modules\opencv4nodejs\build\Release\opencv4nodejs.node : fatal error LNK11
20: 1 unresolved externals [C:\Users\Phil\WebstormProjects\untitled1\node_modules\opencv4nodejs\build\opencv4nodejs.vcxp
roj]

**Comment by justadudewhohacks** [comment]
Oh damn thanks for reporting this,

I guess you have build opencv world, right? Atleast I could reproduce this issue when building with opencv world.

**Comment by justadudewhohacks** [comment]
This should hopefully be fixed now. If you still run into this problem please let me know.

**Comment by nooperpudd** [comment]
Ok, this pull request indeed fixed the build link errors.

**Comment by nooperpudd** [comment]
But I think this project need  appveyor to test build on Windows. https://www.appveyor.com

**Comment by justadudewhohacks** [comment]
Yes I agree, test builds for windows would be great. I will have a look at appveyor. Thanks for sharing!
