### ISSUE TITLE
Read image from base64 buffer

### ISSUE THREAD

**Issue by gjovanov** [justadudewhohacks/opencv4nodejs#70]
Hi,
is there an API to read an image from a base64 buffer instead of a file path?

e.g.

cv.readImage(new Buffer(data, 'base64'), (err, img) => { })

**Comment by justadudewhohacks** [comment]
Hey,

Yes there is. You can use cv.imdecode for this. Here is a short snippet from the opencv-express example:
```
const pngPrefix = 'data:image/jpeg;base64,';
const jpgPrefix = 'data:image/png;base64,';

exports.decodeFromBase64 = (base64DataString) => {
  const base64Data = base64DataString.replace(pngPrefix, '').replace(jpgPrefix, '');
  const buffer = Buffer.from(base64Data, 'base64');
  const img = cv.imdecode(buffer);
  return img;
};

exports.encodeJpgBase64 = (img) => {
  return cv.imencode('.jpg', img).toString('base64');
}
```

I am not quite sure atm if replacing the prefix is necessary. Apparently it should also work without replacing the prefix as stated by YuriGor in #7

**Comment by gjovanov** [comment]
Great. Will try this. Thanks for the quick reply.

**Comment by gjovanov** [comment]
base64 is working:

```
data.base64 = data.content.split(',')[1];
let img = await cv.imdecodeAsync(new Buffer(data.base64, 'base64'));
```
Hence I'm closing this issue.
