### ISSUE TITLE
matchTemplate with mask error

### ISSUE THREAD

**Issue by Sasstraliss** [justadudewhohacks/opencv4nodejs#702]
Windows 10 x64
opencv4nodejs 5.5.0
node 12.16.1

```
const cv = require('opencv4nodejs');
const path = require('path');

const template = await cv.imreadAsync(__dirname + 'template.png', 1);
const template_mask = await cv.imreadAsync(__dirname + 'template_mask.png', 1);
const screen = await cv.imreadAsync(__dirname + 'screen.png', 1);

// This line errors
const output = screen.matchTemplate(template, 1, template_mask);
```

The error:
`Mat::MatchTemplate - OpenCV Error: () in cv::matchTemplateMask, in file C:\Users\user\Documents\project\node_modules\opencv-build\opencv\opencv\modules\imgproc\src\templmatch.cpp, line 841, status -213`

[template.png](https://i.imgur.com/Dsoup8v.png)
[template_mask.png](https://i.imgur.com/4rthkxz.png)

**Comment by Sasstraliss** [comment]
`screen.matchTemplate(template, 1, template_mask)`
needs to be
`screen.matchTemplate(template, 0, template_mask)`

as masking only accepts 0 or 3 for method

**Comment by Zebiano** [comment]
Masking has been implemented for all methods by now, check [this pull request](https://github.com/opencv/opencv/pull/15214) out. Would it be possible to implement this into `opencv4nodejs` as well?
