### ISSUE TITLE
Help - copyMakeBorder

### ISSUE THREAD

**Issue by QuevedoIB** [justadudewhohacks/opencv4nodejs#705]
Hello, I'm trying to access copyMakeBorder function, I've been trying with cv... mat... but couldn't find the way to use it, any help would be really appreciated, my code right now looks like: Which results in img.copyMakeBorder is not a function

```
  const img = cv.imread(imgPath, cv.IMREAD_UNCHANGED);

  const color = new cv.Vec(1.0, 0.0, 0.0);

  const holder = img.copyMakeBorder(5, 5, 5, 5, cv.BORDER_CONSTANT, color);

  return {
    image: holder
  };

**Comment by Shanmax1996** [comment]
const cv = require('/opncvnode/node_modules/opencv4nodejs');

var image = cv.imread('lenna.png');

const color = new cv.Vec(1, 0, 0);
const pan_image = image.copyMakeBorder(20, 0, 20, 0, cv.BORDER_CONSTANT, color);
cv.imshowWait('image', pan_image);
