### ISSUE TITLE
build link error with nw-gyp

### ISSUE THREAD

**Issue by nooperpudd** [justadudewhohacks/opencv4nodejs#71]
os: win 10 x64
node: 7.9.0 x64
nw.js: 0.22.0 x64
nw-gyp: 3.6.2
opencv4nodejs:2.22.2
opencv version: 3.3.1 x64

I follow this link http://docs.nwjs.io/en/latest/For%20Users/Advanced/Use%20Native%20Node%20Modules/#for-lts-releases test build opencv4nodejs
```
\Users\jsxf\.nw-gyp\0.22.0\x64\node.lib : fatal error LNK1106: invalid file or disk full: cannot seek to
0x31534 [C:\Users\jsxf\Documents\aa\node_modules\opencv4nodejs\build\opencv4nodejs.vcxproj]
```

**Comment by justadudewhohacks** [comment]
Hmm, I am not familar with NW.js, but in order to use it with electron for example, one needs to run a electron-rebuild on the native node module. Maybe something similar has to be done for NW.js?

**Comment by nooperpudd** [comment]
@justadudewhohacks ok I will try

**Comment by justadudewhohacks** [comment]
Did you fix this problem?
