### ISSUE TITLE
cv.MultiTracker is not a constructor

### ISSUE THREAD

**Issue by MattCollins84** [justadudewhohacks/opencv4nodejs#73]
I am getting the following error when trying to use the `MultiTracker`

````
const trackers = new cv.MultiTracker();
                 ^
TypeError: cv.MultiTracker is not a constructor
````

I am on Node `8.4.0`, with OpenCV `3.3.1`. If I do `cv.version` inside Node I get:

````json
{ "major": 3, "minor": 3 }
````

So it looks like it is picking up the correct version etc...

Looking at the unit tests etc... this is the correct way to do things, but I can't see what I'm doing wrong?!

__edit:__ it just dawned on me to run the tests. It says compiled without tracking next to the tracking tests - how do I compile with tracking?!

**Comment by justadudewhohacks** [comment]
Hey,

The Tracker module is part of opencv_contrib, which provides extra modules for opencv. You will have to build opencv with contrib if you want to use this module.

**Comment by MattCollins84** [comment]
thank you!
