### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by gjovanov** [justadudewhohacks/opencv4nodejs#74]
Hi there,
on WIN10, I've installed OpenCV 3.3.1 in:

"C:\tools\opencv"

Thus I have:
- OPENCV_DIR=C:\tools\opencv\build
- OPENCV_INCLUDE_DIR=C:\tools\opencv\build\include
- OPENCV_LIB_DIR=C:\tools\opencv\build\x64\vc14\lib

as well in PATH:
- %OPENCV_DIR%\lib
- %OPENCV_DIR%\bin

when compiling from source:
- git clone https://github.com/justadudewhohacks/opencv4nodejs.git
- cd opencv4nodejs
- npm i

I get this error:

imgproc.obj : error LNK2001: unresolved external symbol "void __cdecl cv::Canny(class cv::_InputArray const &,class cv::_InputArray const &,class cv::_OutputArray const &,double,double,bool)" (?Canny@cv@@YAXAEBV_InputArray@1@0AEBV_OutputArray@1@NN_N@Z) [C:\Dev\opencv4nodejs\build\opencv4nodejs.vcxproj]
SVM.obj : error LNK2001: unresolved external symbol "public: static struct cv::Ptr<class cv::ml::SVM> __cdecl cv::ml::SVM::load(class cv::String const &)" (?load@SVM@ml@cv@@SA?AU?$Ptr@VSVM@ml@cv@@@3@AEBVString@3@@Z) [C:\Dev\opencv4nodejs\build\opencv4nodejs.vcxproj]
dnn.obj : error LNK2001: unresolved external symbol "class cv::Mat __cdecl cv::dnn::experimental_dnn_v2::blobFromImages(class std::vector<class cv::Mat,class std::allocator<class cv::Mat> > const &,double,class cv::Size_<int>,class cv::Scalar_<double> const &,bool,bool)" (?blobFromImages@experimental_dnn_v2@dnn@cv@@YA?AVMat@3@AEBV?$vector@VMat@cv@@V?$allocator@VMat@cv@@@std@@@std@@NV?$Size_@H@3@AEBV?$Scalar_@N@3@_N3@Z) [C:\Dev\opencv4nodejs\build\opencv4nodejs.vcxproj]
dnn.obj : error LNK2001: unresolved external symbol "class cv::dnn::experimental_dnn_v2::Net __cdecl cv::dnn::experimental_dnn_v2::readNetFromTensorflow(class cv::String const &,class cv::String const &)" (?readNetFromTensorflow@experimental_dnn_v2@dnn@cv@@YA?AVNet@123@AEBVString@3@0@Z) [C:\Dev\opencv4nodejs\build\opencv4nodejs.vcxproj]
dnn.obj : error LNK2001: unresolved external symbol "public: bool __cdecl cv::dnn::experimental_dnn_v2::Net::empty(void)const " (?empty@Net@experimental_dnn_v2@dnn@cv@@QEBA_NXZ) [C:\Dev\opencv4nodejs\build\opencv4nodejs.vcxproj]
dnn.obj : error LNK2001: unresolved external symbol "public: __cdecl cv::dnn::experimental_dnn_v2::Net::~Net(void)" (??1Net@experimental_dnn_v2@dnn@cv@@QEAA@XZ) [C:\Dev\opencv4nodejs\build\opencv4nodejs.vcxproj]
dnn.obj : error LNK2001: unresolved external symbol "public: __cdecl cv::dnn::experimental_dnn_v2::Net::Net(void)" (??0Net@experimental_dnn_v2@dnn@cv@@QEAA@XZ) [C:\Dev\opencv4nodejs\build\opencv4nodejs.vcxproj]
dnn.obj : error LNK2001: unresolved external symbol "class cv::Mat __cdecl cv::dnn::experimental_dnn_v2::blobFromImage(class cv::Mat const &,double,class cv::Size_<int> const &,class cv::Scalar_<double> const &,bool,bool)" (?blobFromImage@experimental_dnn_v2@dnn@cv@@YA?AVMat@3@AEBV43@NAEBV?$Size_@H@3@AEBV?$Scalar_@N@3@_N3@Z) [C:\Dev\opencv4nodejs\build\opencv4nodejs.vcxproj]
dnn.obj : error LNK2001: unresolved external symbol "class cv::dnn::experimental_dnn_v2::Net __cdecl cv::dnn::experimental_dnn_v2::readNetFromCaffe(class cv::String const &,class cv::String const &)" (?readNetFromCaffe@experimental_dnn_v2@dnn@cv@@YA?AVNet@123@AEBVString@3@0@Z) [C:\Dev\opencv4nodejs\build\opencv4nodejs.vcxproj]
Net.obj : error LNK2001: unresolved external symbol "public: void __cdecl cv::dnn::experimental_dnn_v2::Net::setInput(class cv::Mat const &,class cv::String const &)" (?setInput@Net@experimental_dnn_v2@dnn@cv@@QEAAXAEBVMat@4@AEBVString@4@@Z) [C:\Dev\opencv4nodejs\build\opencv4nodejs.vcxproj]
Net.obj : error LNK2001: unresolved external symbol "public: class cv::Mat __cdecl cv::dnn::experimental_dnn_v2::Net::forward(class cv::String const &)" (?forward@Net@experimental_dnn_v2@dnn@cv@@QEAA?AVMat@4@AEBVString@4@@Z) [C:\Dev\opencv4nodejs\build\opencv4nodejs.vcxproj]
descriptorMatching.obj : error LNK2001: unresolved external symbol "public: static struct cv::Ptr<class cv::DescriptorMatcher> __cdecl cv::DescriptorMatcher::create(int)" (?create@DescriptorMatcher@cv@@SA?AU?$Ptr@VDescriptorMatcher@cv@@@2@H@Z) [C:\Dev\opencv4nodejs\build\opencv4nodejs.vcxproj]
C:\Dev\opencv4nodejs\build\Release\opencv4nodejs.node : fatal error LNK1120: 12 unresolved externals [C:\Dev\opencv4nodejs\build\opencv4nodejs.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)

Do you know why this is the case?
Your help is highly appreciated.

Thanks

**Comment by akkishay** [comment]
follow the steps-
1)install windows-build-tools first-> for this run the command prompt as a administrator otherwise it won't install windows-build-tools

"npm install --global --production windows-build-tools"

this will install the above package (and python version 2.7.13 at location C:\Users\<your username>\.windows-build-tools\python27)
2)then install node-gyp  -> 

"npm install -g node-gyp"

then run this command 
npm config set python C:\Users\<your username>\.windows-build-tools\python27

3)set following 3 variables->

OPENCV_DIR->C:\opencv\sources
OPENCV_INCLUDE_DIR->C:\opencv\build\include
OPENCV_LIB_DIR->C:\opencv\build\x64\vc14\lib

as you have changed location of opencv, therefore above variable path will change according to your installation path of opencv


I hope, my solution works for you.

Enter those commands without double quotes.

**Comment by justadudewhohacks** [comment]
It looks like the linker has some wrong method signatures for some lib files. Did you build opencv3.3.1 yourself from source or did you download one of the releases? The problem is probably that there is a mismatc between header files and lib files that you linked. Did you build opencv in debug mode maybe?

**Comment by gjovanov** [comment]
previously I had 2.4 version installed in the same folder and used the npm
opencv library.

Then noticed your project and decided to give it a try.

I downloaded the 3.3.1 from https://opencv.org/releases.html, but something
must have gone wrong with the folder overwrite.

Anyways, I deleted the folder completely and unzipped it again... and this
time the build has worked.

Thanks for you suggestions.


However, I encountered another issue during the express server start:

Failed to setup secured server: Error: The specified module could not be
found.
\\?\C:\Dev\xplorify\xplorify-hello\server\node_modules\opencv4nodejs\build\Release\opencv4nodejs.node
    at Object.Module._extensions..node (module.js:670:18)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous>
(C:\Dev\xplorify\xplorify-hello\server\node_modules\opencv4nodejs\lib\opencv4nodejs.js:7:8)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous>
(C:\Dev\xplorify\xplorify-hello\server\services\face\face-service.js:11:8)
    at Module._compile (module.js:641:30)

this is how the face-servide.js looks like for now (contains only imports)

"use strict";

const mongoose = require('mongoose'),
config = require("../../config"),
faceSchema = require("../../models/face"),
recognizerSchema = require("../../models/recognizer"),
util = require('util'),
path = require('path'),
fs = require('fs'),
gm = require('gm'), //graphicsmagick,
cv = require('opencv4nodejs'),
dataPath = "./node_modules/opencv4nodejs/lib/haarcascades";

I'm able to find:

\C:\Dev\xplorify\xplorify-hello\server\node_modules\opencv4nodejs\build\Release\opencv4nodejs.node

Any ideas?


Mit freundlichen Grüßen / Best regards,
Goran Jovanov, MSc MBA

*Phone*:
+43 660 257 0161
*Web*:
www.xplorify.net
*Skype*:
mr.goran.jovanov


On Wed, Nov 15, 2017 at 7:28 PM, justadudewhohacks <notifications@github.com

**Comment by justadudewhohacks** [comment]
Are you referring to the opencv-express example? Could you give some more information about the environment, do you run this in a docker container or just on your local machine with express? If you try to require opencv4nodejs from a simple node script does it throw this error as well or is that working?

**Comment by gjovanov** [comment]
The express server is my code, that used to work with previously with:

https://github.com/peterbraden/node-opencv

server.js (express server) -> routes/face-controller.js -> services/face-service.js
(here I have require('opencv4nodejs') statement) previously it was require('opencv')

the error seems to be related to the path:

error: uncaughtException: The specified module could not be found.
\\?\C:\Dev\xplorify\xplorify-hello\server\node_modules\opencv4nodejs\build\Release\opencv4nodejs.node 

For some reason it is prefixing the path with \\?\ ... it should be 

C:\Dev\xplorify\xplorify-hello\server\node_modules\opencv4nodejs\build\Release\opencv4nodejs.node 

I placed several console.log statements and it fails inside:

node_modules/opencv4nodejs/lib/opencv4nodejs.js

in the line:

cv = require('../build/Release/opencv4nodejs');

**Comment by gjovanov** [comment]
As specified here:

https://stackoverflow.com/questions/41253450/error-the-specified-module-could-not-be-found

I used:
http://www.dependencywalker.com/

and opened:
opencv4nodejs.node

And the tool found many unresolved dependencies (see attachment - save export from the tool):

[opencv4nodejs.zip](https://github.com/justadudewhohacks/opencv4nodejs/files/1477934/opencv4nodejs.zip)

Not sure if this is related to the node version I'm using (9.2)

**Comment by gjovanov** [comment]
I also tried your electron example:

- git clone https://github.com/justadudewhohacks/opencv-electron.git
- cd opencv-electron
- npm i
- npm start

The app start and when I browe a photo (any PNG or JPG) i the developer tools I can see this error:

C:\Dev\opencv-electron\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:234 Uncaught Error: The specified module could not be found.
\\?\C:\Dev\opencv-electron\node_modules\opencv4nodejs\build\Release\opencv4nodejs.node
Error: The specified module could not be found.
\\?\C:\Dev\opencv-electron\node_modules\opencv4nodejs\build\Release\opencv4nodejs.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)



So ti seems that some referenced lib is missing. But can't figure out which one...

**Comment by justadudewhohacks** [comment]
If dependency walker tells you about unresolved dependencies, then odds are that the binaries are not found in your path. Did you change your system path to point to the new opencv binary path, e.g. the directory containing the dlls?

Maybe also node9 related, I didn't test with node version 9 yet.

**Comment by akkishay** [comment]
did you have installed windows-build-tools?

**Comment by gjovanov** [comment]
@justadudewhohacks I tried require(path.resolve('../build/Release/opencv4nodejs')); and the only diff is in the error message:

`error: uncaughtException: Cannot find module 'C:\Dev\xplorify\xplorify-hello\build\Release\opencv4nodejs'`

instead of (previously):

```
error: uncaughtException: The specified module could not be found.
\\?\C:\Dev\xplorify\xplorify-hello\server\node_modules\opencv4nodejs\build\Release\opencv4nodejs.node
```

@akkishay 
I do have 'windows-build-tools' installed.

Previously had python via chocolatey installed:

https://chocolatey.org/packages/python2

but I have uninstalled it and did:

```
"npm install --global --production windows-build-tools"
"npm install -g node-gyp"
```

However, this didn't make any difference.

The compilation process of opencv4nodejs works or at least doesn't throw any errors. So when I install it with:

`npm i opencv4nodejs --save`

in my project, the process finishes with these messages:

```
Finished generating code
  opencv4nodejs.vcxproj -> C:\Dev\xplorify\xplorify-hello\server\node_modules\opencv4nodejs\build\Release\\opencv4nodejs.node
  opencv4nodejs.vcxproj -> C:\Dev\xplorify\xplorify-hello\server\node_modules\opencv4nodejs\build\Release\opencv4nodejs.pdb (Full PDB)
+ opencv4nodejs@2.22.2
added 3 packages in 205.005s
```

I also compiled opencv including contrib, following these tutorials:

- https://perso.uclouvain.be/allan.barrea/opencv/cmake_config.html
- https://www.learnopencv.com/install-opencv3-on-windows/

and added the output .dlls in the system PATH.

But no difference.

The only suspcios to me is the fact that Dependency Walker shows OPENCV_WORLD331.DLL is missing (see attachment), besides the KERNELL32 and NODE.EXE missing entries, but for them:

https://stackoverflow.com/questions/36240215/dependency-walker-missing-dlls

says it's normal these are missing as the tool stopped being developed in 2005. 

![image](https://user-images.githubusercontent.com/2255435/32901560-6d2c99f0-caf0-11e7-9d53-d0db821cbaba.png)

**Comment by justadudewhohacks** [comment]
This infact is very suspicious to me. And you are absolutely sure that the path to world331.dll is in your system path and that there are no other references to old opencv binaries dangling around in your system path? Dependency walker should not show you that it cant find opencvworld dll.

**Comment by gjovanov** [comment]
Indeed that was the problem. As mentioned in my first post reporting this issue, let me quote myself:

> "C:\tools\opencv"
> 
> Thus I have:
> 
> OPENCV_DIR=C:\tools\opencv\build
> OPENCV_INCLUDE_DIR=C:\tools\opencv\build\include
> OPENCV_LIB_DIR=C:\tools\opencv\build\x64\vc14\lib
> as well in PATH:
> 
> %OPENCV_DIR%\lib
> %OPENCV_DIR%\bin 

As you can see this is wrong what is in PATH. To access the opencv_world331.dll, I need to have:
C:\tools\opencv\build\x64\vc14\bin in PATH. As well as to access the opencv_world331.lib, I need to have, C:\tools\opencv\build\x64\vc14\lib in PATH.

Having:
%OPENCV_DIR%\lib
%OPENCV_DIR%\bin 
won't do it. So I added explicitly the ......\bin and ....\lib paths in PATH. And the error disappeared.

Thanks for your patience with this siliness of mine :)

You can close this issue.

**Comment by justadudewhohacks** [comment]
Nice. Thats what I am here for, no problem :D
