### ISSUE TITLE
Trying to limit the size of a frame for performance reasons, setting frame width and height breaks the program

### ISSUE THREAD

**Issue by Withenex** [justadudewhohacks/opencv4nodejs#748]
# Error Message

I'm trying to use opencv4nodejs to serve webcam footage to a webpage encoded in base64

I can't reliably get opencv to poll the camera at more than 10fps. I believe this is due to performance reasons

I want to limit the size of the frame to help. I'm using

```
this.cvCap.set(cv.CAP_PROP_FRAME_WIDTH,300);
this.cvCap.set(cv.CAP_PROP_FRAME_HEIGHT,300);
```
Whenever I use these lines of code, nodejs returns:

```
/home/brandonp/repos/nestwebcam/dist/webcam/webcam.service.js:30
            const image = cv.imencode(".jpg", frame).toString('base64');
                             ^
Io::Imencode - OpenCV Error: (Raw image encoder error: Empty JPEG image (DNL not supported)) in throwOnEror, in file /home/brandonp/repos/nestwebcam/node_modules/opencv-build/opencv/opencv/modules/imgcodecs/src/grfmt_base.cpp, line 145, status -10
```

I've done some logging as well and those two statements that break my code return false. Whenever I try to cvCap.get() the properties they return zero

# Auto Build - Full Error Log
Don't know how to get this. Help appreciated.

*OpenCV version* (example 3.4.1): 5.6.0

*With OpenCV-contrib?* (extra modules): No

*OS*: Manjaro

**Comment by stdbreaks** [comment]
Try using guvcview to determine which resolutions are supported by your webcam, empty frames may be caused by unsupported resolution 300x300. I don't remember any cameras that have suport for such resolution. And you also will need to determine supported frame rates as they are set by CAP_PROP_FPS

**Comment by Withenex** [comment]
> Try using guvcview to determine which resolutions are supported by your webcam, empty frames may be caused by unsupported resolution 300x300. I don't remember any cameras that have suport for such resolution. And you also will need to determine supported frame rates as they are set by CAP_PROP_FPS

I see, so any resolution I set through those variables has to be natively supported by the hardware. I'll give it a try
