### ISSUE TITLE
Installation issues of opencv4nodejs

### ISSUE THREAD

**Issue by spandey1296** [justadudewhohacks/opencv4nodejs#766]
I have installed all packages and all git, node, and npm are in the latest version. Some of the steps I followed by StackOverflow but doesn't work.

> opencv-build@0.1.9 install C:\Users\91727\Videos\Nodejs project\StreamVedioapp\node_modules\opencv-build
> node ./install.js

info install if you want to use an own OpenCV installation set OPENCV4NODEJS_DISABLE_AUTOBUILD
info readAutoBuildFile file does not exists: C:\Users\91727\Videos\Nodejs project\StreamVedioapp\node_modules\opencv-build\opencv\auto-build.json C:\Users\91727\Videos\Nodejs project\StreamVedioapp\node_modules\opencv-build\opencv\auto-build.json
info install failed to find auto-build.json: C:\Users\91727\Videos\Nodejs project\StreamVedioapp\node_modules\opencv-build\opencv\auto-build.json
info install
info install running install script...
info install
info install opencv version: 3.4.6
info install with opencv contrib: yes
info install custom build flags:
info install
info install executing: git --version
ERR! Error: failed to execute git --version, git is required, error is: Error: Command failed: git --version
'git' is not recognized as an internal or external command,
operable program or batch file.
 
npm WARN stramlive_video@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv-build@0.1.9 install: `node ./install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv-build@0.1.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\91727\AppData\Roaming\npm-cache\_logs\2020-09-27T14_58_15_677Z-debug.log

**Comment by yomboprime** [comment]
It seems you need to do ```sudo apt install git```

**Comment by dland512** [comment]
I think the relevant line is

```
ERR! Error: failed to execute git --version, git is required, error is: Error: Command failed: git --version
'git' is not recognized as an internal or external command
```

It's telling you it doesn't know what `git` is. You probably need to add the git to your PATH env variable.

**Comment by spandey1296** [comment]
An error has now resolved. Thanks
