### ISSUE TITLE
Opencv4nodejs compiled without face module

### ISSUE THREAD

**Issue by gjovanov** [justadudewhohacks/opencv4nodejs#77]
Hi again,
I've been trying out the face recognition examples, but I get this error.

`Opencv4nodejs compiled without face module`

I have compiled manually OpenCV 3.3.1 including OpenCV Contrib 3 and the compilation was successful.

I've the follwoing system environment varibales:
`OPENCV_DIR=C:\tools\opencv\build\bin\Release` - Contains all dlls including opencv_face331.dll
`OPENCV_LIB_DIR=C:\tools\opencv\build\lib\Release` - Contains all libs including opencv_face331.lib
`OPENCV_INCLUDE_DIR=C:\tools\opencv\build\include` - Origingal includes folder from the downloaded OpenCV zip. It doesn't contain face subfolder. 

I must admit I don't quite understand the purpose of the include dir and I assume the problem lies in that.

For example, the folder `(1) C:\tools\opencv\build\modules` contains all cpp files including the face subfolder and it's cpp files. The folder `(2) C:\tools\opencv_contrib-3.3.1\modules` contains all contrib cpp files. Both (1) and (2) were used during my manual compilation. But as I said, I'm not sure what is the purpose of the include folder.

Anyways, do you know if this error is related to the INCLUDE folder or why the face module is not included?

**Comment by justadudewhohacks** [comment]
Hey,

The include dir points to the opencv header files, which are the files that basically tell the compiler about all the classes, functions and their signatures, which are compiled and bundled in the .lib files. Both the header files and .lib files are required to compile external libraries or packages using opencv ( such as opencv4nodejs).

As far as I understood your problem, you did compile Opencv now from source with contrib and thus have the .lib and .dll files for both opencv and opencv contrib. But you took the header files from the official opencv release, which only contain the main modules, not the extra modules headers such as face, right?

If you build opencv on windows you will probably have run the main solution to build the thing. On windows however you also have to run the INSTALL.vcxproj under CMakeTargets. This will copy all the header files to `OPENCV_DIR/build/install/include`. That one should then be your include dir.

**Comment by gjovanov** [comment]
Thanks for explaning about the include folder.

Yes, that was it. I had those include folder in `C:\tools\opencv\build\install\include`.

You can close this one as well. Cheers!
