### ISSUE TITLE
imread error

### ISSUE THREAD

**Issue by chenjie26** [justadudewhohacks/opencv4nodejs#78]
howt to read a image  with IMREAD_UNCHANGED.

**Comment by justadudewhohacks** [comment]
Currently imread is working with default flags. Will add support for flags asap.

**Comment by justadudewhohacks** [comment]
Imread and imwrite can now be called with an optional flags parameter. So you can do:
`cv.imread(path, cv.IMREAD_UNCHANGED`.

**Comment by chenjie26** [comment]
OK thanks!
