### ISSUE TITLE
matchTemplate - multi object template matching.

### ISSUE THREAD

**Issue by animosi** [justadudewhohacks/opencv4nodejs#786]
matchTemplate using python returns an array of possible matches which you can filter using threshhold. Opencv4nodejs's matchTemplate returns one Mat.
I can't find an example of multi-object template matching using JS anywhere on google, yourtube, github, or stackoverflow.

I see a similar thread opened in 2018 which was never resolved. Are there other Mat functions which I should be utilizing to achieve my goal.

**Comment by phurinatp** [comment]
```
const cv = require("opencv4nodejs");

async function findMatchingTemplate() {
  const threshold = 0.8;
  const bigImgMat = await cv.imreadAsync("./assets/source.png");
  const subImgMat = await cv.imreadAsync("./assets/coin.png");

  const matched = bigImgMat.matchTemplate(subImgMat, cv.TM_CCOEFF_NORMED);
  const dataList = matched.getDataAsArray();

  for (let y = 0; y < dataList.length; y++) {
    for (let x = 0; x < dataList[y].length; x++) {
      if (dataList[y][x] > threshold) {
        bigImgMat.drawRectangle(
          new cv.Rect(x, y, subImgMat.cols, subImgMat.rows),
          new cv.Vec3(0, 255, 0),
          2,
          cv.LINE_8
        );
      }
    }
  }

  cv.imshow('multiple matches', bigImgMat);
  cv.waitKey();
}
```
source.png

![mario](https://user-images.githubusercontent.com/53590627/101584670-cf7e9800-3a10-11eb-86f0-2d8cc9107187.png)

coin.png
![coin](https://user-images.githubusercontent.com/53590627/101584715-e45b2b80-3a10-11eb-9111-3f75e6a62080.PNG)

result:
![result](https://user-images.githubusercontent.com/53590627/101584809-0fde1600-3a11-11eb-9b7e-4887d6084778.png)
