### ISSUE TITLE
Installation: staticlib folder not found

### ISSUE THREAD

**Issue by Garfield100** [justadudewhohacks/opencv4nodejs#8]
So I've set up the environment variables and all but now I get another error:

`Error: ENOENT: no such file or directory, scandir 'D:\opencv\build\x64\vc14\staticlib'`

I've googled a bit and it seems like version 3.3.0 of opencv (the one I have) comes without said folder.
I've seen people talking about recompiling and static linkage stuff but I have no idea what that means or how to use c++. What should I do?

**Comment by justadudewhohacks** [comment]
Hello Garfield100,
Indeed the OpenCV 3.3 release does not have staticlibs, did you set the environmet variable specifically to that path: 'D:\opencv\build\x64\vc14\staticlib'? In vc14/lib you should find 'opencv_world330.lib'. Make sure you set 'OPENCV_LIB_DIR' to ''D:\opencv\build\x64\vc14\lib' instead.

`

**Comment by Garfield100** [comment]
Oh, I thought I had deleted `OPENCV_LIB_DIR` but apparently i set it to a non existen staticlib folder.
My bad but thanks! I didn't know the lib folder would also work because it says "static lib" folder on the npm page, so you might want to change that. Thanks for your help and for making this! I'm looking forward to doing all sorts of stuff with this, and I don't know c++.
