### ISSUE TITLE
core dumps without any trace

### ISSUE THREAD

**Issue by nerkn** [justadudewhohacks/opencv4nodejs#811]
My app heavily using getRegion. In one of the functions, I'm going out of the image, but i cant locate without proper error message. Whole nodejs just dies out.

terminate called after throwing an instance of 'std::runtime_error'
  what():  OpenCV Error: (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in Mat, in file /control/node_modules/opencv-build/opencv/opencv/modules/core/src/matrix.cpp, line 465, status -215
Aborted (core dumped)

It should emit error exception or die traceable.

**Comment by UrielCh** [comment]
fixed and tested [here](https://github.com/UrielCh/opencv4nodejs/commit/10cdf00651ad1603ff55b86ecc520d2e33d44265)

I do not know where is the fix, but the test is here.
