### ISSUE TITLE
M1 Mac Mini BigSur - fails install via 'npm i -g opencv4nodejs'

### ISSUE THREAD

**Issue by sme81** [justadudewhohacks/opencv4nodejs#817]
Followed issue template as best as possible regarding useful errors.

npm@6.14.10
node@v14.15.4

# Error Message

> [ 79%] Built target opencv_dnn
make: *** [all] Error 2
ERR! child process exited with code 2

# Auto Build - Full Error Log

[Gist](https://gist.github.com/sme81/5b98baad907971cdfede0372d64f6bb1)

# Additional Info

*OpenCV version*: 3.4.6

*With OpenCV-contrib?* (extra modules): yes

*OS*: M1 Mac Mini BigSur

**Comment by sme81** [comment]
FIXED:

Uninstall brew
Set terminal to Rosetta Mode
Install Brew
brew install cmake
npm i -g opencv4nodejs - now finishes (with lots of warnings)

shows as installed on 'appium-doctor --android'
Appium CLI can find it too

**Comment by zcmgyu** [comment]
@Auto81 Thanks. This is indeed helpful.
