### ISSUE TITLE
warnings during installations

### ISSUE THREAD

**Issue by akkishay** [justadudewhohacks/opencv4nodejs#83]
I am getting some warnings while doing a fresh install of opencv4nodejs as following-

1)
c:\users\advik\appdata\roaming\npm\node_modules\opencv4nodejs\cc\ArrayConverters.h(41): warning C4018: '<': signed/unsigned mismatch (compiling source file ..\cc\modules\features2d\detectors\SimpleBlobDetector.cc) [C:\Users\advik\AppData\
Roaming\npm\node_modules\opencv4nodejs\build\opencv4nodejs.vcxproj]

2)
c:\users\advik\appdata\roaming\npm\node_modules\opencv4nodejs\cc\core\Vec.h(44): warning C4018: '<': signed/unsigned mismatch (compiling source file ..\cc\modules\features2d\detectors\SimpleBlobDetector.cc) [C:\Users\advik\AppData\Roaming
\npm\node_modules\opencv4nodejs\build\opencv4nodejs.vcxproj]

3) c:\users\advik\appdata\roaming\npm\node_modules\opencv4nodejs\cc\modules\imgproc\contour.cc(159): warning C4700: uninitialized local variable 'parameter' used [C:\Users\advik\AppData\Roaming\npm\node_modules\opencv4nodejs\build\opencv4nod
ejs.vcxproj]

are those negligible?

**Comment by justadudewhohacks** [comment]
Hey,

Yes the warnings are negligible. There are quite some compiler warnings, which I wanted to clean up at some point, but they shouldn't bother you at all.

**Comment by akkishay** [comment]
thanks for reply.
