### ISSUE TITLE
face module

### ISSUE THREAD

**Issue by akkishay** [justadudewhohacks/opencv4nodejs#87]
does this package come with face module or do we have to compile from contrib packages?

**Comment by justadudewhohacks** [comment]
The face module is part of opencv-contrib. If you install opencv with contrib then you can use it with opencv4nodejs.

**Comment by akkishay** [comment]
and if i compile opencv-contrib, then can I use that compiled files on any computer or system?

just assume that I am using windows then the compiled files will run on any windows system?

**Comment by justadudewhohacks** [comment]
Oh I am not sure. It might be possible that compiling on win10, you would be able to reuse it on another win10 machine, but I am not sure about that, since during compilation of OpenCV there are also machine specific checks such as IPP support.

**Comment by akkishay** [comment]
if i build the opencv_contrib in 32 bit, will it work?

**Comment by justadudewhohacks** [comment]
What, opencv4nodejs? Yes it shouldn't matter if 32 bit or 64bit.

**Comment by akkishay** [comment]
nope. I am asking for opencv+opencv+contrib.

I am using nodejs of 64bit.

**Comment by justadudewhohacks** [comment]
I mean it doesnt matter if you compile opencv with contrib for 32 or 64 bit. You can use both with opencv4nodejs.

**Comment by akkishay** [comment]
ok
it is saying that these projects are out of date while building the opencv in vs15-

    ZERO_CHECK - Debug Win32
    ippiw - Debug Win32
    zlib - Debug Win32
    opencv_core_FP16 - Debug Win32
    opencv_core_SSE4_2 - Debug Win32
    opencv_core_SSE4_1 - Debug Win32
    opencv_core_AVX - Debug Win32
    ittnotify - Debug Win32
    opencv_core_AVX2 - Debug Win32
    opencv_imgproc_AVX - Debug Win32

and it is giving an option to build them.

should i build or not?

![capture](https://user-images.githubusercontent.com/16587898/33482535-8314b876-d6bf-11e7-86f6-88ec5d9b730c.PNG)

**Comment by akkishay** [comment]
i got it

thannk you.
