### ISSUE TITLE
need help: how to close or rename an imshow window?

### ISSUE THREAD

**Issue by Fauny** [justadudewhohacks/opencv4nodejs#88]
[edit] how to close or rename an imshow window in Electron.

**Comment by justadudewhohacks** [comment]
Hey Fauny, 
I am not aware of any way to rename windows in opencv. But you can ckose them with destroyWindow(windowName) or destroyAllWindows()

**Comment by Fauny** [comment]
Thank you @justadudewhohacks .

destroyWindow works in node evn,  but I cannot use it in my Electron project.

**Comment by justadudewhohacks** [comment]
Oh yeah, might be that it's not possible to use opencv window methods with electron. So you might have to draw it into a canvas.
