### ISSUE TITLE
Project insight!

### ISSUE THREAD

**Issue by Czechh** [justadudewhohacks/opencv4nodejs#89]
Hey yo! I've been looking into several libraries to go for my next project, and I believe this one should do the trick. But I'm new in `opencv` and computer vision in general, so it would be awesome to get some advice if you don't mind.

I'm looking to detect the result of a roulette using video. Determining what number did the ball fell. I've been looking into your examples to build upon them, but it would be great to get some insight from you if you don't mind.

Thanks!

**Comment by justadudewhohacks** [comment]
Hey Czechh,

Indeed I think opencv is the right choice to implement this. There are obviously a lot of ways to achieve your goal, depending on the general conditions and desired robustness.

What I would try out first, is to track the bowl until it reached it's final position in the video. This could be as simple as thresholding the image for the bowls color and keep track of the largest blob in the thresholded image. You would also have to detect the score slots somehow, maybe you can use hough circles to find the outter rings of the board and work your way up from there. Then you would also have to determine the score value of the slots by recognizing the numbers. You could probably use OCR for that, recognizing homogenously shaped numbers shouldn't be that difficult.

**Comment by Czechh** [comment]
Thank you for the insight! I'll start working on this! I'll be using this NPM package. 🥇
