### ISSUE TITLE
Failed to locate: "CL.exe"

### ISSUE THREAD

**Issue by Garfield100** [justadudewhohacks/opencv4nodejs#9]
Sorry to bother you again, but now I've installed the Windows 8.1 (and 10) SDK and now I get this error:
`TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified.
[C:\Users\Garfield100\AppData\Roaming\npm\node_modules\opencv4nodejs\build\opencv4nodejs.vcxproj]`
Do I need to install something else too?

**Comment by justadudewhohacks** [comment]
That error looks exotic to me, probably something msvc related. Do you have the windows build tools installed? `npm install --global windows-build-tools` from a shell started as admin. Also make sure you have python 2.7.

If you have trouble with node-gyp, check out the section about windows at: https://github.com/nodejs/node-gyp

**Comment by Garfield100** [comment]
Yeah... Turns out you need Visual Studio 2015, not 2017.
Sorry for being nooby :/
Hope it helps someone else with the same problem.
