### ISSUE TITLE
installation issue from manual build of opencv

### ISSUE THREAD

**Issue by akkishay** [justadudewhohacks/opencv4nodejs#90]
hello there.
I have manually build the opencv from source.
the build went successfully

I installed windows-build-tools which also installed python with itself

then I installed node-gyp

all installation were successful

i set all variable for python and opencv

and I am getting problem while installing the opencv4nodejs
as following

C:\Users\advik>npm install -g opencv4nodejs

> opencv4nodejs@2.23.1 install C:\Users\advik\AppData\Roaming\npm\node_modules\opencv4nodejs
> node-gyp rebuild

C:\Users\advik\AppData\Roaming\npm\node_modules\opencv4nodejs>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\advik\.windows-build-tools\python27", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\advik\AppData\Roaming\npm\node_modules\opencv4nodejs
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv4nodejs@2.23.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv4nodejs@2.23.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\advik\AppData\Roaming\npm-cache\_logs\2017-12-02T08_55_47_024Z-debug.log

C:\Users\advik>

**Comment by fildaniels** [comment]
Error: Can't find Python executable "C:\Users\advik.windows-build-tools\python27", you can set the PYTHON env variable.

**Comment by akkishay** [comment]
I have alrady set up an variable of this in environmental variables. @fildaniels

**Comment by fildaniels** [comment]
Are you sure of the path you configured because this one looks weird C:\Users\advik.windows-build-tools ?

**Comment by akkishay** [comment]
there is an \ after username that is advik
i have setted up the variable as PYTHON=C:\Users\advik\.windows-build-tools\python27

**Comment by akkishay** [comment]
here is the image 
![capture](https://user-images.githubusercontent.com/16587898/33513766-471cc0c4-d76f-11e7-9d28-21bae1ad6db3.PNG)

**Comment by fildaniels** [comment]
I think you should check the full path you installed Windows build tools because the dot before windows-build-tools seems not correct (ASFAIK)
Try to set up the variable as :
PYTHON=C:\Users\advik\windows-build-tools\python27

**Comment by justadudewhohacks** [comment]
I think you are missing the "\" before ".windows-build-tools". Maybe "C:\Users\advik\.windows-build-tools\python27". The dot should be correct, atleast it's ".windows-build-tools" on my machine as well. Another option would be to simply put the path to the python.exe in your system path.

**Comment by justadudewhohacks** [comment]
Hey, did the suggestion fix your issue?
