### ISSUE TITLE
Where is flip() ?

### ISSUE THREAD

**Issue by cotejp** [justadudewhohacks/opencv4nodejs#96]
I can see a `transpose()` method inside the `Mat` object but I cannot find the `flip()` method. It does not seem to be inside the `cv` object either. Am I looking at the wrong places or is it not implemented?

**Comment by justadudewhohacks** [comment]
I think you are right, the binding is missing. I will add it asap.

**Comment by justadudewhohacks** [comment]
flip is available in the newest version via npm now.

**Comment by cotejp** [comment]
Works, thanks!
