### ISSUE TITLE
Using minimum or maximum size with detectMultiScale() causes crash

### ISSUE THREAD

**Issue by cotejp** [justadudewhohacks/opencv4nodejs#97]
I'm trying to define minimum and maximum sizes to use with `detectMultiScale()` but as soon as I do, I get a crash.

This works:
```javascript
const faceClassifier = new cv.CascadeClassifier(cv.HAAR_FRONTALFACE_DEFAULT);
faceClassifier.detectMultiScale(frame);
````

This does not:
```javascript
const faceClassifier = new cv.CascadeClassifier(cv.HAAR_FRONTALFACE_DEFAULT);
faceClassifier.detectMultiScale(frame, 1.1, 3, 0, new Size(100, 100));
```

**Comment by justadudewhohacks** [comment]
Okay this is strange, it is working for me. 

Could you verify that it indeed crashes in `detectMultiScale` and that `frame` is not empty? Maybe it simply could not detect a face for that frame and crashes at some later point in time.

Which OpenCV version are you using?

**Comment by cotejp** [comment]
This is my fault. In my code I used `new Size()` instead of `new cv.Size()`. Sorry for the trouble.
